# cloudbuild.yaml
steps:
  # 1. Construction de l'image Docker
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/votre-service-bot:$COMMIT_SHA", "."]

  # 2. Envoi de l'image au Container Registry (GCR)
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/votre-service-bot:$COMMIT_SHA"]

  # 3. Déploiement de l'image sur Cloud Run
  - name: "gcr.io/google.com/cloudsdk/cloud-sdk"
    args: [
        "gcloud",
        "run",
        "deploy",
        "votre-service-bot", # REMPLACEZ PAR LE NOM DE VOTRE SERVICE CLOUD RUN
        "--image",
        "gcr.io/$PROJECT_ID/votre-service-bot:$COMMIT_SHA",
        "--region",
        "europe-west1", # REMPLACEZ PAR VOTRE RÉGION (ex: us-central1)
        "--platform",
        "managed",
      ]

# Correction du bug de journalisation/service account
options:
  logging: CLOUD_LOGGING_ONLY
