const quizGastronomieAfricaine = {
  title: "Gastronomie Africaine & Diaspora",
  description: "Explorez les saveurs extraordinaires de la cuisine africaine et de sa diaspora mondiale !",
  emoji: "🌍",
  questions: [
    { question: "Quel pays africain est considéré comme ayant la cuisine la plus variée et raffinée du continent ?", answers: ["Nigeria", "Maroc", "Éthiopie", "Sénégal"], correct: 3, explanation: "La cuisine sénégalaise est reconnue comme l'une des plus sophistiquées d'Afrique. Le thiéboudienne (riz au poisson) est considéré comme le plat national et a été classé au patrimoine culturel immatériel de l'UNESCO en 2021. Dakar est la capitale gastronomique de l'Afrique de l'Ouest." },
    { question: "Qu'est-ce que l'injera, base de la cuisine éthiopienne et érythréenne ?", answers: ["Un ragoût de viande épicé", "Une galette fermentée à base de teff (céréale locale) servie comme assiette comestible et ustensile", "Un plat de légumes sautés", "Un pain plat sans levain"], correct: 1, explanation: "L'injera est une galette fermentée spongieuse à base de teff (céréale endémique d'Éthiopie, riche en fer et protéines). Elle sert à la fois d'assiette, de cuillère et de pain. On y dépose les wats (ragoûts épicés) et on mange avec les mains. L'injera fermentée a un goût légèrement acidulé caractéristique." },
    { question: "Quel est le plat national du Sénégal classé au patrimoine UNESCO en 2021 ?", answers: ["Le mafé (ragoût d'arachide)", "Le yassa poulet", "Le thiéboudienne (riz au poisson)", "Le domoda"], correct: 2, explanation: "Le thiéboudienne (thieb = riz, dienne = poisson en wolof) est le plat national sénégalais. Riz cuit dans une sauce tomate avec poisson, légumes (manioc, aubergine africaine, chou), épices. Classé au patrimoine culturel immatériel de l'UNESCO en 2021, première cuisine africaine à obtenir cette reconnaissance." },
    { question: "Quelle huile est fondamentale dans la cuisine d'Afrique de l'Ouest et présente dans la cuisine afro-caribéenne ?", answers: ["L'huile d'olive", "L'huile de palme rouge (riche en bêta-carotène et vitamine E)", "L'huile de tournesol", "L'huile de coco uniquement"], correct: 1, explanation: "L'huile de palme rouge (non raffinée) est l'huile traditionnelle d'Afrique de l'Ouest. Riche en bêta-carotène (couleur rouge-orange) et vitamine E. Utilisée dans le mafé, le ndolé, les sauces gombo. Elle a traversé l'Atlantique avec les esclaves et reste présente dans la cuisine afro-caribéenne (Brésil, Trinidad, Haïti)." },
    { question: "Qu'est-ce que le mafé (ou maafe), plat présent dans toute l'Afrique de l'Ouest ?", answers: ["Une soupe de poisson légère", "Ragoût de viande (bœuf, agneau ou poulet) en sauce épaisse d'arachide avec légumes — originaire du Mali/Sénégal", "Un plat végétarien aux lentilles", "Un couscous nord-africain"], correct: 1, explanation: "Le mafé est un ragoût riche en sauce d'arachide (cacahuète pilée ou beurre d'arachide), tomates, oignon, avec viande et légumes. Originaire des peuples Mandingues (Mali, Sénégal, Guinée). Présent sous différents noms dans toute l'Afrique de l'Ouest. Les arachides, introduites d'Amérique, sont devenues fondamentales dans la cuisine africaine." },
    { question: "Comment l'alimentation africaine a-t-elle influencé la cuisine américaine du Sud (Soul Food) ?", answers: ["Aucune influence", "Les esclaves africains ont apporté okra (gombo), pastèque, sorgho, riz, techniques de friture et nombreuses recettes", "Uniquement les épices", "Seulement le barbecue"], correct: 1, explanation: "La Soul Food américaine est directement issue de la cuisine africaine apportée par les esclaves. Ils ont introduit : gombo (okra), sorgho, pastèque, sésame (benne), taro, techniques de friture, utilisation des parties dévalorisées du porc (pieds, oreilles). Des plats comme le gumbo (louisianais) viennent directement du mot 'ngombo' (gombo en langue bantoue)." },
    { question: "Qu'est-ce que le ndolé, plat national du Cameroun ?", answers: ["Un poulet braisé", "Plat à base de feuilles de ndolé (herbe amère) avec arachides et crevettes ou viande — cuisine bamiléké et bassa", "Une soupe de légumes légère", "Un poisson fumé en sauce"], correct: 1, explanation: "Le ndolé est le plat national camerounais, fait avec des feuilles de ndolé (Vernonia amygdalina, herbe amère désamérisée), arachides pilées, crevettes fumées ou viande. Spécialité des peuples Bassa et Bamiléké. C'est un plat de fête et de célébration, très apprécié dans toute la diaspora camerounaise mondiale." },
    { question: "Quelle boisson fermentée traditionnelle africaine est à la base de nombreuses cérémonies et rites ?", answers: ["Le vin de raisin importé", "Le tchoukoutou (bière de sorgho), le dolo, le vin de palme et le vin de raphia selon les régions", "Le café éthiopien uniquement", "L'eau de coco"], correct: 1, explanation: "Les boissons fermentées africaines traditionnelles varient selon les régions : dolo/tchoukoutou (bière de sorgho, Burkina-Mali), vin de palme (Afrique centrale et de l'Ouest, sève fermentée), vin de raphia (Cameroun, très prisé), hydromel (Éthiopie, tej). Ces boissons ont un rôle central dans les cérémonies, funérailles et rites de passage." },
    { question: "Quel légume originaire d'Afrique de l'Ouest est devenu fondamental dans la cuisine créole américaine et antillaise ?", answers: ["La tomate", "Le gombo (okra, Abelmoschus esculentus) — liant naturel des ragoûts, transporté par les esclaves", "Le piment", "L'igname"], correct: 1, explanation: "Le gombo (okra) est originaire d'Afrique de l'Ouest et centrale. Les esclaves africains l'ont apporté aux Amériques. Son mucilage (substance visqueuse) est un liant naturel pour les soupes et ragoûts. Il donne son nom au gumbo louisianais. Présent dans la cuisine antillaise, brésilienne, cajun et dans tout le Sud des États-Unis." },
    { question: "Quelle cérémonie du café éthiopienne est classée au patrimoine immatériel de l'UNESCO ?", answers: ["La cérémonie n'est pas reconnue", "La cérémonie du café éthiopien (Buna) — 3 services rituels symbolisant respect, amitié et bénédiction", "Uniquement le café en grain exporté", "La culture du café arabica"], correct: 1, explanation: "L'Éthiopie est le berceau du café (Kaffa). La cérémonie du Buna est un rituel social essentiel : les grains sont torréfiés sur place, le café est préparé dans une jebena (cafetière en terre cuite), servi 3 fois (Abol, Tona, Baraka) symbolisant les niveaux de bénédiction. Durée : 1 à 2 heures. Classée UNESCO en 2024." },
  ],
  tips: ["Le thiéboudienne sénégalais est la première cuisine africaine classée au patrimoine UNESCO (2021)", "Le gombo (okra) apporté par les esclaves africains est la base du gumbo louisianais — lien direct Afrique-Amériques", "L'Éthiopie est le berceau mondial du café — la cérémonie du Buna dure 2 heures et est un acte social sacré"],
};
export default quizGastronomieAfricaine;
