/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizArchitecture = {
  title: "Architecture",
  description: "Découvrez les grands styles et chefs-d'œuvre de l'architecture mondiale !",
  emoji: "🏗️",
  questions: [
    { question: "🏗️ Quel est le bâtiment le plus haut du monde ?", answers: ["Empire State Building (New York)", "Shanghai Tower (Chine)", "Burj Khalifa (Dubaï)", "Merdeka 118 (Malaisie)"], correct: 2, explanation: "Le Burj Khalifa à Dubaï, avec ses 828 mètres et 163 étages, est le bâtiment le plus haut du monde depuis 2010. Il a coûté 1,5 milliard de dollars et peut accueillir jusqu'à 35 000 personnes." },
    { question: "🏛️ Quel style architectural caractérise les cathédrales médiévales européennes ?", answers: ["Style baroque", "Style gothique (arcs brisés, voûtes en ogive, grandes fenêtres)", "Style roman", "Style classique"], correct: 1, explanation: "Le style gothique (XIIe-XVe siècle) se caractérise par les arcs brisés, les voûtes en croisée d'ogives, les grandes rosaces et les vitraux colorés. Notre-Dame de Paris, la cathédrale de Reims et Chartres en sont des exemples emblématiques." },
    { question: "🌿 Qu'est-ce que l'architecture bioclimatique ?", answers: ["Construire avec des plantes uniquement", "Concevoir des bâtiments qui utilisent l'environnement naturel (soleil, vent, végétation) pour réduire la consommation d'énergie", "Un style décoratif végétal", "Construire dans la nature sans la modifier"], correct: 1, explanation: "L'architecture bioclimatique intègre les paramètres climatiques locaux dès la conception : orientation pour profiter du soleil en hiver, ventilation naturelle, isolation, végétalisation des toits... Elle réduit fortement la consommation d'énergie." },
    { question: "🇫🇷 Qui a conçu la Tour Eiffel ?", answers: ["Le Corbusier", "Gustave Eiffel", "Haussmann", "Vauban"], correct: 1, explanation: "La Tour Eiffel a été conçue par Gustave Eiffel et construite pour l'Exposition Universelle de 1889. Initialement prévue pour être démontée après 20 ans, elle est devenue le symbole de Paris et le monument le plus visité au monde." },
    { question: "🏘️ Qu'est-ce que l'architecture créole aux Antilles ?", answers: ["Des constructions en béton modernes", "Un style architectural mêlant influences françaises, africaines et locales, adapté au climat tropical", "Des huttes traditionnelles amérindiennes", "L'architecture coloniale uniquement"], correct: 1, explanation: "L'architecture créole antillaise est un mélange unique : galeries couvertes pour l'ombre, persiennes pour la ventilation, toits à double pente pour la pluie, structures légères antisismiques. Elle reflète l'histoire métissée des Antilles." },
    { question: "🌱 Qu'est-ce qu'un bâtiment 'vert' (certifié HQE ou LEED) ?", answers: ["Un bâtiment peint en vert", "Un bâtiment conçu pour minimiser son impact environnemental tout au long de son cycle de vie", "Un bâtiment construit avec du bois uniquement", "Un bâtiment entouré de végétation"], correct: 1, explanation: "Les certifications HQE (France) et LEED (international) évaluent la performance environnementale des bâtiments : consommation d'énergie, qualité de l'air, gestion de l'eau, matériaux durables. Ces bâtiments ont une valeur patrimoniale supérieure." },
  ],
  tips: ["🏗️ L'architecture créole antillaise est un patrimoine culturel unique à préserver", "🌱 L'architecture durable est l'avenir de la construction", "💡 En Guadeloupe, les constructions doivent résister aux cyclones et séismes — une contrainte qui forge des architectes excellents"],
};
export default quizArchitecture;
