/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizLitterature = {
  title: "Littérature",
  description: "Explorez les grandes œuvres et auteurs qui ont marqué l'histoire !",
  emoji: "📖",
  questions: [
    { question: "📖 Qui a écrit 'Les Misérables' ?", answers: ["Émile Zola", "Victor Hugo", "Alexandre Dumas", "Gustave Flaubert"], correct: 1, explanation: "Victor Hugo a publié Les Misérables en 1862. Ce chef-d'œuvre raconte la rédemption de Jean Valjean dans la France du XIXe siècle. C'est l'un des romans les plus vendus de l'histoire et a été adapté en comédie musicale mondiale." },
    { question: "🌴 Quel auteur guadeloupéen a reçu le prix Nobel de littérature ?", answers: ["Aucun auteur guadeloupéen n'a reçu ce prix", "Maryse Condé (en 2018, prix Nobel alternatif)", "Patrick Chamoiseau", "Édouard Glissant"], correct: 1, explanation: "Maryse Condé, auteure guadeloupéenne, a reçu le Prix Nobel alternatif de littérature en 2018 (Nouvelle Académie suédoise). Son œuvre, notamment 'Moi, Tituba sorcière...' et 'Ségou', est mondialement reconnue." },
    { question: "📚 Qu'est-ce que la Négritude en littérature ?", answers: ["Un genre littéraire africain-américain", "Un mouvement littéraire et culturel affirmant la fierté et la valeur des cultures africaines et antillaises, fondé par Césaire, Senghor et Damas", "Un style d'écriture moderne", "Un courant littéraire brésilien"], correct: 1, explanation: "La Négritude est un mouvement fondé dans les années 1930 par Aimé Césaire (Martinique), Léopold Sédar Senghor (Sénégal) et Léon-Gontran Damas (Guyane). Il affirme la valeur des cultures africaines et rejette l'assimilation coloniale." },
    { question: "📝 Qui a écrit 'Cahier d'un retour au pays natal' ?", answers: ["Patrick Chamoiseau", "Édouard Glissant", "Aimé Césaire", "Raphaël Confiant"], correct: 2, explanation: "Aimé Césaire, poète et homme politique martiniquais (1913-2008), a écrit ce poème fondateur de la Négritude en 1939. Césaire a aussi été maire de Fort-de-France pendant 56 ans et député de la Martinique." },
    { question: "🌍 Qu'est-ce que la littérature postcoloniale ?", answers: ["La littérature des anciennes colonies uniquement", "Des œuvres qui examinent les effets du colonialisme, questionnent les récits dominants et valorisent les voix marginalisées", "La littérature écrite après la guerre", "Un genre de science-fiction"], correct: 1, explanation: "La littérature postcoloniale explore les conséquences du colonialisme sur les identités, cultures et sociétés. Des auteurs comme Frantz Fanon, Chinua Achebe, Toni Morrison et Maryse Condé en sont des représentants majeurs." },
    { question: "🏆 Quel est le prix littéraire le plus prestigieux en France ?", answers: ["Le Prix Médicis", "Le Prix Renaudot", "Le Prix Goncourt", "Le Prix Femina"], correct: 2, explanation: "Le Prix Goncourt, décerné depuis 1903, est le prix littéraire le plus médiatisé et influent en France. Il garantit des ventes de plusieurs centaines de milliers d'exemplaires. Il est remis chaque année en novembre par l'Académie Goncourt." },
  ],
  tips: ["📖 Lire 20 minutes par jour change une vie — choisissez des livres qui vous challengent", "🌴 La littérature antillaise et africaine francophone est riche et mondiale", "💡 Aimé Césaire et Maryse Condé sont des fiertes de la Guadeloupe et des Antilles"],
};
export default quizLitterature;
