/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizMedecine = {
  title: "Médecine",
  description: "Explorez les connaissances médicales fondamentales pour prendre soin de votre santé !",
  emoji: "🩺",
  questions: [
    { question: "🩺 Combien d'os le corps humain adulte contient-il ?", answers: ["100 os", "206 os", "350 os", "512 os"], correct: 1, explanation: "Le corps humain adulte contient 206 os. À la naissance, un bébé en a environ 270-300 — certains fusionnent au fil de la croissance. Le fémur (os de la cuisse) est le plus long et le plus solide." },
    { question: "❤ Quel organe pompe le sang dans tout le corps ?", answers: ["Les poumons", "Les reins", "Le foie", "Le cœur"], correct: 3, explanation: "Le cœur est un muscle creux qui bat environ 70 fois par minute, soit plus de 100 000 fois par jour et 2,5 milliards de fois dans une vie. Il pompe 5 litres de sang par minute, soit l'équivalent de la totalité du sang du corps toutes les minutes." },
    { question: "🦠 Qu'est-ce qu'un antibiotique ?", answers: ["Un médicament qui tue les virus", "Un médicament qui tue ou inhibe les bactéries — inefficace contre les virus", "Un vaccin préventif", "Un anti-inflammatoire"], correct: 1, explanation: "Les antibiotiques (comme la pénicilline) agissent uniquement contre les bactéries. Ils sont INUTILES contre les virus (rhume, grippe, COVID). Leur usage excessif crée des bactéries résistantes — un problème de santé publique mondial." },
    { question: "🧬 Qu'est-ce que l'ADN ?", answers: ["Un type de protéine", "L'acide désoxyribonucléique — la molécule qui contient toutes les instructions génétiques d'un être vivant", "Un nutriment essentiel", "Un type d'hormone"], correct: 1, explanation: "L'ADN contient le 'code' génétique de chaque être vivant. Chaque cellule humaine contient 2 mètres d'ADN enroulé. Notre génome contient environ 20 000 à 25 000 gènes qui déterminent nos caractéristiques héréditaires." },
    { question: "🌴 Quelles maladies sont particulièrement surveillées aux Antilles ?", answers: ["La grippe et le rhume uniquement", "La dengue, le chikungunya et le zika (transmises par le moustique tigre Aedes albopictus)", "Les maladies des pays froids uniquement", "Aucune maladie tropicale particulière"], correct: 1, explanation: "Aux Antilles, le moustique Aedes albopictus (moustique tigre) transmet la dengue, le chikungunya et le zika. La prévention passe par l'élimination des eaux stagnantes où pondent les moustiques, et la protection contre les piqûres." },
    { question: "💊 Qu'est-ce qu'un vaccin ?", answers: ["Un médicament qui guérit une maladie", "Un produit qui stimule le système immunitaire pour qu'il apprenne à reconnaître et combattre un pathogène spécifique", "Un antibiotique préventif", "Un supplément vitaminique"], correct: 1, explanation: "Un vaccin prépare le système immunitaire à reconnaître un pathogène (virus ou bactérie) sans développer la maladie. Si vous êtes ensuite exposé au vrai pathogène, votre corps peut le combattre rapidement. La vaccination a éradiqué la variole et presque éliminé la polio." },
  ],
  tips: ["🩺 MLC Health (partenaire Reussitess®) utilise l'IA pour le diagnostic médical préventif", "🌴 Aux Antilles, éliminez les eaux stagnantes pour éviter la dengue", "💊 Ne prenez jamais d'antibiotiques sans prescription médicale"],
};
export default quizMedecine;
