const quizNumerologie = {
  title: "Numérologie — Chiffres & Destinées",
  description: "Découvrez les secrets des chiffres et leur influence sur votre vie !",
  emoji: "🔢",
  questions: [
    { question: "Comment calcule-t-on son Chemin de Vie en numérologie ?", answers: ["En additionnant les lettres de son prénom", "En additionnant tous les chiffres de sa date de naissance jusqu'à obtenir un chiffre entre 1 et 9", "En soustrayant l'année de naissance de l'année actuelle", "En multipliant jour et mois de naissance"], correct: 1, explanation: "Le Chemin de Vie est le calcul principal en numérologie. Ex: né le 15/03/1990 → 1+5+0+3+1+9+9+0 = 28 → 2+8 = 10 → 1+0 = 1. Chemin de Vie 1. Exceptions : 11, 22, 33 sont des Nombres Maîtres qu'on ne réduit pas." },
    { question: "Que représente le chiffre 1 en numérologie ?", answers: ["La famille et l'amour", "Le leadership, l'indépendance, le pionnier", "La spiritualité et la sagesse", "L'harmonie et la diplomatie"], correct: 1, explanation: "Le 1 en numérologie représente le leadership, l'indépendance, l'originalité et l'esprit pionnier. Les personnes avec ce chiffre dominant sont des initiateurs naturels, ambitieux et autonomes. Ils ouvrent des voies que les autres suivent ensuite." },
    { question: "Quels sont les Nombres Maîtres en numérologie qui ne sont jamais réduits ?", answers: ["7, 8, 9", "10, 20, 30", "11, 22, 33", "12, 21, 33"], correct: 2, explanation: "Les Nombres Maîtres 11, 22 et 33 ont une vibration spéciale et ne sont jamais réduits à un chiffre simple. Le 11 = intuition et illumination spirituelle. Le 22 = maître bâtisseur. Le 33 = maître enseignant. Ces personnes ont un potentiel exceptionnel mais aussi des défis plus grands." },
    { question: "Comment calcule-t-on le Nombre d'Expression (ou de Destin) en numérologie ?", answers: ["Avec la date de naissance uniquement", "En convertissant les lettres du nom complet de naissance en chiffres", "Avec le prénom seul", "En additionnant le Chemin de Vie et l'âge actuel"], correct: 1, explanation: "Le Nombre d'Expression se calcule en convertissant chaque lettre du nom complet de naissance en chiffre (A=1, B=2... I=9, J=1... etc.) puis en additionnant tout. Il représente les talents naturels, les aptitudes et la mission de vie." },
    { question: "Quelle est la signification du chiffre 7 en numérologie ?", answers: ["L'amour et les relations", "L'argent et la réussite matérielle", "La spiritualité, l'analyse, la sagesse intérieure", "L'action et le sport"], correct: 2, explanation: "Le 7 est le nombre de la spiritualité, de l'analyse profonde et de la sagesse. Les personnes influencées par le 7 cherchent la vérité cachée, aiment la solitude et la réflexion. Souvent attirés par la philosophie, la science ou la spiritualité. Chiffre sacré dans de nombreuses traditions." },
    { question: "Que signifie le nombre 8 dans la numérologie et dans la culture asiatique ?", answers: ["Malchance et obstacles", "Pouvoir, abondance et succès matériel — très chanceux en Asie", "Amour et romantisme", "Spiritualité et détachement"], correct: 1, explanation: "Le 8 représente le pouvoir, l'abondance, le succès matériel et le karma. En Chine, le 8 est le chiffre le plus chanceux (8 se prononce 'ba', proche de 'fa' qui signifie prospérité). Les JO de Pékin ont commencé le 08/08/2008 à 8h08." },
    { question: "Qu'est-ce que l'Année Personnelle en numérologie ?", answers: ["L'âge de la personne", "Un cycle de 9 ans — chaque année a une vibration spécifique influençant les événements", "L'année de naissance réduite", "La somme du Chemin de Vie et du mois actuel"], correct: 1, explanation: "L'Année Personnelle se calcule en additionnant le jour + mois de naissance + l'année en cours. Elle indique les thèmes dominants de l'année. An 1 = nouveaux départs. An 9 = fins et bilans. Cycle complet de 9 ans." },
    { question: "Que représente le chiffre 9 en numérologie, dernier chiffre du cycle ?", answers: ["Les débuts et nouvelles aventures", "L'humanisme, la sagesse universelle, les fins de cycles", "La routine et la stabilité", "L'argent et les affaires"], correct: 1, explanation: "Le 9 est le nombre de l'accomplissement, de l'humanisme et des fins de cycles. Les personnes influencées par le 9 ont souvent une vocation d'aide aux autres, un idéalisme fort. C'est aussi le nombre du karma : ce qu'on sème, on le récolte." },
    { question: "Comment convertit-on la lettre 'S' en chiffre en numérologie Pythagoricienne ?", answers: ["S = 1", "S = 5", "S = 9", "S = 7"], correct: 0, explanation: "Dans le système Pythagoricien : A=1, B=2, C=3, D=4, E=5, F=6, G=7, H=8, I=9, J=1, K=2, L=3, M=4, N=5, O=6, P=7, Q=8, R=9, S=1, T=2, U=3, V=4, W=5, X=6, Y=7, Z=8. La séquence recommence à 1 après I (9)." },
    { question: "Quelle est la signification des chiffres répétés que l'on voit souvent (ex: 11:11, 333, 444) ?", answers: ["Pure coïncidence mathématique", "Nombres Anges — messages de guidance spirituelle selon la numérologie angélique", "Erreur de l'horloge", "Signe de malchance"], correct: 1, explanation: "En numérologie angélique, ces séquences répétées sont appelées Nombres Anges. 111 = manifestation et pensées qui se matérialisent. 222 = équilibre et foi. 333 = soutien divin. 444 = protection. 555 = changements majeurs. 999 = fin d'un cycle important." },
  ],
  tips: ["Votre Chemin de Vie révèle votre mission principale — calculez-le avec votre date complète de naissance", "Les Nombres Maîtres 11, 22, 33 ne se réduisent jamais", "La numérologie est complémentaire de l'astrologie — les deux ensemble donnent un portrait plus complet"],
};
export default quizNumerologie;
