/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizFranceEssentiel = {
  title: "France — Essentiel Voyage & Culture",
  description: "Droits, règles, culture et bons à savoir pour visiter la France !",
  emoji: "🇫🇷",
  questions: [
    { question: "🛂 Les ressortissants guadeloupéens ont-ils besoin d'un passeport pour aller en France métropolitaine ?", answers: ["Oui, passeport obligatoire", "Non, carte d'identité suffit", "Visa nécessaire", "ESTA obligatoire"], correct: 1, explanation: "La Guadeloupe est un département français d'outre-mer (DOM). Les Guadeloupéens sont citoyens français et peuvent voyager en métropole avec uniquement leur carte nationale d'identité." },
    { question: "🚬 À quel âge peut-on acheter tabac et alcool en France ?", answers: ["16 ans", "18 ans", "21 ans", "19 ans"], correct: 1, explanation: "En France, l'âge légal est 18 ans pour alcool et tabac. Depuis 2009, les buralistes et supermarchés sont tenus de vérifier les pièces d'identité. Des amendes lourdes s'appliquent en cas de vente à des mineurs." },
    { question: "🏥 La Sécurité Sociale couvre-t-elle les soins en France métropolitaine pour un Guadeloupéen ?", answers: ["Non, couverture différente", "Oui, même couverture nationale", "Partielle seulement", "Uniquement les urgences"], correct: 1, explanation: "La Sécurité Sociale française est nationale. Un Guadeloupéen a exactement les mêmes droits en métropole qu'en Guadeloupe. La carte Vitale fonctionne partout en France." },
    { question: "🚗 Quelle est la limite de vitesse sur autoroute en France par temps de pluie ?", answers: ["130 km/h", "110 km/h", "90 km/h", "100 km/h"], correct: 1, explanation: "Par temps de pluie, la limite sur autoroute passe de 130 km/h à 110 km/h. En cas de brouillard avec visibilité inférieure à 50m, la limite est 50 km/h sur toutes les routes." },
    { question: "💶 Quel est le montant du SMIC horaire brut en France en 2024 ?", answers: ["9,22€", "11,27€", "10,03€", "12,50€"], correct: 1, explanation: "Le SMIC horaire brut en France était de 11,27€ en 2024 (11,65€ en 2025). Le SMIC mensuel brut dépasse 1 766€. Il est revalorisé chaque année au 1er janvier." },
    { question: "🏖️ Quel droit français permet aux salariés de refuser de travailler en vacances ?", answers: ["Droit au repos", "Droit à la déconnexion", "Droit aux congés payés", "Droit au silence"], correct: 2, explanation: "En France, tout salarié a droit à 5 semaines de congés payés par an (25 jours ouvrés). C'est l'un des droits sociaux les plus protecteurs d'Europe, acquis par les luttes ouvrières de 1936." },
    { question: "🚇 Dans quelle ville française le réseau de métro est le plus étendu d'Europe ?", answers: ["Lyon", "Marseille", "Paris", "Lille"], correct: 2, explanation: "Le métro de Paris (RATP) compte 16 lignes et 302 stations, c'est le 2ème réseau le plus dense d'Europe après Londres. Il transporte 1,5 milliard de voyageurs par an." },
    { question: "🍷 La France est le premier producteur mondial de quel produit ?", answers: ["Fromage", "Parfum", "Vin", "Mode"], correct: 2, explanation: "La France est le premier ou deuxième producteur mondial de vin selon les années, avec des régions mythiques : Bordeaux, Bourgogne, Champagne, Alsace, Côtes du Rhône. Le vin représente 12 milliards d'euros d'exportations annuelles." },
    { question: "📋 Quel document est obligatoire pour ouvrir un compte bancaire en France ?", answers: ["Seulement passeport", "Passeport + justificatif de domicile", "Visa uniquement", "Carte d'identité seule"], correct: 1, explanation: "Pour ouvrir un compte en France : pièce d'identité + justificatif de domicile (facture EDF, quittance de loyer...) + parfois justificatif de revenus. Tout résident a le droit à un compte bancaire (droit au compte)." },
    { question: "🌡️ Quelle est la région de France la plus chaude en été ?", answers: ["Bretagne", "Normandie", "Provence-Alpes-Côte d'Azur (PACA)", "Alsace"], correct: 2, explanation: "La région PACA (Marseille, Nice, Toulon) est la plus chaude de France métropolitaine avec des étés dépassant souvent 35-40°C. La canicule de 2003 a tué 15 000 personnes en France, principalement dans le Sud." },
  ],
  tips: ["Carte Vitale valable partout en France pour les Guadeloupéens", "Le pourboire n'est pas obligatoire en France, contrairement aux USA", "La France a le droit du travail le plus protecteur d'Europe — 35h, 5 semaines de congés"],
};
export default quizFranceEssentiel;
