/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizImmobilier = {
  title: "Immobilier",
  description: "Construisez votre patrimoine grâce à l'investissement immobilier !",
  emoji: "🏠",
  questions: [
    { question: "🏠 Qu'est-ce que la règle des 1% en immobilier locatif ?", answers: ["Épargner 1% du prix d'achat par an", "Le loyer mensuel devrait idéalement représenter au moins 1% du prix d'achat pour assurer la rentabilité", "Ne jamais dépenser plus de 1% en travaux", "Le rendement locatif minimum acceptable"], correct: 1, explanation: "La règle des 1% stipule que le loyer mensuel brut devrait atteindre environ 1% du prix d'achat. Un bien à 150 000€ devrait rapporter 1 500€/mois. En France, c'est difficile dans les grandes villes mais atteignable dans certaines villes moyennes." },
    { question: "💰 Qu'est-ce que le cashflow en immobilier ?", answers: ["Le prix d'un bien", "L'argent qui reste chaque mois après avoir payé toutes les charges (crédit, taxe, assurance, charges...)", "Le bénéfice à la revente", "La valeur locative d'un bien"], correct: 1, explanation: "Le cashflow est la différence entre les loyers perçus et toutes les dépenses liées au bien (mensualités de crédit, charges de copropriété, taxe foncière, assurance, gestion locative). Un cashflow positif signifie que le bien se paye tout seul." },
    { question: "🏗 Qu'est-ce que la loi Pinel en France ?", answers: ["Une loi sur la construction", "Un dispositif fiscal permettant de réduire ses impôts en investissant dans l'immobilier neuf locatif", "Un droit des locataires", "Une réglementation sur les loyers"], correct: 1, explanation: "La loi Pinel permet aux investisseurs en immobilier neuf de bénéficier d'une réduction d'impôt en échange d'un engagement de location à loyers plafonnés pendant 6, 9 ou 12 ans." },
    { question: "📊 Qu'est-ce que le taux de rendement brut d'un investissement locatif ?", answers: ["(Loyer annuel / Prix d'achat) × 100", "Prix de vente - Prix d'achat", "Loyer mensuel × 12", "Bénéfice net après impôts"], correct: 0, explanation: "Le rendement brut = (loyer annuel / prix d'achat) × 100. Un bien acheté 100 000€ loué 600€/mois génère 7 200€/an, soit un rendement brut de 7,2%. Le rendement net déduit toutes les charges." },
    { question: "🌴 Pourquoi investir dans l'immobilier en Guadeloupe peut être avantageux ?", answers: ["Les prix sont très bas", "Dispositifs fiscaux spécifiques DOM (Girardin), forte demande locative, et cadre de vie attractif", "Il n'y a aucun avantage", "Les loyers sont très élevés"], correct: 1, explanation: "La Guadeloupe bénéficie de dispositifs fiscaux spécifiques aux DOM (loi Girardin, défiscalisation outre-mer) plus avantageux qu'en métropole. La demande locative est soutenue et le marché est moins saturé qu'en France métropolitaine." },
    { question: "🔑 Qu'est-ce qu'une SCPI ?", answers: ["Une société de construction", "Une Société Civile de Placement Immobilier — investir dans l'immobilier sans gérer de bien physique", "Un type de crédit immobilier", "Une assurance propriétaire"], correct: 1, explanation: "Les SCPI permettent d'investir dans l'immobilier collectivement à partir de quelques centaines d'euros. Vous recevez des revenus locatifs proportionnels à vos parts, sans vous occuper de la gestion. C'est l'immobilier 'passif'." },
  ],
  tips: ["🏠 L'immobilier est la première source de patrimoine des millionnaires français", "🌴 Les DOM bénéficient de dispositifs fiscaux uniques — renseignez-vous", "💡 Commencez par votre résidence principale si possible — chaque mensualité construit votre patrimoine"],
};
export default quizImmobilier;
