/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizDroitsCitoyen = {
  title: "Droits & Devoirs du Citoyen Français",
  description: "Connaissez-vous vraiment vos droits et devoirs en tant que citoyen français ?",
  emoji: "🇫🇷",
  questions: [
    { question: "À quel âge devient-on majeur et citoyen à part entière en France ?", answers: ["16 ans", "18 ans", "21 ans", "17 ans"], correct: 1, explanation: "La majorité civile est fixée à 18 ans en France depuis 1974 (abaissée de 21 ans). À 18 ans : droit de vote, droit de conduire sans accompagnateur, responsabilité pénale pleine, signature de contrats. En Guadeloupe et dans tous les DOM, les mêmes règles s'appliquent qu'en métropole." },
    { question: "Quel est le délai maximum de garde à vue en France pour un crime ou délit ordinaire ?", answers: ["12 heures", "24 heures renouvelables une fois = 48 heures maximum", "72 heures", "96 heures"], correct: 1, explanation: "La garde à vue ordinaire dure 24 heures, renouvelable une fois par le procureur = 48 heures maximum. Des délais dérogatoires existent : trafic de stupéfiants, terrorisme (96h à 144h). Vos droits en GAV : prévenir un proche, consulter un médecin, être assisté d'un avocat dès la 1ère heure." },
    { question: "Qu'est-ce que le droit au logement opposable (DALO) en France ?", answers: ["Le droit de squatter un logement vide", "Le droit pour toute personne sans logement décent de saisir l'État qui doit reloger — loi du 5 mars 2007", "Le droit de refuser une expulsion", "Le droit à une aide au loyer automatique"], correct: 1, explanation: "La loi DALO (2007) reconnaît le logement comme droit fondamental opposable à l'État. Les personnes sans domicile, logées dans des conditions indignes ou en attente de logement social depuis trop longtemps peuvent saisir une commission de médiation. Si l'État ne reloger pas, le juge administratif peut condamner l'État à une astreinte." },
    { question: "Quel est le devoir civique le plus important en France, symbolisant l'appartenance à la nation ?", answers: ["Payer ses impôts uniquement", "Voter aux élections — suffrage universel, direct et secret depuis 1944 (femmes) et 1848 (hommes)", "Servir dans l'armée", "Apprendre le français"], correct: 1, explanation: "Le vote est le devoir civique fondamental de la démocratie française. Le suffrage universel masculin date de 1848. Les femmes ont obtenu le droit de vote en 1944 (ordonnance du général de Gaulle). En France, voter n'est pas obligatoire légalement (contrairement à la Belgique ou l'Australie) mais est considéré comme un devoir moral citoyen." },
    { question: "Quels sont vos droits si la police vous contrôle dans la rue en France ?", answers: ["Obligation de répondre à toutes les questions", "Obligation de présenter un justificatif d'identité, mais droit de garder le silence sur les questions autres que l'identité", "Droit de refuser tout contrôle", "Obligation de suivre la police sans question"], correct: 1, explanation: "Lors d'un contrôle d'identité : vous devez justifier de votre identité (CNI, passeport, permis). Vous pouvez garder le silence sur les autres questions. Vous pouvez demander le motif du contrôle. Vous ne pouvez pas être fouillé sans raison légitime (flagrant délit, réquisition du procureur). Tout contrôle discriminatoire basé sur l'apparence physique est illégal (contrôle au faciès)." },
    { question: "Qu'est-ce que la présomption d'innocence en droit français ?", answers: ["Toute personne est innocente jusqu'à ce qu'elle soit prouvée coupable par une décision judiciaire définitive", "La police doit prouver l'innocence", "Applicable uniquement devant les tribunaux civils", "Uniquement pour les mineurs"], correct: 0, explanation: "La présomption d'innocence est un principe fondamental du droit français (article 9 DDHC 1789, article préliminaire CPP). Toute personne accusée est réputée innocente jusqu'au jugement définitif de culpabilité. Violation : condamnable en justice. Les médias violent souvent ce principe en traitant les suspects comme des coupables avant jugement." },
    { question: "Quel droit constitutionnel français permet à toute personne de refuser un acte médical ?", answers: ["Droit impossible — les médecins décident", "Droit au consentement éclairé — tout patient peut refuser tout soin, même vital, après information complète", "Uniquement pour les opérations chirurgicales électives", "Seulement si majeur et en bonne santé mentale certifiée"], correct: 1, explanation: "Le droit au consentement éclairé (loi Kouchner 2002) est un droit fondamental : tout patient peut refuser tout acte médical, même vital. Le médecin doit informer clairement des risques et alternatives. Exceptions très limitées : urgence vitale avec personne inconsciente, hospitalisations psychiatriques sous contrainte selon procédure stricte." },
    { question: "Qu'est-ce que la laïcité, principe constitutionnel français, et ce qu'elle implique ?", answers: ["L'interdiction de toute religion en France", "La séparation de l'État et des religions — l'État ne reconnaît aucune religion, la pratique religieuse privée est libre", "L'obligation d'être athée pour les fonctionnaires", "L'interdiction du voile dans tous les espaces publics"], correct: 1, explanation: "La laïcité (loi 1905 séparation Église-État) garantit : liberté de conscience et de culte dans la sphère privée, neutralité de l'État vis-à-vis de toutes les religions, interdiction de signes religieux ostensibles pour les agents de l'État en service. Elle ne s'applique pas aux particuliers dans l'espace public (une femme peut porter le voile dans la rue)." },
    { question: "Quels sont les droits d'un salarié en cas de licenciement abusif en France ?", answers: ["Aucun recours possible", "Saisir le Conseil de Prud'hommes dans les 12 mois — peut obtenir réintégration ou indemnités selon l'ancienneté", "Seulement une lettre de réclamation", "Recours uniquement si plus de 5 ans d'ancienneté"], correct: 1, explanation: "Un salarié licencié sans cause réelle et sérieuse peut saisir le Conseil de Prud'hommes dans un délai de 12 mois. Le juge peut ordonner réintégration ou indemnités (barème Macron : de 1 à 20 mois de salaire selon ancienneté). Des indemnités légales de licenciement sont dues à partir d'8 mois d'ancienneté (1/4 de mois de salaire par année)." },
    { question: "Quel document officiel français prouve votre identité et votre nationalité à l'international ?", answers: ["Le permis de conduire uniquement", "La Carte Nationale d'Identité (CNI) valable 10 ans et le passeport valable 10 ans — tous deux documents officiels", "Uniquement le passeport pour l'international", "L'acte de naissance uniquement"], correct: 1, explanation: "La CNI française (valable 10 ans pour les adultes) est acceptée dans l'espace Schengen et de nombreux pays comme document de voyage. Le passeport (valable 10 ans) est requis hors Schengen. La CNI biométrique actuelle, délivrée depuis 2021, est valable 10 ans (les anciennes cartes émises avant 2014 ont une validité prolongée automatiquement à 15 ans)." },
  ],
  tips: ["En garde à vue, vous avez le droit à un avocat dès la 1ère heure — exercez-le systématiquement", "La présomption d'innocence protège tout citoyen jusqu'au jugement définitif — même en cas de flagrant délit", "La laïcité n'interdit pas la religion dans la sphère privée — elle garantit la liberté de conscience"],
};
export default quizDroitsCitoyen;
