/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizBelgiqueEssentiel = {
  title: "Belgique — Essentiel Voyage & Culture",
  description: "Droits, règles, culture et bons à savoir avant d'aller en Belgique !",
  emoji: "🇧🇪",
  questions: [
    { question: "🛂 Faut-il un document spécial pour voyager en Belgique depuis la France ?", answers: ["Visa obligatoire", "Passeport biométrique", "Carte d'identité ou passeport suffit (Schengen)", "ESTA"], correct: 2, explanation: "La Belgique est dans l'espace Schengen. Les Français et Guadeloupéens (citoyens français) peuvent y aller avec simplement leur carte nationale d'identité. Pas de contrôle aux frontières." },
    { question: "🍟 La Belgique dispute à qui la paternité des frites ?", answers: ["Aux Américains", "À la France", "Aux Pays-Bas", "À l'Espagne"], correct: 1, explanation: "Les Belges affirment avoir inventé les frites, non les Français ! Le terme 'French fries' viendrait des soldats américains qui ont découvert les frites en Belgique lors de la WWI, la langue de l'armée belge étant parfois française." },
    { question: "🗣️ Combien de langues officielles la Belgique possède-t-elle ?", answers: ["1", "2", "3", "4"], correct: 2, explanation: "La Belgique a 3 langues officielles : le néerlandais (Flandre, 60%), le français (Wallonie et Bruxelles, 35%) et l'allemand (petite communauté à l'est, 1%). Bruxelles est officiellement bilingue français-néerlandais." },
    { question: "🚗 La Belgique a-t-elle des autoroutes payantes comme la France ?", answers: ["Oui, même système de péage", "Non, autoroutes gratuites", "Payantes seulement pour les étrangers", "Vignette obligatoire"], correct: 1, explanation: "Les autoroutes belges sont GRATUITES, l'une des rares exceptions en Europe de l'Ouest. Par contre, les camions paient une taxe kilométrique. Pour entrer à Bruxelles en voiture, une vignette LEZ (Zone à faibles émissions) est obligatoire depuis 2018." },
    { question: "🍺 Combien de bières différentes la Belgique produit-elle officiellement ?", answers: ["100", "500", "Plus de 1 500", "300"], correct: 2, explanation: "La Belgique produit plus de 1 500 bières différentes ! Bières trappistes (Chimay, Rochefort, Orval...), lambic, gueuze, kriek... La culture brassicole belge est classée au patrimoine mondial de l'UNESCO depuis 2016." },
    { question: "🏛️ Bruxelles est le siège de quelles organisations internationales majeures ?", answers: ["ONU et FMI", "OTAN et Union Européenne", "UNESCO et OCDE", "OMS et Banque Mondiale"], correct: 1, explanation: "Bruxelles abrite le siège de l'OTAN et les principales institutions de l'Union Européenne (Commission, Parlement, Conseil). C'est la 'capitale de l'Europe'. Des dizaines de milliers d'eurocrates y travaillent." },
    { question: "🚲 Quel système de vélos en libre-service est célèbre à Bruxelles ?", answers: ["Vélib", "Villo", "Donkey Republic", "Blue-bike"], correct: 1, explanation: "Villo est le système de vélos en libre-service de Bruxelles avec 5 000 vélos et 360 stations. La Belgique est très cycliste : la Flandre notamment a plus de 15 000 km de pistes cyclables balisées." },
    { question: "🍫 La Belgique est mondialement connue pour quel produit gastronomique de luxe ?", answers: ["Le fromage", "Le chocolat", "Les gaufres", "La charcuterie"], correct: 1, explanation: "Le chocolat belge est reconnu mondialement comme le meilleur. Marques emblématiques : Godiva, Neuhaus, Côte d'Or, Pierre Marcolini. La Belgique produit 220 000 tonnes de chocolat par an, avec plus de 2 000 chocolatiers artisanaux." },
    { question: "🌧️ Quel est le nombre moyen de jours de pluie par an à Bruxelles ?", answers: ["50 jours", "100 jours", "130 jours", "200 jours"], correct: 2, explanation: "Bruxelles reçoit de la pluie environ 130 jours par an. Le climat est tempéré océanique avec des étés doux et des hivers froids. Un imperméable ou parapluie est recommandé en toute saison, surtout d'octobre à mars." },
    { question: "🎭 Quel personnage de bande dessinée belge est connu dans le monde entier ?", answers: ["Astérix", "Lucky Luke", "Tintin", "Les Schtroumpfs"], correct: 2, explanation: "Tintin, créé par Hergé (Georges Remi) en 1929, est le personnage de BD belge le plus mondialement célèbre. La Belgique est la capitale mondiale de la BD avec 700 auteurs actifs. Tintin a été traduit en 70 langues." },
  ],
  tips: ["Autoroutes gratuites mais vignette LEZ obligatoire pour entrer dans Bruxelles en voiture", "3 langues officielles — parlez français en Wallonie et Bruxelles, néerlandais en Flandre", "Le chocolat et les frites belges sont une fierté nationale — goûtez l'original !"],
};
export default quizBelgiqueEssentiel;
