const quizCuisineAntillaise = {
  title: "Cuisine Antillaise — Recettes & Secrets",
  description: "Plongez dans la richesse culinaire de la Guadeloupe, la Martinique et toute la Caraïbe !",
  emoji: "🦀",
  questions: [
    { question: "Quels sont les ingrédients essentiels du colombo antillais ?", answers: ["Curry indien pur", "Poudre de colombo (curcuma, cumin, coriandre, moutarde, fenugrec) + viande + légumes + piment", "Simplement du curry en poudre avec du riz", "Épices françaises uniquement"], correct: 1, explanation: "Le colombo antillais est l'héritage des travailleurs indiens-tamouls arrivés aux Antilles après l'abolition de l'esclavage (1848). La poudre de colombo est un mélange maison : curcuma, cumin, coriandre, moutarde, fenugrec. Il se prépare avec cabri, poulet, porc ou poisson. Plat emblématique de la Guadeloupe et Martinique." },
    { question: "Quelle est la technique traditionnelle de préparation du boudin antillais qui le différencie du boudin métropolitain ?", answers: ["Il est uniquement blanc", "Boudin créole : sang de porc + épices antillaises (piment, cive, thym, persil) + pain rassis — très épicé et parfumé", "Il est fait avec du poisson uniquement", "Il n'y a aucune différence"], correct: 1, explanation: "Le boudin créole antillais est une institution. Composé de sang de porc, pain rassis trempé, cive (ciboule), piment végétarien, thym, persil, poivre et épices créoles. Bien plus épicé et parfumé que le boudin métropolitain. Servi à toutes les fêtes, plage et Noël. Il existe aussi la version blanche et le boudin de poisson." },
    { question: "Qu'est-ce que le 'féroce d'avocat', entrée emblématique martiniquaise et guadeloupéenne ?", answers: ["Un plat de viande sauvage", "Morue salée effritée + avocat + farine de manioc (cassave) + piment — texture craquante et crémeuse unique", "Un avocat farci de légumes", "Un plat de crabes et avocats"], correct: 1, explanation: "Le féroce d'avocat est une entrée créole incontournable : morue dessalée et effilochée, avocat bien mûr écrasé, farine de manioc (ou cassave) pour la texture craquante, piment antillais, cive. Son nom vient de son caractère pimenté. Simple à faire, riche en saveurs — symbole de la cuisine créole populaire et conviviale." },
    { question: "Quelle est la différence entre le Ti-punch guadeloupéen et le cocktail préparé au bar ?", answers: ["Aucune différence", "Ti-punch traditionnel : chacun prépare le sien à table — rhum agricole, citron vert, sucre de canne (quantités selon goût)", "Le Ti-punch bar est meilleur", "Le Ti-punch guadeloupéen n'a pas de sucre"], correct: 1, explanation: "Le vrai Ti-punch (petit punch) antillais se prépare à table, chacun selon son goût : rhum agricole blanc (Guadeloupe : Bologne, Karukera, Damoiseau), jus de citron vert, sirop de canne ou sucre roux. L'expression 'chacun prépare la mort de soi-même' reflète la culture de responsabilité individuelle autour de cet apéritif emblématique." },
    { question: "Qu'est-ce que le 'blaff', plat traditionnel antillais de poisson ?", answers: ["Un poisson fumé", "Poisson entier cuit dans un court-bouillon épicé (piment, cive, thym, laurier, citron, ail) — cuisson rapide qui préserve la fraîcheur", "Un poisson frit à l'huile de palme", "Un ragoût de poisson mijoté 3 heures"], correct: 1, explanation: "Le blaff est la technique de cuisson du poisson dans un court-bouillon très épicé et parfumé. Le nom viendrait du bruit 'blaff' du poisson plongé dans l'eau bouillante. Le court-bouillon contient : piment végétarien ou fort, cive, thym, laurier, ail, citron vert, sel. Cuisson très rapide pour préserver la texture et les arômes." },
    { question: "Quelle farine traditionnelle antillaise, issue du manioc, est utilisée dans de nombreuses recettes créoles ?", answers: ["La farine de riz", "La farine de manioc (couac) et la cassave — héritages amérindiens toujours présents dans la cuisine antillaise", "La farine de maïs uniquement", "La farine de blé tropicale"], correct: 1, explanation: "Le manioc (héritage amérindien kalinago/arawak) reste fondamental dans la cuisine antillaise : la cassave (galette plate de manioc râpé), le couac (farine de manioc grillée), l'amidon de manioc (pour les gâteaux). Le manioc amer contient de l'acide cyanhydrique éliminé par la cuisson — technique maîtrisée par les Amérindiens depuis des millénaires." },
    { question: "Quel est le secret du court-bouillon de poisson antillais pour qu'il soit réussi ?", answers: ["Cuire très longtemps à feu doux", "Poisson ultra-frais + piment végétarien + cive + tomates + ail + citron vert — sauce réduite et relevée", "Utiliser du poisson surgelé uniquement", "Éviter le piment pour ne pas couvrir le goût du poisson"], correct: 1, explanation: "Le court-bouillon antillais exige un poisson frais du jour. La sauce : oignon, cive, tomates, ail, piment végétarien, thym, laurier, citron vert, huile. Le poisson est mariné puis cuit dans la sauce. L'astuce créole : dorer le poisson légèrement à la poêle avant de l'ajouter à la sauce pour une texture parfaite." },
    { question: "Qu'est-ce que le 'matété de crabes', plat royal guadeloupéen servi à Pâques ?", answers: ["Une soupe de crabes légère", "Riz cuit dans la carapace et les pattes de crabes de terre avec épices créoles — plat rituel de Pâques en Guadeloupe", "Des crabes grillés au barbecue", "Une entrée froide de crabes en mayonnaise"], correct: 1, explanation: "Le matété de crabes est LE plat emblématique de Pâques en Guadeloupe. Les crabes de terre (crabes marins selon les régions) sont préparés avec leurs carapaces broyées pour enrichir la sauce. Le riz cuit dans ce bouillon de crabe épicé (piment, cive, thym, ail) absorbe tous les arômes. Un plat intense, festif et profondément guadeloupéen." },
    { question: "Qu'est-ce que le 'punch coco' et comment le prépare-t-on traditionnellement ?", answers: ["Un cocktail alcoolisé au rhum et lait de coco uniquement", "Rhum vieux ou crème de cacao + lait de coco frais + lait concentré sucré + cannelle + muscade — fait maison", "Un jus de coco sans alcool", "Un dessert glacé à la noix de coco"], correct: 1, explanation: "Le punch coco antillais traditionnel : rhum vieux ou rhum arrangé + lait de coco frais (pas en boîte) + lait concentré sucré + cannelle + muscade râpée. Servi très frais. Chaque famille a sa recette secrète. Contrairement au cocktail commercial, le punch coco maison utilise du vrai lait de coco pressé à la main." },
    { question: "Quelle est la signification culturelle du 'ragoût de cabri' dans les fêtes antillaises ?", answers: ["Un plat ordinaire du quotidien", "Plat de fête symbolisant l'abondance et la convivialité — préparé pour les mariages, baptêmes et grandes réunions familiales", "Un plat uniquement masculin", "Une recette importée récemment de métropole"], correct: 1, explanation: "Le cabri (chèvre) est l'animal de fête aux Antilles. Son ragoût en colombo ou en sauce créole est systématiquement présent lors des grandes occasions : mariages, baptêmes, fêtes patronales, réunions de famille. Sa préparation est communautaire et prend des heures. Sa présence sur la table signifie que c'est un grand jour." },
  ],
  tips: ["Le colombo antillais est un héritage tamoul-indien arrivé aux Antilles avec les travailleurs engagés après 1848", "Le matété de crabes est LE plat de Pâques guadeloupéen — une institution culturelle autant que culinaire", "Le Ti-punch se prépare à table, chacun selon son goût — respect de l'autonomie individuelle créole"],
};
export default quizCuisineAntillaise;
