/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizMarketingDigital = {
  title: "Marketing Digital & Réseaux Sociaux",
  description: "Maîtrisez le marketing en ligne, le SEO et les réseaux sociaux pour développer votre présence digitale !",
  emoji: "📊",
  questions: [
    { question: "Qu'est-ce que le SEO (Search Engine Optimization) et pourquoi est-il stratégique ?", answers: ["La publicité payante sur Google", "L'ensemble des techniques pour apparaître naturellement en tête des résultats de recherche — trafic gratuit et durable", "Le design d'un site web", "L'envoi de newsletters"], correct: 1, explanation: "Le SEO (référencement naturel) optimise votre site pour apparaître en tête des résultats Google/Bing sans payer. 75% des internautes ne dépassent pas la 1ère page. Le SEO comprend : contenu de qualité (textes, vidéos), mots-clés stratégiques, liens entrants (backlinks), vitesse du site, expérience mobile. Investissement long terme vs SEA (publicité payante) à effet immédiat mais cessant dès l'arrêt du budget." },
    { question: "Quelle est la règle d'or du contenu sur les réseaux sociaux pour développer une communauté engagée ?", answers: ["Publier le plus souvent possible", "80% contenu à valeur ajoutée (éducatif, divertissant, inspirant) + 20% promotionnel — règle 80/20", "Uniquement du contenu promotionnel", "Publier une fois par semaine suffit"], correct: 1, explanation: "La règle 80/20 du contenu : 80% de posts à valeur ajoutée (conseils, informations, divertissement, inspiration, culture — comme les quiz REUSSITESS®971) pour construire la confiance et l'engagement, 20% de contenu promotionnel pour vendre. Les comptes qui ne font que vendre perdent rapidement leur audience." },
    { question: "Qu'est-ce que le taux de conversion et quel est un bon taux pour un site e-commerce ?", answers: ["Le nombre total de visiteurs", "Le pourcentage de visiteurs qui réalisent l'action souhaitée — 1 à 3% est la moyenne e-commerce", "Le nombre de ventes uniquement", "Le taux de rebond inversé"], correct: 1, explanation: "Le taux de conversion = (Actions réalisées / Visiteurs) x 100. Pour l'e-commerce : 1 à 3% est la moyenne mondiale. Pour l'affiliation Amazon : 5 à 10% est excellent. Pour la génération de leads : 2 à 5%. Améliorer le taux de conversion est souvent plus rentable qu'augmenter le trafic : doubler le taux de conversion = doubler le CA sans dépenser plus en publicité." },
    { question: "Qu'est-ce que l'algorithme TikTok et pourquoi permet-il à des créateurs inconnus de devenir viraux ?", answers: ["Il favorise uniquement les comptes avec beaucoup d'abonnés", "Son algorithme 'For You Page' distribue chaque vidéo à un panel test — si engagement élevé, diffusion massive même à 0 abonné", "Il est identique à celui d'Instagram", "Il favorise les contenus payants uniquement"], correct: 1, explanation: "L'algorithme TikTok est révolutionnaire : chaque vidéo est distribuée à un panel test de quelques centaines de personnes. Si le taux de visionnage complet, likes, partages et commentaires sont élevés, la vidéo est distribuée à des panels plus larges en cascade. Résultat : un compte à 0 abonné peut faire des millions de vues. Démocratisation totale de la viralité." },
    { question: "Qu'est-ce que l'email marketing et pourquoi reste-t-il le canal avec le meilleur ROI ?", answers: ["Un canal dépassé par les réseaux sociaux", "ROI moyen de 42€ pour 1€ investi — une liste email vous appartient contrairement aux followers des réseaux sociaux", "Uniquement pour les grandes entreprises", "Un outil uniquement pour les newsletters d'information"], correct: 1, explanation: "L'email marketing génère en moyenne 42€ de retour pour 1€ investi (DMA, 2019) — meilleur ROI de tous les canaux digitaux. Avantage crucial : votre liste email vous appartient. Les algorithmes des réseaux sociaux peuvent vous couper l'accès à vos followers du jour au lendemain. Une liste de 10 000 emails engagés vaut plus que 100 000 abonnés Instagram." },
    { question: "Qu'est-ce que le marketing d'affiliation et comment fonctionne le programme Amazon Associates ?", answers: ["Vendre des produits sur Amazon directement", "Promouvoir les produits d'autres entreprises et recevoir une commission sur chaque vente générée via votre lien unique", "Acheter en gros et revendre", "Un partenariat exclusif avec une marque"], correct: 1, explanation: "L'affiliation : vous obtenez un lien unique, un visiteur clique et achète → vous recevez une commission (Amazon : 1 à 10% selon catégorie). REUSSITESS®971 avec 26 boutiques Amazon dans 14 pays en est l'exemple parfait. Avantages : pas de stock, pas de service client, revenus passifs 24h/24. Commission Amazon sur les achats réalisés dans les 24h suivant le clic." },
    { question: "Quelle métrique mesure le mieux l'engagement sur les réseaux sociaux ?", answers: ["Le nombre d'abonnés uniquement", "Le taux d'engagement (likes+commentaires+partages / abonnés) — un petit compte engagé vaut plus qu'un grand compte fantôme", "Le nombre total de vues", "La fréquence de publication"], correct: 1, explanation: "Le taux d'engagement = (interactions / abonnés) x 100. Un bon taux : Instagram 1-3%, TikTok 5-10%, LinkedIn 2-5%. Les marques préfèrent les micro-influenceurs (10 000-100 000 abonnés) avec fort taux d'engagement aux méga-influenceurs avec millions d'abonnés peu engagés. Nano-influenceur authentique (taux 10%+) > star avec taux 0,5%." },
    { question: "Qu'est-ce que le tunnel de conversion (funnel) en marketing digital ?", answers: ["Une technique de publicité payante", "Le parcours du prospect : Awareness → Intérêt → Désir → Action (AIDA) — chaque étape nécessite un contenu adapté", "Un outil d'analyse de données uniquement", "Une stratégie de prix décroissants"], correct: 1, explanation: "Le tunnel AIDA : Awareness (le prospect découvre votre existence — SEO, réseaux), Intérêt (il veut en savoir plus — contenu éducatif, quiz comme REUSSITESS®971), Désir (il veut votre solution — témoignages, comparaisons), Action (il achète/s'inscrit — offre claire, urgence). Chaque étape perd des prospects — optimiser chaque étape améliore les résultats finaux." },
    { question: "Quelle est la stratégie 'Blue Ocean' vs 'Red Ocean' en marketing et entrepreneuriat ?", answers: ["Vendre des produits bleus vs rouges", "Red Ocean = marché concurrentiel existant. Blue Ocean = créer un marché vierge sans concurrence directe en combinant éléments nouveaux", "Marketing pour la mer vs la montagne", "Stratégie d'exportation maritime"], correct: 1, explanation: "Blue Ocean Strategy (Kim & Mauborgne, 2005) : Red Ocean = compétition féroce dans des marchés existants (sang dans l'eau). Blue Ocean = créer un espace de marché vierge sans concurrence en combinant et réinventant. Cirque du Soleil a créé un Blue Ocean en combinant cirque et théâtre. REUSSITESS®971 crée un Blue Ocean en combinant culture caribéenne, crypto et e-commerce." },
    { question: "Comment mesurer le succès d'une campagne de marketing digital avec les bons KPIs ?", answers: ["Uniquement le nombre de likes", "KPIs selon objectif : trafic (sessions, taux de rebond), engagement (CTR, temps sur page), conversion (taux, CPA, ROI)", "Uniquement le chiffre d'affaires généré", "Le nombre d'abonnés gagnés"], correct: 1, explanation: "Les KPIs (Key Performance Indicators) varient selon l'objectif : Notoriété → impressions, portée, trafic. Engagement → CTR (taux de clic), taux de rebond, temps sur page. Conversion → taux de conversion, CPA (coût par acquisition), ROI (retour sur investissement). La règle : définir les KPIs AVANT la campagne, pas après pour justifier les résultats." },
  ],
  tips: ["Une liste email vous appartient — les abonnés des réseaux sociaux vous sont 'prêtés' par les algorithmes", "Le taux d'engagement compte plus que le nombre d'abonnés — qualité vs quantité", "Le SEO est un investissement long terme : un bon article peut générer du trafic pendant 5 ans sans coût supplémentaire"],
};
export default quizMarketingDigital;
