/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizAnimeManga = {
  title: "Anime & Manga",
  description: "Testez vos connaissances sur la culture japonaise animée !",
  emoji: "🎌",
  questions: [
    { question: "🎌 Quelle est la différence entre un anime et un manga ?", answers: ["Ce sont des synonymes", "Le manga est la bande dessinée japonaise papier, l'anime est son adaptation en animation", "L'anime est plus populaire que le manga", "Le manga est pour adultes, l'anime pour enfants"], correct: 1, explanation: "Le manga est la BD japonaise (lue de droite à gauche) et l'anime est l'adaptation animée. Beaucoup d'animes célèbres sont des adaptations de mangas : Dragon Ball, Naruto, One Piece, Demon Slayer..." },
    { question: "⚔️ Quel anime suit des soldats combattant des titans géants qui dévorent les humains ?", answers: ["Naruto", "L'Attaque des Titans (Shingeki no Kyojin)", "Berserk", "Demon Slayer"], correct: 1, explanation: "L'Attaque des Titans (Attack on Titan / Shingeki no Kyojin) de Hajime Isayama est l'un des animes/mangas les plus populaires du XXIe siècle. Son univers dystopique et ses rebondissements en ont fait un phénomène mondial." },
    { question: "🏴‍☠️ Dans One Piece, que cherche Luffy ?", answers: ["Un grand trésor appelé One Piece pour devenir le Roi des Pirates", "La Pierre Philosophale", "Les 7 Boules de Cristal", "Le Poignard Sacré"], correct: 0, explanation: "Monkey D. Luffy, le protagoniste de One Piece (Eiichiro Oda), rêve de trouver le légendaire trésor 'One Piece' pour devenir le Roi des Pirates. One Piece est le manga le plus vendu de l'histoire avec plus de 500 millions de volumes." },
    { question: "🎬 Quel studio d'animation japonais a réalisé Spirited Away et Mon Voisin Totoro ?", answers: ["Toei Animation", "Madhouse", "Studio Ghibli", "Gainax"], correct: 2, explanation: "Le Studio Ghibli, co-fondé par Hayao Miyazaki et Isao Takahata en 1985, est le studio d'animation japonais le plus célèbre. Spirited Away (Le Voyage de Chihiro) a remporté l'Oscar du meilleur film d'animation en 2003." },
    { question: "🍜 Dans quel anime un jeune ninja rêve de devenir le chef de son village ?", answers: ["Bleach", "Dragon Ball", "Naruto", "Fairy Tail"], correct: 2, explanation: "Naruto Uzumaki, protagoniste de Naruto (Masashi Kishimoto), rêve de devenir Hokage (chef) de son village Konoha. Naruto est l'un des animes les plus populaires au monde et a marqué toute une génération." },
    { question: "🌍 Pourquoi la culture anime/manga est-elle si populaire en Afrique et dans les Caraïbes ?", answers: ["Pour des raisons commerciales uniquement", "Les thèmes universels de persévérance, d'amitié et de dépassement de soi résonnent profondément, indépendamment des origines", "C'est une mode passagère", "Uniquement parce que les dessins sont beaux"], correct: 1, explanation: "L'anime transcende les frontières culturelles car ses thèmes — surmonter les obstacles, la force de l'amitié, ne jamais abandonner (NAKAMA !) — résonnent universellement. En Afrique et aux Caraïbes, des personnages comme Luffy ou Naruto inspirent les jeunes générations." },
  ],
  tips: ["🎌 L'anime est devenu une culture mondiale qui génère des milliards de dollars", "💡 Beaucoup d'animes transmettent de vraies valeurs : persévérance, loyauté, dépassement de soi", "🌍 Dragon Ball Z a été regardé par des générations entières dans les Caraïbes et en Afrique"],
};
export default quizAnimeManga;
