const quizVinsSpiriteux = {
  title: "Vins & Spiritueux du Monde",
  description: "Découvrez l'univers fascinant des vins, rhums, whisky et spiritueux du monde entier !",
  emoji: "🍷",
  questions: [
    { question: "Quelle est la différence entre un rhum agricole et un rhum industriel (de mélasse) ?", answers: ["Aucune différence de goût", "Rhum agricole = distillé du jus de canne fraîche pressée. Rhum industriel = distillé de mélasse (résidu sucrerie) — goût et terroir très différents", "Le rhum agricole est plus fort en alcool", "Le rhum industriel est uniquement pour les cocktails"], correct: 1, explanation: "Rhum agricole (AOC Martinique, Guadeloupe) : distillé du jus de canne fraîche pressée le jour même. Garde les arômes végétaux, herbacés et le terroir de l'île. Rhum industriel (la grande majorité mondiale : Bacardi, Havana Club) : distillé de mélasse, résidu de la fabrication du sucre. Goût plus neutre et commercial." },
    { question: "Quelle île des Antilles possède la seule AOC (Appellation d'Origine Contrôlée) de rhum reconnue en France et en Europe ?", answers: ["La Guadeloupe", "Haïti", "La Martinique", "La Barbade"], correct: 2, explanation: "La Martinique détient depuis 1996 la seule AOC Rhum Agricole de Martinique, reconnue par l'Union Européenne. Cette AOC réglemente : la variété de canne, la méthode de distillation, le degré minimum, le vieillissement. Les grandes marques : Clément, Saint James, Trois Rivières, Depaz, Neisson, La Mauny." },
    { question: "Combien d'années minimum doit vieillir un whisky scotch single malt pour être commercialisé ?", answers: ["1 an", "3 ans minimum en fût de chêne en Écosse", "5 ans", "10 ans"], correct: 1, explanation: "La loi écossaise impose un minimum de 3 ans de vieillissement en fût de chêne sur le territoire écossais pour tout whisky scotch. En pratique, les whiskies de qualité vieilissent 10, 12, 18 ou 25 ans. Le fût doit avoir contenu du sherry, bourbon ou vin de Porto. La distillation en alambic en cuivre (pot still) est caractéristique." },
    { question: "Qu'est-ce que la méthode champenoise qui donne ses bulles au champagne ?", answers: ["Injection de CO2 artificiel", "Seconde fermentation en bouteille (tirage) avec ajout de sucre et levures — les bulles sont naturelles", "Agitation vigoureuse du vin avant ouverture", "Utilisation d'eau gazeuse dans la vinification"], correct: 1, explanation: "La méthode champenoise (ou traditionnelle) : une seconde fermentation est réalisée EN BOUTEILLE après ajout de sucre et levures (liqueur de tirage). Le CO2 produit reste emprisonné dans la bouteille. Remuage (rotation quotidienne), dégorgement (élimination des levures), dosage final. Seuls les vins de Champagne (France) peuvent s'appeler Champagne." },
    { question: "Le cognac et l'armagnac sont tous deux des brandies français. Quelle est leur principale différence ?", answers: ["Le cognac est plus fort en alcool", "Cognac : double distillation en alambic charentais, Charente. Armagnac : distillation continue, Gascogne — plus fruité et rustique", "L'armagnac est uniquement blanc", "Le cognac est uniquement brun"], correct: 1, explanation: "Cognac (Charente) : double distillation en alambic en cuivre (pot still charentais), vieillissement en fûts de chêne du Limousin, grades VS/VSOP/XO. Armagnac (Gascogne) : distillation continue (colonne), souvent millésimé, plus complexe et typé. L'armagnac est le plus ancien eau-de-vie français (XIVe siècle vs XVIIe pour le cognac)." },
    { question: "Qu'est-ce qu'un rhum arrangé et comment le prépare-t-on traditionnellement aux Antilles ?", answers: ["Un rhum mélangé à un autre rhum", "Rhum blanc macéré avec fruits, épices et sucre pendant des semaines ou mois — recette familiale transmise", "Un rhum avec jus de fruit frais uniquement", "Un cocktail préparé au bar"], correct: 1, explanation: "Le rhum arrangé antillais est un rhum blanc (50-55°) macéré avec des fruits locaux (ananas, corossol, maracudja, cacao), épices (vanille, cannelle, badiane, girofle) et sucre de canne. Macération minimum 3 semaines, souvent plusieurs mois. Chaque famille a sa recette secrète transmise de génération en génération. Culture vivante en Guadeloupe et Martinique." },
    { question: "Quel pays est le premier producteur mondial de vin en volume ?", answers: ["France", "Italie", "Espagne", "Ces 3 pays alternent le podium selon les années, souvent Italie en tête de volume"], correct: 3, explanation: "L'Italie, la France et l'Espagne alternent régulièrement au sommet de la production mondiale de vin. En volume : Italie souvent première (49 millions d'hectolitres/an), suivie de France et Espagne. En valeur : la France est première (exportations à 12 milliards €). Le Nouveau Monde (USA, Australie, Argentine, Chili) monte en puissance." },
    { question: "Qu'est-ce que le terroir dans la viticulture française et pourquoi est-il unique au monde ?", answers: ["La technique de vinification uniquement", "L'ensemble sol + sous-sol + climat + exposition + savoir-faire humain d'un lieu donné — donne l'unicité irréproductible d'un vin", "La qualité des cépages plantés uniquement", "Le château ou domaine viticole"], correct: 1, explanation: "Le terroir est un concept français (reconnu par l'UNESCO en 2010 pour les Climats de Bourgogne) : la combinaison unique de sol, sous-sol, microbiome, climat, exposition et savoir-faire humain. Un même cépage planté à 100m de distance peut donner des vins très différents. Le terroir est irréproductible — c'est pourquoi les grands Bourgognes sont uniques." },
    { question: "Quel spiritueux japonais connaît un essor mondial spectaculaire depuis les années 2000 ?", answers: ["Le saké uniquement", "Le whisky japonais (Nikka, Suntory) — multiprimé, en rupture de stock mondiale", "Le shochu", "Le umeshu (vin de prune)"], correct: 1, explanation: "Le whisky japonais (Nikka, Suntory Yamazaki, Hakushu) a révolutionné le marché mondial. Primé à de nombreux concours internationaux (souvent au-dessus des scotch), il est en pénurie mondiale depuis 2015. Suntory a racheté Jim Beam (bourbon) en 2014 pour 16 milliards $. Le Japon avait envoyé des apprentis en Écosse dans les années 1920 pour apprendre la distillation." },
    { question: "Qu'est-ce que la dégustation à l'aveugle et pourquoi a-t-elle révolutionné le monde du vin ?", answers: ["Boire du vin les yeux fermés", "Évaluer un vin sans connaître son identité — le Jugement de Paris (1976) a montré que des vins californiens surpassaient les grands Bordeaux et Bourgognes", "Technique réservée aux sommeliers professionnels", "Méthode pour identifier les vins défectueux uniquement"], correct: 1, explanation: "Le Jugement de Paris (1976, Steven Spurrier) : dégustation à l'aveugle où des experts français ont préféré des Chardonnays et Cabernets californiens aux meilleurs Bourgognes et Bordeaux. Scandale mondial, humiliation pour la France, révolution pour le Nouveau Monde. Prouve que les préjugés influencent massivement la dégustation." },
  ],
  tips: ["Le rhum agricole de Martinique est le seul rhum AOC européen — un patrimoine antillais protégé unique", "Le Jugement de Paris (1976) a prouvé que les préjugés influencent la dégustation — même les experts sont victimes du biais de réputation", "Le rhum arrangé antillais est une tradition familiale vivante — chaque famille garde jalousement sa recette"],
};
export default quizVinsSpiriteux;
