/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizHuilesEssentielles = {
  title: "Huiles Essentielles & Aromathérapie",
  description: "Découvrez les secrets des huiles essentielles et leurs incroyables propriétés thérapeutiques !",
  emoji: "🌸",
  questions: [
    { question: "Combien de plante faut-il pour produire 1 kg d'huile essentielle de rose ?", answers: ["1 kg de pétales", "100 kg de pétales", "3 000 à 5 000 kg de pétales de rose !", "500 kg de pétales"], correct: 2, explanation: "Il faut 3 000 à 5 000 kg de pétales de rose pour produire 1 kg d'huile essentielle de rose ! C'est pourquoi elle coûte 3 000 à 6 000€/kg. La rose de Damas (Bulgarie, Turquie, Maroc) est la plus utilisée. Une rose contient 0.02% d'huile essentielle." },
    { question: "Quelle est la règle de sécurité absolue avec les huiles essentielles ?", answers: ["Peuvent s'utiliser pures directement sur la peau", "Ne jamais utiliser pures sur la peau sans huile végétale, jamais dans les yeux, jamais per os sans avis médical", "Toutes sont sans danger pour les enfants", "Peuvent remplacer tous les médicaments"], correct: 1, explanation: "Règles de sécurité : 1. Toujours diluer dans une huile végétale (2-3% max) avant application cutanée, 2. Jamais dans les yeux, 3. Jamais ingérées sans avis médical qualifié, 4. Déconseillées chez les femmes enceintes (1er trimestre) et enfants de moins de 3 ans pour la plupart, 5. Test cutané préalable." },
    { question: "Quelle huile essentielle est reconnue comme l'une des plus polyvalentes et sûres, surnommée la couteau suisse ?", answers: ["Huile essentielle de menthe poivrée", "Huile essentielle de lavande vraie (Lavandula angustifolia)", "Huile essentielle de tea tree", "Huile essentielle d'eucalyptus"], correct: 1, explanation: "La lavande vraie (Lavandula angustifolia) est l'HE la plus polyvalente et sûre : cicatrisante (brûlures légères pure en urgence), relaxante, anti-inflammatoire, antibactérienne. L'une des rares utilisables pures ponctuellement. René-Maurice Gattefossé a fondé l'aromathérapie moderne après avoir soigné sa main brûlée avec de la lavande en 1910." },
    { question: "Quelle huile essentielle antillaise est particulièrement précieuse et produite en Guadeloupe et Martinique ?", answers: ["L'huile de coco uniquement", "L'huile essentielle de vétiver, ylang-ylang et bois de Inde (bay rum)", "L'huile de palme", "L'HE de vanille"], correct: 1, explanation: "Les Antilles produisent des HE précieuses : le vétiver (racines — ancrant, anti-stress), l'ylang-ylang (fleurs — aphrodisiaque, relaxant), le bois de Inde / bay rum (Pimenta racemosa — tonique circulatoire, cheveux). Ces HE antillaises sont utilisées par les grandes maisons de parfum mondiales." },
    { question: "Qu'est-ce que la chémotypie dans les huiles essentielles ?", answers: ["La couleur de l'huile essentielle", "Des plantes de même espèce produisant des HE aux compositions biochimiques différentes selon leur habitat", "La méthode d'extraction de l'HE", "Le pays d'origine de la plante"], correct: 1, explanation: "Le chémotype (CT) : la même espèce de plante peut produire des HE très différentes selon l'altitude, le sol et le climat. Ex: Rosmarinus officinalis CT camphre (muscles) vs CT cinéole (respiratoire) vs CT verbénone (foie). Le chémotype DOIT être indiqué sur une HE de qualité thérapeutique." },
    { question: "Quelle huile essentielle est prouvée scientifiquement efficace contre les poux résistants aux traitements classiques ?", answers: ["L'HE de lavande uniquement", "L'HE de tea tree et l'HE de lavande en combinaison", "L'HE de menthe poivrée", "L'HE d'eucalyptus"], correct: 1, explanation: "Des études ont montré l'efficacité de l'HE de tea tree (Melaleuca alternifolia) et de lavande en combinaison contre les poux, y compris résistants aux pyréthrinoïdes (insecticides classiques). Le tea tree est aussi antifongique (mycoses) et antibactérien (acné). Dilution obligatoire : 2-3% dans huile végétale." },
    { question: "Comment s'effectue la diffusion atmosphérique d'huiles essentielles et quels sont ses bénéfices ?", answers: ["Brûler l'HE directement dans une flamme", "Diffuser à froid (ultrasonique ou nébulisation) pour assainir l'air, créer une ambiance et effets thérapeutiques respiratoires", "Mettre quelques gouttes dans l'aspirateur", "Uniquement dans les spas professionnels"], correct: 1, explanation: "La diffusion à froid préserve les molécules actives des HE. Types : diffuseur ultrasonique (eau + HE, humidifie), nébuliseur (HE pure, plus puissant), diffusion passive (argile). Bénéfices prouvés : assainissement de l'air (HE de ravintsara, eucalyptus), relaxation (lavande), stimulation (citrus). Max 30 minutes, aérer ensuite." },
    { question: "Quelle est la différence entre une huile essentielle et une huile végétale ?", answers: ["Ce sont la même chose", "HE = composés aromatiques volatils extraits par distillation (très concentrée, pas grasse). HV = lipides extraits de graines/fruits (grasse, support de dilution)", "L'HE est plus chère donc meilleure", "L'HV est synthétique"], correct: 1, explanation: "HE (huile essentielle) : extraite par distillation à vapeur ou expression (agrumes), très concentrée, volatile, non grasse. HV (huile végétale) : lipides extraits par pression de graines/fruits (olive, argan, coco), grasse, stable, sert de base de dilution pour les HE. Les deux sont complémentaires en aromathérapie." },
    { question: "Quelle huile essentielle est contre-indiquée absolument chez les enfants de moins de 12 ans car elle peut provoquer des convulsions ?", answers: ["La lavande vraie", "L'HE de menthe poivrée (menthol — risque de spasme laryngé et convulsions)", "L'HE de camomille romaine", "L'HE de mandarine"], correct: 1, explanation: "L'HE de menthe poivrée est CONTRE-INDIQUÉE chez les enfants de moins de 12 ans, les femmes enceintes et allaitantes : le menthol peut provoquer spasme laryngé, ralentissement cardiaque et convulsions. Ne jamais l'appliquer près du visage des enfants. Pour les enfants : menthe douce (Mentha spicata) à la place." },
    { question: "Qu'est-ce que la synergie en aromathérapie ?", answers: ["Utiliser une seule HE à dose élevée", "La combinaison de plusieurs HE dont l'effet combiné est supérieur à la somme des effets individuels", "Mélanger HE avec médicaments", "Diffuser plusieurs HE en même temps dans différentes pièces"], correct: 1, explanation: "La synergie en aromathérapie : certaines combinaisons d'HE ont un effet supérieur à leurs effets individuels additionnés. Ex: la combinaison tea tree + lavande + eucalyptus est plus efficace contre les infections respiratoires que chacune seule. Les formules synergiques sont au cœur de l'aromathérapie professionnelle." },
  ],
  tips: ["Les HE antillaises (vétiver, ylang-ylang, bois de Inde) sont utilisées par les grandes maisons de parfum mondiales", "Jamais d'HE pure sur la peau — toujours diluer dans une huile végétale (coco, amande douce)", "La lavande vraie est la seule HE utilisable pure ponctuellement en urgence (brûlures, piqûres)"],
};
export default quizHuilesEssentielles;
