const quizDroitTravail = {
  title: "Droit du Travail — Ce que Tout Salarié Doit Savoir",
  description: "Connaissez vos droits en tant que salarié et ne laissez personne les violer !",
  emoji: "⚖️",
  questions: [
    { question: "Quel est le SMIC horaire brut en France en 2024 et à partir de quelle ancienneté a-t-on droit à une prime d'ancienneté ?", answers: ["11€ brut, aucune prime légale", "11,65€ brut, prime d'ancienneté selon conventions collectives (pas légale universelle)", "10€ brut, prime après 1 an", "12€ brut, prime après 6 mois"], correct: 1, explanation: "Le SMIC était de 11,65€ brut/heure au 1er janvier 2024 (soit 1 766,92€ brut/mois pour 35h). La prime d'ancienneté n'est pas une obligation légale universelle — elle dépend de votre convention collective. Vérifiez votre CCN (Convention Collective Nationale) sur le site Légifrance." },
    { question: "Combien de semaines de congés payés un salarié à temps plein a-t-il droit par an en France ?", answers: ["4 semaines (20 jours ouvrables)", "5 semaines (25 jours ouvrables ou 30 jours ouvrés)", "3 semaines", "6 semaines après 5 ans d'ancienneté"], correct: 1, explanation: "En France, tout salarié acquiert 2,5 jours ouvrables de congés par mois travaillé = 30 jours ouvrables (5 semaines) par an. Les congés se prennent entre le 1er mai et 31 octobre pour la période principale (4 semaines minimum). Le fractionnement peut donner droit à des jours supplémentaires. Les DOM ont les mêmes droits." },
    { question: "Qu'est-ce que le harcèlement moral au travail selon le Code du Travail français ?", answers: ["Uniquement les insultes directes", "Agissements répétés ayant pour effet une dégradation des conditions de travail portant atteinte aux droits et à la dignité — article L1152-1", "Seulement si commis par un supérieur hiérarchique", "Uniquement en cas de témoin"], correct: 1, explanation: "Le harcèlement moral (art. L1152-1 CT) : agissements RÉPÉTÉS ayant pour effet ou objet une dégradation des conditions de travail susceptible de porter atteinte aux droits, dignité, santé physique/mentale ou avenir professionnel. Peut être commis par l'employeur, un collègue ou même un subordonné. Peines : 2 ans prison + 30 000€ amende." },
    { question: "Qu'est-ce que le droit de retrait et dans quelles situations peut-on l'exercer ?", answers: ["Droit de refuser de travailler pour n'importe quelle raison", "Droit de se retirer d'une situation de travail présentant un danger grave et imminent pour sa vie ou sa santé", "Droit de partir avant la fin des heures", "Droit de refuser une mission déplaisante"], correct: 1, explanation: "Le droit de retrait (art. L4131-1 CT) : tout salarié peut se retirer d'une situation de travail dont il a un motif raisonnable de penser qu'elle présente un danger grave et imminent pour sa vie ou sa santé. L'employeur ne peut pas sanctionner ni retenir le salaire si le danger est réel. À exercer avec discernement et signaler immédiatement au supérieur." },
    { question: "Quelle est la durée maximale légale du travail en France par semaine et par jour ?", answers: ["35h/semaine, 8h/jour", "48h/semaine maximum (10h/jour maximum), la durée normale étant 35h", "40h/semaine, 10h/jour", "50h/semaine pour les cadres"], correct: 1, explanation: "Durées maximales légales : 48h/semaine (ou 44h en moyenne sur 12 semaines consécutives), 10h/jour maximum. La durée légale de travail est 35h (seuil des heures supplémentaires). Au-delà des 35h : majorations de salaire (25% pour les 8 premières heures sup, 50% au-delà) ou repos compensateur selon accord." },
    { question: "Qu'est-ce que la rupture conventionnelle et quels sont ses avantages pour le salarié ?", answers: ["Un licenciement déguisé", "Rupture amiable du contrat CDI — ouvre droit aux allocations chômage + indemnité spécifique négociée", "Uniquement pour les CDD", "Sans indemnité ni chômage"], correct: 1, explanation: "La rupture conventionnelle (RC, loi 2008) est une rupture amiable du CDI à l'initiative commune. Avantages salarié : indemnité au moins égale à l'indemnité légale de licenciement + ouverture des droits au chômage (ARE). L'employeur ne peut pas imposer une RC. Délai de rétractation de 15 jours calendaires. Homologuée par la DREETS." },
    { question: "Qu'est-ce que le CPF (Compte Personnel de Formation) et comment l'utiliser ?", answers: ["Une caisse de retraite complémentaire", "Compte alimenté en euros tout au long de la vie active (500€/an, max 5000€) pour financer des formations de son choix", "Une aide au logement pour les salariés", "Un compte épargne salarial"], correct: 1, explanation: "Le CPF (depuis 2015) : tout actif acquiert 500€/an (800€ pour non-qualifiés, plafond 5000€/8000€). Utilisable sur moncompteformation.gouv.fr pour des milliers de formations certifiantes sans accord de l'employeur. Les droits restent même en cas de changement d'emploi ou chômage. Ne pas confondre avec le plan de formation de l'entreprise." },
    { question: "Un employeur peut-il lire les emails personnels d'un salarié sur l'ordinateur professionnel ?", answers: ["Oui totalement, c'est son matériel", "Non — les emails marqués 'personnel' ou 'privé' sont protégés même sur ordinateur professionnel (jurisprudence Nikon 2001)", "Oui uniquement en son absence", "Seulement avec autorisation du juge"], correct: 1, explanation: "L'arrêt Nikon (Cass. soc. 2001) : le salarié a droit au respect de sa vie privée et au secret de ses correspondances, même sur le lieu de travail et avec les outils professionnels. Les emails marqués 'personnel' ou 'privé' ne peuvent être ouverts par l'employeur sans la présence du salarié. Violation = atteinte à la vie privée." },
    { question: "Qu'est-ce que l'égalité de rémunération homme-femme et comment la faire respecter ?", answers: ["Un principe moral sans sanction légale", "Obligation légale (art. L3221-2 CT) — à travail égal salaire égal — l'employeur qui viole ce principe risque des sanctions et un redressement", "Applicable seulement dans les grandes entreprises (500+ salariés)", "Uniquement pour les postes de cadre"], correct: 1, explanation: "À travail égal, salaire égal est une obligation légale depuis 1972 (art. L3221-2 CT). Les entreprises de 50+ salariés doivent publier leur Index d'Égalité Professionnelle (score /100). En dessous de 75/100, elles ont 3 ans pour progresser sinon pénalité financière (1% de la masse salariale). Recours possible : inspection du travail, prud'hommes." },
    { question: "Quels sont les droits d'un salarié en arrêt maladie en France ?", answers: ["Aucun salaire pendant l'arrêt", "Indemnités journalières Sécu (après 3 jours de carence) + maintien de salaire selon convention collective — protection contre licenciement pendant l'arrêt", "Licenciement possible immédiatement", "Uniquement pour les maladies graves"], correct: 1, explanation: "En arrêt maladie : Sécurité Sociale verse des Indemnités Journalières (IJ) à partir du 4ème jour (3 jours de carence, 1 seul pour accident du travail). La CCN peut prévoir le maintien de salaire complétant les IJ. L'employeur ne peut pas licencier pour maladie ordinaire (sauf perturbation grave et nécessité de remplacement définitif prouvée). Protection renforcée pour accident du travail." },
  ],
  tips: ["Le CPF vous donne 500€/an pour vous former — consultez moncompteformation.gouv.fr pour voir votre solde", "La rupture conventionnelle ouvre le droit au chômage — très avantageux vs démission", "À travail égal salaire égal est une obligation légale — comparez avec vos collègues de même poste"],
};
export default quizDroitTravail;
