/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizMarketingDigital = {
  title: "Marketing Digital",
  description: "Maîtrisez les outils pour développer votre présence en ligne !",
  emoji: "📱",
  questions: [
    { question: "📱 Qu'est-ce que le SEO ?", answers: ["Un réseau social professionnel", "L'optimisation pour les moteurs de recherche — apparaître en haut des résultats Google", "Un outil de publicité payante", "Un logiciel de design"], correct: 1, explanation: "Le SEO (Search Engine Optimization) regroupe toutes les techniques pour améliorer le positionnement d'un site dans les résultats naturels (non-payants) de Google. C'est un investissement long terme très rentable." },
    { question: "🎯 Quelle est la différence entre SEO et SEA ?", answers: ["Ce sont des synonymes", "SEO = résultats naturels gratuits, SEA = publicités payantes sur Google", "SEO est plus cher que SEA", "SEA est plus durable que SEO"], correct: 1, explanation: "SEO (Search Engine Optimization) = positionnement naturel non-payant. SEA (Search Engine Advertising) = annonces payantes (Google Ads). Le SEO prend du temps mais est durable. Le SEA est immédiat mais s'arrête dès qu'on ne paie plus." },
    { question: "📊 Qu'est-ce qu'un taux de conversion ?", answers: ["Le taux de change d'une devise", "Le pourcentage de visiteurs qui effectuent l'action souhaitée (achat, inscription...)", "Le nombre de clics sur une publicité", "La vitesse de chargement d'un site"], correct: 1, explanation: "Le taux de conversion mesure l'efficacité d'une page ou d'une campagne. Si 100 personnes visitent votre page et 5 achètent, votre taux de conversion est de 5%. L'optimiser est souvent plus rentable qu'attirer plus de visiteurs." },
    { question: "📧 Pourquoi l'email marketing reste-t-il efficace en 2025 ?", answers: ["Il est devenu obsolète", "Il offre un ROI parmi les plus élevés — chaque euro investi peut en rapporter 40 — et vous possédez votre liste", "Parce que les réseaux sociaux ne fonctionnent plus", "Il est gratuit"], correct: 1, explanation: "L'email marketing offre un ROI exceptionnel car vous parlez directement à des personnes qui ont choisi de vous suivre. Contrairement aux réseaux sociaux, vous possédez votre liste — aucun algorithme ne peut vous couper de votre audience." },
    { question: "🎬 Qu'est-ce que le marketing de contenu (content marketing) ?", answers: ["Créer des publicités visuelles", "Créer et partager du contenu utile pour attirer et fidéliser une audience cible", "Acheter du contenu sponsorisé", "Copier le contenu des concurrents"], correct: 1, explanation: "Le content marketing consiste à créer du contenu utile (articles, vidéos, podcasts, quiz...) qui attire naturellement votre audience cible. C'est exactement ce que fait Reussitess®971 avec ses quiz éducatifs !" },
    { question: "🔥 Qu'est-ce qu'un funnel marketing (entonnoir de vente) ?", answers: ["Un outil de filtrage des emails", "Le parcours du client de la découverte jusqu'à l'achat : Attention → Intérêt → Désir → Action", "Un type de publicité", "Une méthode de pricing"], correct: 1, explanation: "Le funnel (entonnoir) représente le chemin que suit un prospect : il découvre votre marque, s'y intéresse, désire votre produit, puis passe à l'action (achat). Optimiser chaque étape maximise les conversions." },
  ],
  tips: ["🎯 Commencez par maîtriser un seul canal avant d'en multiplier", "📊 Sans données, c'est juste une opinion — installez Google Analytics dès le début", "💡 Le meilleur marketing raconte une histoire vraie — comme vos résultats GoMining réels"],
};
export default quizMarketingDigital;
