/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizPlantesAntilles = {
  title: "Plantes des Antilles & Remèdes Créoles",
  description: "Redécouvrez la pharmacopée végétale extraordinaire de la Guadeloupe et de la Martinique !",
  emoji: "🌺",
  questions: [
    { question: "Pour quel usage traditionnel la feuille de corossol est-elle la plus utilisée aux Antilles ?", answers: ["Uniquement pour le jus de fruit", "Tisane pour l'hypertension, le diabète, la fièvre et comme sédatif naturel — et études anti-cancer", "Uniquement en cuisine", "Pour repousser les insectes"], correct: 1, explanation: "Le corossol (Annona muricata) est l'une des plantes les plus utilisées en médecine créole. Ses feuilles en tisane : hypotenseur, hypoglycémiant, sédatif. Des études sur l'annonacine (graviola) montrent des effets anti-tumoraux in vitro, rendant cette plante très étudiée. Attention : à forte dose, la graviola peut être neurotoxique." },
    { question: "Qu'est-ce que la 'bois bandé' (Richeria grandis), plante emblématique des Antilles ?", answers: ["Un bois de construction uniquement", "Plante aphrodisiaque traditionnelle antillaise dont l'écorce est utilisée en infusion ou rhum arrangé", "Une plante contre le paludisme", "Un arbre fruitier"], correct: 1, explanation: "La bois bandé (Richeria grandis) est l'aphrodisiaque végétal traditionnel des Antilles. Son écorce est macérée dans du rhum ou en infusion. Contient des flavonoïdes et tanins. Très utilisée par les hommes pour les troubles de la libido. Son commerce est règlementé en Guadeloupe et Martinique pour protéger l'espèce menacée." },
    { question: "Quelle plante antillaise aux fleurs jaunes est utilisée contre les troubles digestifs et la fièvre, appelée herbe à tout mal ?", answers: ["La verveine citronnelle", "L'herbe à tout mal (Pluchea carolinensis) — feuilles en bain et tisane contre les grippes et douleurs", "Le basilic tropical", "La menthe antillaise"], correct: 1, explanation: "L'herbe à tout mal (Pluchea carolinensis) est une plante buissonnante à fleurs roses/mauves très utilisée en médecine créole guadeloupéenne. Ses feuilles bouillies servent en tisane (grippe, fièvre, douleurs articulaires) et en bain (rhumatismes, douleurs musculaires). Son nom créole dit tout : elle soigne beaucoup d'affections." },
    { question: "Quelle est l'utilisation traditionnelle de la feuille de goyavier aux Antilles ?", answers: ["Uniquement pour les fruits", "Antidiarrhéique puissant — les tanins des feuilles resserrent la muqueuse intestinale", "Contre les migraines uniquement", "Pour la teinture des cheveux"], correct: 1, explanation: "Les feuilles de goyavier (Psidium guajava) sont l'antidiarrhéique traditionnel numéro 1 aux Antilles. Les tanins et flavonoïdes resserrent la muqueuse intestinale. Des études cliniques ont confirmé l'efficacité comparable à certains médicaments antidiarrhéiques. Également utilisées contre les ulcères buccaux (gargarisme)." },
    { question: "Pourquoi le bain de feuilles est-il une pratique centrale de la médecine créole antillaise ?", answers: ["Uniquement pour l'hygiène", "Purification physique et spirituelle, absorption cutanée des principes actifs, dimension rituelle et sociale de guérison", "Tradition importée d'Europe", "Pratique uniquement pour les enfants"], correct: 1, explanation: "Le bain de feuilles aux Antilles transcende la simple hygiène : il combine l'absorption cutanée des principes actifs (certains passent la barrière cutanée), la purification spirituelle et le rituel de soin communautaire. La peau absorbe les molécules actives de plantes comme la verveine, l'herbe à tout mal, le vétiver. Dimension holistique corps-esprit." },
    { question: "Quelle épice antillaise, présente dans le colombo, a des propriétés anti-inflammatoires majeures ?", answers: ["Le curcuma uniquement", "Le mélange colombo : curcuma + cumin + coriandre + fenugrec + moutarde — synergie anti-inflammatoire", "Le piment uniquement", "La noix de muscade uniquement"], correct: 1, explanation: "Le colombo antillais (héritage indien-tamoul) est un mélange d'épices à haute valeur médicinale : curcuma (anti-inflammatoire), cumin (digestif), coriandre (antioxydant), fenugrec (hypoglycémiant), moutarde. Cette synergie d'épices est une médecine préventive quotidienne intégrée dans la cuisine. Preuve de la richesse de la culture tamoul-antillaise." },
    { question: "Quelle plante marine des Antilles, le sénevé de mer ou raisin de mer, est utilisée en médecine créole ?", answers: ["Uniquement décorative sur les plages", "Coccoloba uvifera — feuilles contre les diarrhées, fruits riches en antioxydants, racines contre les rhumatismes", "Plante invasive sans usage", "Uniquement alimentaire"], correct: 1, explanation: "Le raisin de mer (Coccoloba uvifera) est présent sur toutes les plages antillaises. En médecine créole : feuilles en décoction contre la diarrhée et les inflammations, racines contre les rhumatismes, fruits (résine riche) antioxydants. C'est une plante-pharmacie naturelle accessible sur toutes les côtes de la Caraïbe." },
    { question: "Qu'est-ce que le 'siwo myèl doubout' (sirop de miel debout) traditionnel guadeloupéen ?", answers: ["Un cocktail alcoolisé", "Préparation médicinale créole de miel, citron, gingembre et rhum contre les refroidissements et toux", "Un dessert sucré uniquement", "Un engrais naturel pour les plantes"], correct: 1, explanation: "Le siwo myèl doubout est une préparation médicinale créole combinant : miel local (antibactérien), citron (vitamine C, antiseptique), gingembre (anti-inflammatoire, antiémétique) et parfois rhum (antiseptique). Utilisé contre la toux, les refroidissements et les maux de gorge. Un remède de grand-mère guadeloupéen encore très utilisé." },
    { question: "La citronnelle (bois citron) antillaise est-elle efficace contre les moustiques et notamment le moustique tigre ?", answers: ["Non, c'est un mythe", "Oui — l'huile essentielle de citronnelle repousse les moustiques, Aedes aegypti (dengue, zika) inclus", "Seulement dans les pays d'Asie", "Uniquement en diffusion intérieure"], correct: 1, explanation: "La citronnelle (Cymbopogon citratus) contient du citral et du géraniol reconnus comme répulsifs naturels contre les moustiques dont Aedes aegypti (vecteur dengue, chikungunya, zika). L'OMS la reconnaît comme répulsif naturel. Efficacité moindre que le DEET chimique mais sans effets toxiques. Planter autour de la maison est une pratique traditionnelle." },
    { question: "Qu'est-ce que la tradithérapie et comment est-elle organisée en Guadeloupe et Martinique ?", answers: ["Un terme sans signification officielle", "La reconnaissance officielle progressive des tradipraticiens et de leurs savoirs en médecine complémentaire dans les DOM", "Un département de l'hôpital de Pointe-à-Pitre uniquement", "Une pratique uniquement africaine continentale"], correct: 1, explanation: "La tradithérapie (médecine traditionnelle) est progressivement reconnue dans les DOM. Des initiatives existent pour recenser et valoriser les savoirs des tradipraticiens guadeloupéens et martiniquais. Le TRAMIL (réseau caribéen de recherche sur les plantes médicinales) a validé scientifiquement des dizaines de plantes utilisées traditionnellement aux Antilles." },
  ],
  tips: ["Le réseau TRAMIL a validé scientifiquement des dizaines de plantes médicinales antillaises utilisées depuis des siècles", "La bois bandé est protégée — son commerce est règlementé en Guadeloupe et Martinique", "Planter citronnelle et basilic autour de chez soi repousse naturellement les moustiques vecteurs de la dengue"],
};
export default quizPlantesAntilles;
