/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizUKEssentiel = {
  title: "Royaume-Uni — Essentiel Voyage & Culture",
  description: "Droits, règles, culture et bons à savoir avant d'aller au Royaume-Uni !",
  emoji: "🇬🇧",
  questions: [
    { question: "🛂 Depuis le Brexit, faut-il un visa pour visiter le Royaume-Uni depuis la France ?", answers: ["Non, passeport suffit 6 mois", "Oui, visa obligatoire", "Carte d'identité suffit", "ESTA comme aux USA"], correct: 0, explanation: "Depuis le Brexit (2021), les Français n'ont plus besoin de visa mais le passeport est OBLIGATOIRE (carte d'identité non acceptée). Séjour sans visa limité à 6 mois. Un nouveau système ETA (Electronic Travel Authorisation) entre en vigueur en 2024." },
    { question: "🚗 De quel côté roule-t-on au Royaume-Uni ?", answers: ["À droite comme en France", "À gauche", "Au centre", "Selon les routes"], correct: 1, explanation: "Le Royaume-Uni roule à gauche ! Les volants sont à droite. Si vous louez une voiture, l'adaptation prend quelques heures. Les ronds-points tournent dans le sens inverse. C'est le même système en Australie, Inde, Japon..." },
    { question: "💷 Quelle monnaie utilise le Royaume-Uni ?", answers: ["L'Euro", "La Livre Sterling (GBP)", "Le Dollar américain", "La Livre irlandaise"], correct: 1, explanation: "Le Royaume-Uni n'a jamais adopté l'Euro et utilise la Livre Sterling (£, GBP). 1 GBP vaut environ 1,17€. Prévoyez d'échanger des euros ou de retirer des livres à l'arrivée. Les euros ne sont pas acceptés." },
    { question: "☔ Quel accessoire est indispensable en toute saison au Royaume-Uni ?", answers: ["Crème solaire", "Parapluie", "Lunettes de soleil", "Gants de ski"], correct: 1, explanation: "Le Royaume-Uni reçoit de la pluie toute l'année. Londres a en moyenne 109 jours de pluie par an. Le parapluie est un accessoire culturel autant que pratique. La météo peut changer 3 fois dans la même journée !" },
    { question: "🍺 À quel âge peut-on boire de l'alcool dans un pub britannique ?", answers: ["16 ans", "21 ans", "18 ans", "19 ans"], correct: 2, explanation: "L'âge légal pour consommer de l'alcool dans un pub est 18 ans. Les pubs ferment généralement à 23h (midnight license dans certains). La culture du pub est centrale dans la vie sociale britannique." },
    { question: "🔌 Quel type de prise électrique utilise le Royaume-Uni ?", answers: ["Type C comme en France", "Type G à 3 broches rectangulaires", "Type A américain", "Type B"], correct: 1, explanation: "Le Royaume-Uni utilise les prises de type G, à 3 broches rectangulaires, uniques au monde. Un adaptateur est OBLIGATOIRE. La tension est 230V/50Hz comme en Europe, donc pas de transformateur nécessaire pour les appareils modernes." },
    { question: "🏥 Le NHS (National Health Service) est-il gratuit pour les touristes français ?", answers: ["Oui totalement gratuit", "Gratuit seulement aux urgences vitales", "Non, payant pour tous les touristes depuis le Brexit", "Gratuit pour les Européens"], correct: 2, explanation: "Depuis le Brexit (2021), les Français n'ont plus accès gratuit au NHS. Une assurance voyage est indispensable. Les urgences vitales sont traitées mais facturées. Une consultation peut coûter 200-500£." },
    { question: "🤐 Quelle règle sociale britannique est la plus importante à respecter ?", answers: ["Toujours serrer la main", "Respecter les files d'attente (queue)", "Ne jamais parler à des inconnus", "Saluer avec une bise"], correct: 1, explanation: "Respecter la file d'attente (queue) est une règle sacrée au Royaume-Uni. Doubler quelqu'un dans une file est considéré comme une grave impolitesse qui peut provoquer des incidents. Les Britanniques font la queue avec une discipline extraordinaire." },
    { question: "🎓 Combien coûtent les frais de scolarité universitaires par an au Royaume-Uni ?", answers: ["Gratuit", "3 000£/an", "9 250£/an", "25 000£/an"], correct: 2, explanation: "Les frais universitaires au Royaume-Uni sont de 9 250£/an pour les étudiants nationaux (encore plus pour les étrangers : 20 000-50 000£/an). C'est un débat politique majeur depuis leur introduction en 1998." },
    { question: "🏰 Quel monument britannique est un site préhistorique mystérieux datant de 3000 avant J.-C. ?", answers: ["Big Ben", "Stonehenge", "Tower of London", "Buckingham Palace"], correct: 1, explanation: "Stonehenge (Wiltshire) est un cercle de mégalithes datant de 3000-2000 avant J.-C. Son usage reste mystérieux : observatoire astronomique, lieu de culte, cimetière ? Site UNESCO visité par 1,5 million de personnes par an." },
  ],
  tips: ["Passeport obligatoire depuis le Brexit — la carte d'identité n'est plus acceptée", "Adaptateur prise type G indispensable — les prises françaises ne fonctionnent pas", "Respectez toujours les files d'attente — règle sociale absolue"],
};
export default quizUKEssentiel;
