const quizItalieEssentiel = {
  title: "Italie — Essentiel Voyage & Culture",
  description: "Droits, règles, culture et bons à savoir avant d'aller en Italie !",
  emoji: "🇮🇹",
  questions: [
    { question: "🛂 Faut-il un visa pour aller en Italie depuis la France ?", answers: ["Oui, visa Schengen", "Non, espace Schengen libre", "ESTA obligatoire", "Visa touristique 30 jours"], correct: 1, explanation: "L'Italie est dans l'espace Schengen. Les citoyens français circulent librement avec carte d'identité. Depuis la Guadeloupe (DOM français), même règle : carte d'identité ou passeport suffit." },
    { question: "⛪ Quelle tenue est obligatoire pour entrer dans les églises et sites religieux en Italie ?", answers: ["Costume obligatoire", "Épaules et genoux couverts", "Chaussures fermées uniquement", "Aucune règle"], correct: 1, explanation: "En Italie, épaules et genoux doivent être couverts pour entrer dans les églises, basiliques et chapelles. Au Vatican, les règles sont encore plus strictes. Des amendes peuvent s'appliquer à Rome pour tenue inadaptée." },
    { question: "🚫 Dans quelle ville italienne est-il interdit de manger sur les marches des monuments historiques ?", answers: ["Milan", "Venise", "Rome", "Florence"], correct: 2, explanation: "Rome a interdit de manger et boire sur les marches de la Fontaine de Trevi et d'autres monuments. Amendes jusqu'à 250€. Venise a aussi des règles très strictes contre les pique-niques dans les rues." },
    { question: "🍕 Quelle est la règle d'or pour commander un cappuccino en Italie ?", answers: ["Le commander à n'importe quelle heure", "Uniquement le matin, jamais après 11h", "Toujours avec sucre", "Seulement le dimanche"], correct: 1, explanation: "Les Italiens considèrent que le cappuccino se boit uniquement le matin (avant 11h). Commander un cappuccino après un repas ou le soir est vu comme une erreur touristique. Le café de l'après-midi c'est l'espresso !" },
    { question: "💶 L'Italie utilise-t-elle une monnaie différente de la France ?", answers: ["Oui, la Lire", "Non, l'Euro comme la France", "Oui, la Lire digitale", "Non mais taux différent"], correct: 1, explanation: "L'Italie utilise l'Euro depuis 2002, comme la France. Pas de change nécessaire. Cependant, dans certaines régions rurales, le cash est encore très utilisé. Prévoyez des espèces pour les petits commerçants." },
    { question: "🚗 Que doit-on obligatoirement avoir dans sa voiture en Italie ?", answers: ["Extincteur seul", "Triangle + gilet jaune + extincteur", "GPS obligatoire", "Certificat médical"], correct: 1, explanation: "En Italie, le triangle de signalisation et le gilet de sécurité jaune sont obligatoires dans tout véhicule. En cas d'accident ou de panne, le port du gilet est obligatoire avant de descendre de la voiture." },
    { question: "🏺 Quelle est la peine pour avoir emporté du sable ou des galets des plages de Sardaigne ?", answers: ["Avertissement oral", "Amende jusqu'à 3 000€", "Expulsion du pays", "Confiscation du passeport"], correct: 1, explanation: "En Sardaigne, emporter du sable, des galets ou des coquillages est illégal avec des amendes de 500€ à 3 000€. Des douaniers contrôlent les bagages. Ce sable blanc unique disparaîtrait si tous les touristes en prenaient." },
    { question: "🍝 Combien de régions l'Italie compte-t-elle, chacune avec sa propre gastronomie ?", answers: ["10 régions", "15 régions", "20 régions", "25 régions"], correct: 2, explanation: "L'Italie est divisée en 20 régions, chacune avec ses propres spécialités culinaires. La pizza à Naples, la pasta à Bologne, le risotto à Milan, la focaccia à Gênes. La cuisine italienne varie radicalement d'une région à l'autre." },
    { question: "🌋 Quelle ville italienne vit sous la menace d'un super-volcan pouvant affecter 3 millions de personnes ?", answers: ["Rome", "Catane", "Naples / Vésuve et Campi Flegrei", "Palerme"], correct: 2, explanation: "Naples est menacée par le Vésuve (qui a détruit Pompéi en 79 après J.-C.) ET par les Campi Flegrei, super-volcan en activité croissante. Des plans d'évacuation de 3 millions de personnes existent. Le risque sismique est réel." },
    { question: "🎥 L'Italie est le pays natal de quelle invention culturelle majeure du XXe siècle ?", answers: ["Le cinéma parlant", "La télévision couleur", "Le cinéma (Cinecittà / Néo-réalisme)", "La radio FM"], correct: 2, explanation: "Cinecittà, les studios de cinéma romains fondés en 1937, ont produit des centaines de chefs-d'œuvre. Le néo-réalisme italien (Fellini, Visconti, De Sica) a révolutionné le cinéma mondial. Rome était surnommée Hollywood sul Tevere." },
  ],
  tips: ["Épaules et genoux couverts obligatoires dans les églises — portez un foulard", "Cappuccino uniquement le matin pour ne pas choquer les locaux", "Emporter du sable de Sardaigne est une infraction avec amendes lourdes"],
};
export default quizItalieEssentiel;
