/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizAmazon = {
  title: "Amazon & E-commerce — Secrets des Vendeurs",
  description: "Maîtrisez Amazon Associates, le FBA et les secrets du commerce en ligne mondial !",
  emoji: "📦",
  questions: [
    { question: "Qu'est-ce que le programme Amazon Associates et comment fonctionne la commission ?", answers: ["Un programme pour vendre ses propres produits sur Amazon", "Programme d'affiliation : promouvoir des produits Amazon avec un lien unique et recevoir 1 à 10% de commission sur les achats des 24h suivant le clic", "Un abonnement Prime pour vendeurs", "Un programme de cashback pour les acheteurs"], correct: 1, explanation: "Amazon Associates est le plus grand programme d'affiliation mondial. Principe : créez des liens trackés vers des produits Amazon, quelqu'un clique et achète n'importe quel produit dans les 24h → vous recevez une commission. Taux : 1% (electronique) à 10% (beauté, mode, maison). REUSSITESS®971 exploite 26 boutiques sur 14 Amazon marketplace avec l'ID fb942837." },
    { question: "Quels sont les pays où Amazon a des marketplace indépendantes accessibles via le programme Associates ?", answers: ["Uniquement USA, UK et France", "USA, Canada, UK, Allemagne, France, Italie, Espagne, Japon, Australie, Inde, Brésil, Mexique, UAE, Singapore et plus", "Uniquement les pays anglophones", "Seulement 5 pays européens"], correct: 1, explanation: "Amazon opère des marketplace indépendantes dans 20+ pays : USA (amazon.com), UK (.co.uk), DE (.de), FR (.fr), IT (.it), ES (.es), CA (.ca), JP (.co.jp), AU (.com.au), IN (.in), BR (.com.br), MX (.com.mx), UAE (.ae), SG (.sg), NL (.nl), SE (.se), PL (.pl), TR (.com.tr), SA (.sa.com), BE (.com.be). REUSSITESS®971 couvre 14 de ces marchés." },
    { question: "Qu'est-ce que le SEO Amazon (A9/A10 algorithm) et comment optimiser ses listings ?", answers: ["Le même SEO que Google", "Algorithme Amazon qui classe les produits par pertinence et taux de conversion — titres, bullets, description, images, avis et prix influencent le classement", "Uniquement les publicités payantes", "Le nombre d'étoiles uniquement"], correct: 1, explanation: "L'algorithme A10 d'Amazon priorise : taux de conversion (clics qui aboutissent à un achat), relevance des mots-clés (titre, bullets, description backend), vélocité des ventes (nombre de ventes récentes), avis clients (quantité et qualité), prix compétitif, qualité des images. Contrairement à Google, Amazon optimise pour la vente, pas la visite." },
    { question: "Qu'est-ce que le programme Amazon FBA (Fulfillment by Amazon) et ses avantages ?", answers: ["Fabriquer ses produits avec Amazon", "Stocker ses produits dans les entrepôts Amazon — Amazon gère l'expédition, service client et retours en échange de frais de stockage et d'expédition", "Vendre uniquement en dropshipping", "Un programme pour les grandes entreprises uniquement"], correct: 1, explanation: "Amazon FBA : vous envoyez vos produits aux entrepôts Amazon, Amazon stocke, expédie et gère le service client. Avantages : badge Prime (80% des acheteurs filtrent Prime), expédition rapide (J+1, J+2), service client 24/7 géré par Amazon. Inconvénients : frais de stockage et d'expédition, moins de contrôle sur l'expérience client. Alternative : FBM (vendeur gère lui-même)." },
    { question: "Qu'est-ce que le Private Label sur Amazon et pourquoi est-ce la stratégie la plus rentable ?", answers: ["Vendre des produits de luxe uniquement", "Créer sa propre marque sur des produits existants fabriqués en Chine — marges de 50-70% vs 10-20% en retail classique", "Revendre des produits de marques existantes", "Vendre des produits numériques"], correct: 1, explanation: "Le Private Label : sourcing d'un produit générique (souvent via Alibaba), y apposer sa propre marque, le vendre sur Amazon. Marges élevées (50-70%) car on contrôle le prix de vente et le coût de production. Outils : Jungle Scout ou Helium 10 pour trouver des niches rentables, Alibaba pour les fournisseurs. Base du modèle de nombreux millionnaires Amazon." },
    { question: "Comment fonctionne le système d'avis clients sur Amazon et pourquoi sont-ils cruciaux ?", answers: ["Ils n'influencent pas les ventes", "Les avis influencent directement l'algorithme et la confiance — un produit avec 4,5 étoiles+ et 50+ avis convertit 3x plus qu'un sans avis", "Seuls les avis négatifs importent", "Les avis payants sont tolérés par Amazon"], correct: 1, explanation: "Les avis Amazon sont le facteur de conversion numéro 1. Un produit sans avis = invisible. Amazon interdit les faux avis (suspension du compte). Stratégies légales : programme Amazon Vine (envoi aux top reviewers), follow-up email via outils tiers, packaging avec carte de remerciement incitant à laisser un avis honnête. Les avis vendus sont détectés par l'algorithme." },
    { question: "Qu'est-ce que le dropshipping et pourquoi Amazon l'encadre-t-il strictement ?", answers: ["Vendre ses propres produits fabriqués", "Vendre des produits qu'on ne possède pas — le fournisseur expédie directement au client. Amazon autorise mais l'adresse d'expédition doit être la vôtre", "Uniquement de la revente de produits d'occasion", "Un système d'achat groupé"], correct: 1, explanation: "Le dropshipping sur Amazon : vous prenez commande, votre fournisseur expédie au client. Amazon autorise sous conditions : vous devez être l'expéditeur officiel (votre nom/adresse), pas de factures fournisseur dans les colis. Interdit : acheter sur un autre retailer (Walmart, AliExpress) et livrer directement (retail arbitrage en dropshipping = suspension de compte)." },
    { question: "Qu'est-ce que la Buy Box Amazon et pourquoi est-elle cruciale pour les vendeurs ?", answers: ["Une promotion spéciale d'Amazon", "Le bouton 'Ajouter au panier' — 82% des ventes passent par ce bouton. Gagner la Buy Box = visibilité maximale", "Une garantie supplémentaire pour l'acheteur", "Un badge de qualité Amazon"], correct: 1, explanation: "La Buy Box est le bouton 'Ajouter au panier' en évidence sur la page produit. 82% des ventes Amazon passent par la Buy Box. Si plusieurs vendeurs offrent le même produit, l'algorithme attribue la Buy Box au meilleur selon : prix compétitif, expédition rapide (FBA favorisé), bon feedback vendeur, disponibilité stock. La perdre = ventes quasi nulles." },
    { question: "Quels outils sont indispensables pour réussir en affiliation Amazon ?", answers: ["Aucun outil nécessaire", "SiteStripe (liens Amazon), outil analytics pour suivre les conversions, site/blog/réseaux à fort trafic, tableaux de comparaison de produits", "Uniquement les publicités Facebook", "Un logiciel de comptabilité uniquement"], correct: 1, explanation: "Outils essentiels affiliation Amazon : SiteStripe (extension Chrome pour créer des liens affiliés facilement), Google Analytics (analyser le trafic et les conversions), un site/blog SEO ou réseau social à trafic qualifié, tableaux de comparaison (très efficaces pour le taux de clic), outils de gestion de liens (Pretty Links), suivi des commissions via le portail Associates Central." },
    { question: "Comment maximiser ses revenus d'affiliation Amazon avec une stratégie de contenu ?", answers: ["Publier le maximum de liens sans contenu", "Créer du contenu éducatif et comparatif ciblant des mots-clés d'achat (meilleur X pour Y) — trafic organique à forte intention d'achat", "Uniquement sur les réseaux sociaux", "Se concentrer sur un seul pays Amazon"], correct: 1, explanation: "Stratégie gagnante affiliation : créer du contenu ciblant des mots-clés à intention d'achat élevée ('meilleur blender pour smoothies', 'comparatif trottinettes électriques 2024'). Ces recherches indiquent que l'internaute est prêt à acheter. SEO long terme + contenu comparatif = trafic qualifié récurrent sans publicité. REUSSITESS®971 sur 14 pays multiplier les niches et les opportunités." },
  ],
  tips: ["L'ID affilié Amazon fb942837 de REUSSITESS®971 génère des commissions sur 14 marchés mondiaux simultanément", "82% des ventes Amazon passent par la Buy Box — comprendre son fonctionnement est indispensable pour les vendeurs", "Le contenu SEO à intention d'achat génère du trafic qualifié des années après sa publication — le meilleur ROI"],
};
export default quizAmazon;
