const quizDeveloppementPersonnel = {
  title: "Développement Personnel",
  description: "Découvrez les outils pour devenir la meilleure version de vous-même !",
  emoji: "🧘",
  questions: [
    { question: "🧠 Qu'est-ce que la zone de confort ?", answers: ["Un espace physique confortable", "L'état mental où l'on se sent à l'aise, sans stress ni challenge — mais où la croissance est limitée", "Un type de méditation", "Une technique de relaxation"], correct: 1, explanation: "La zone de confort est l'ensemble des situations familières où on ne ressent pas de stress. En dehors de cette zone se trouve la zone d'apprentissage. La croissance personnelle nécessite de la quitter régulièrement." },
    { question: "⏰ Qu'est-ce que la procrastination ?", answers: ["Une technique de productivité", "Le fait de remettre à plus tard des tâches importantes au profit d'activités moins urgentes", "Un trouble du sommeil", "Une méthode de gestion du stress"], correct: 1, explanation: "La procrastination est l'habitude de reporter les tâches importantes. Elle est souvent liée à la peur de l'échec ou de la perfection. La méthode des 2 minutes (faire immédiatement ce qui prend moins de 2 min) aide à la combattre." },
    { question: "🎯 Qu'est-ce qu'un objectif SMART ?", answers: ["Un objectif facile à atteindre", "Un objectif Spécifique, Mesurable, Atteignable, Réaliste et Temporellement défini", "Un objectif ambitieux et flou", "Un objectif choisi par son manager"], correct: 1, explanation: "SMART est un acronyme pour définir des objectifs efficaces. Exemple : 'Je veux économiser 200€ par mois pendant 6 mois pour créer mon fonds d'urgence de 1200€ d'ici décembre'." },
    { question: "🔄 Qu'est-ce que le mindset de croissance (Growth Mindset) ?", answers: ["Croire que ses capacités sont fixes et innées", "Croire que l'intelligence et les talents peuvent se développer par l'effort et l'apprentissage", "Avoir beaucoup d'ambitions", "Ignorer ses échecs"], correct: 1, explanation: "Développé par la psychologue Carol Dweck, le growth mindset est la conviction que l'on peut progresser dans n'importe quel domaine avec de l'effort. Son opposé, le fixed mindset, croit que les capacités sont figées." },
    { question: "🌙 Pourquoi la routine matinale est-elle importante ?", answers: ["Pour se coucher plus tôt", "Elle permet de prendre le contrôle de sa journée avant que le monde extérieur ne dicte son agenda", "Pour aller au sport uniquement", "C'est une mode sans réel impact"], correct: 1, explanation: "Les heures du matin sont les plus calmes et les plus productives pour beaucoup. Une routine matinale (exercice, lecture, méditation, travail profond) structure la journée et améliore la concentration et l'énergie." },
    { question: "💪 Qu'est-ce que la résilience ?", answers: ["La force physique", "La capacité à surmonter les épreuves et à rebondir après les échecs", "L'absence d'émotions", "L'optimisme excessif"], correct: 1, explanation: "La résilience est la capacité à faire face aux adversités, traumatismes et stress et à s'en remettre. Elle se développe avec l'expérience, le soutien social et les stratégies d'adaptation." },
  ],
  tips: ["🌱 Lisez 10 pages par jour — 3650 pages par an, soit une douzaine de livres transformateurs", "🎯 Un journal quotidien aide à clarifier ses pensées et suivre ses progrès", "💪 La discipline crée la liberté — les petites habitudes quotidiennes font les grands résultats"],
};
export default quizDeveloppementPersonnel;
