/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizEpicesMonde = {
  title: "Épices du Monde — Saveurs & Secrets",
  description: "Partez à la découverte des épices qui ont changé le monde, de leur histoire à leurs vertus !",
  emoji: "🌶️",
  questions: [
    { question: "Quelle épice était plus précieuse que l'or au Moyen Âge et a motivé les grandes explorations ?", answers: ["Le piment", "Le poivre noir (Piper nigrum)", "La cannelle", "La muscade"], correct: 1, explanation: "Le poivre noir était si précieux au Moyen Âge qu'il servait de monnaie d'échange et de dot. Les caravanes de la Route des Épices traversaient l'Asie. C'est la recherche d'une route directe vers les épices (poivre, cannelle, muscade) qui a motivé Vasco de Gama, Christophe Colomb et les grandes explorations du XVe siècle." },
    { question: "Quelle est l'épice la plus chère du monde, récoltée à la main en Iran, Espagne et Maroc ?", answers: ["La vanille de Madagascar", "Le safran (Crocus sativus) — jusqu'à 10 000€/kg", "La cardamome", "La truffe noire"], correct: 1, explanation: "Le safran (5 000 à 10 000€/kg) est l'épice la plus chère au monde. Il faut 150 000 à 200 000 fleurs de Crocus sativus pour produire 1 kg de safran sec. Chaque fleur ne produit que 3 stigmates récoltés à la main. L'Iran produit 90% du safran mondial. Propriétés médicinales : antidépresseur naturel (études prometteuses), antioxydant." },
    { question: "D'où vient le piment, épice incontournable de la cuisine antillaise et africaine ?", answers: ["D'Inde et d'Asie", "D'Amérique centrale et du Sud — importé en Europe par Christophe Colomb en 1493", "D'Afrique subsaharienne", "D'Arabie"], correct: 1, explanation: "Le piment (Capsicum) est originaire d'Amérique centrale et du Sud. Les Amérindiens le cultivaient depuis 7000 ans avant J.-C. Christophe Colomb l'a rapporté en Europe en 1493. Il a ensuite conquis le monde entier : cuisine indienne, africaine, thaïe, coréenne... Le piment antillais (Capsicum chinense) est l'un des plus forts au monde." },
    { question: "Quelle molécule donne au piment son caractère piquant et quels sont ses effets sur le corps ?", answers: ["La pipérine", "La capsaïcine — active les récepteurs TRPV1 de la douleur, libère endorphines et accélère le métabolisme", "La curcumine", "L'allicine"], correct: 1, explanation: "La capsaïcine active les récepteurs TRPV1 (sensibles à la chaleur) — le cerveau interprète cela comme une brûlure. Réponse : endorphines (plaisir), sueurs (thermorégulation), accélération du métabolisme. La capsaïcine est utilisée en crème analgésique (arthrite, neuropathies). Les amateurs de piment développent une tolérance grâce à la désensibilisation des récepteurs." },
    { question: "Quelle épice antillaise unique, la noix de muscade, est produite dans quelle île caribéenne ?", answers: ["La Jamaïque", "La Grenade — premier producteur mondial de muscade (40% de la production mondiale)", "Haïti", "Trinidad"], correct: 1, explanation: "La Grenade est surnommée 'l'île aux épices' et est l'un des plus grands producteurs mondiaux de muscade (Myristica fragrans). La noix de muscade produit deux épices : la muscade (graine) et le macis (arille rouge). Utilisée en cuisine antillaise, européenne et dans les boissons chaudes. Propriétés : digestive, légèrement narcotique à haute dose." },
    { question: "Qu'est-ce que les 5 épices chinoises (wu xiang fen) et dans quelle cuisine sont-elles fondamentales ?", answers: ["Sel, poivre, gingembre, ail, piment", "Anis étoilé, cannelle de Chine, clou de girofle, poivre de Sichuan, fenouil — cuisine chinoise et vietnamienne", "Curcuma, cumin, coriandre, cardamome, cannelle", "Poivre, gingembre, muscade, safran, vanille"], correct: 1, explanation: "Les 5 épices chinoises (wu xiang fen) : anis étoilé (badiane), cannelle de Chine (cassia), clou de girofle, poivre de Sichuan (baies de Zanthoxylum, effet anesthésiant unique), graines de fenouil. Fondamentales dans la cuisine cantonaise, le canard laqué de Pékin, le porc rôti, les marinades et le pho vietnamien." },
    { question: "Quelle épice est à la base de tous les curry indiens et quel est son pays de première production ?", answers: ["Le curcuma uniquement", "La cardamome verte (Elettaria cardamomum) — originaire d'Inde, surnommée 'reine des épices'", "Le cumin (Cuminum cyminum) — originaire du Moyen-Orient, base de tous les mélanges d'épices mondiaux", "Le fenugrec"], correct: 2, explanation: "Le cumin est l'épice la plus utilisée dans les mélanges d'épices mondiaux : garam masala (Inde), colombo (Antilles), ras el hanout (Maroc), chili (Mexique), cumin powder (USA). L'Inde produit 70% du cumin mondial. Propriétés : digestif puissant, carminatif (anti-ballonnements), antioxydant." },
    { question: "D'où vient la vanille et pourquoi est-elle si chère ?", answers: ["D'Inde, cultivée facilement", "Du Mexique originellement (orchidée vanilla planifolia) — pollinisation manuelle nécessaire hors de son habitat naturel", "De Madagascar uniquement", "De Polynésie française"], correct: 1, explanation: "La vanille est une orchidée grimpante originaire du Mexique. Hors du Mexique (où un colibri et une abeille spécifiques la pollinisent), chaque fleur doit être pollinisée à la main, en 12 heures d'ouverture maximum. Processus de séchage long (6 mois). Madagascar produit 80% de la vanille mondiale. Prix : 300-600€/kg selon les années." },
    { question: "Quelles épices composent le 'quatre-épices' traditionnellement utilisé dans la charcuterie et cuisine française ?", answers: ["Sel, poivre, ail, thym", "Poivre, muscade, clou de girofle, gingembre (ou cannelle selon les variantes)", "Cumin, coriandre, curcuma, piment", "Laurier, thym, romarin, persil"], correct: 1, explanation: "Le quatre-épices français : poivre noir (dominant), noix de muscade, clou de girofle, gingembre (ou cannelle selon les recettes). Utilisé en charcuterie (pâtés, terrines, boudin), viandes en sauce, cakes salés. Mélange d'épices typiquement français, hérité des épices précieuses du Moyen Âge quand elles symbolisaient richesse et prestige." },
    { question: "Pourquoi le clou de girofle était-il la cause de guerres et de massacres aux îles Moluques (Indonésie) au XVIe siècle ?", answers: ["Pour des raisons religieuses", "Il ne poussait que dans une zone géographique très limitée — son monopole valait des fortunes et les Portugais/Hollandais se sont battus pour le contrôler", "Pour des raisons territoriales sans lien avec les épices", "Les Moluquois ont attaqué les Européens en premier"], correct: 1, explanation: "Au XVIe siècle, le clou de girofle (Syzygium aromaticum) ne poussait que sur 5 îles des Moluques (Indonésie). Les Portugais puis les Hollandais (VOC) ont massacré des populations entières pour contrôler ce monopole. Le clou de girofle valait son poids en or en Europe. Ce monopole des épices a façonné la géopolitique mondiale pendant 3 siècles." },
  ],
  tips: ["Le piment est originaire des Amériques — les Antilles, l'Inde et l'Afrique ne l'ont découvert qu'après 1493", "La Grenade produit 40% de la muscade mondiale — surnommée l'île aux épices de la Caraïbe", "Le safran à 10 000€/kg nécessite 200 000 fleurs récoltées à la main pour produire 1 kg"],
};
export default quizEpicesMonde;
