/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizGraphologie = {
  title: "Graphologie — Ce que votre Écriture Révèle",
  description: "L'écriture est le miroir de l'âme — découvrez les secrets de la graphologie !",
  emoji: "✍️",
  questions: [
    { question: "Qu'est-ce que la graphologie ?", answers: ["L'étude des langues étrangères", "L'étude de la personnalité à travers l'analyse de l'écriture manuscrite", "L'art de la calligraphie", "L'étude des signatures des célébrités"], correct: 1, explanation: "La graphologie est la science (et l'art) d'analyser la personnalité, le caractère et l'état psychologique d'une personne à travers son écriture manuscrite. Elle est utilisée en recrutement (France), en psychologie et en criminologie." },
    { question: "Que révèle une écriture très penchée vers la droite ?", answers: ["Personnalité introvertie et froide", "Nature extravertie, tournée vers les autres, affectivité forte", "Intelligence supérieure", "Agressivité et violence"], correct: 1, explanation: "En graphologie, une écriture inclinée vers la droite indique une personne tournée vers l'avenir, les autres et les émotions. Elle est affective, communicative et a besoin de contacts humains. À l'inverse, une écriture penchée à gauche indique un repli sur soi." },
    { question: "Que signifie une écriture très petite (micrograhie) en graphologie ?", answers: ["Manque d'intelligence", "Concentration, précision, capacité d'analyse — souvent des personnes très méthodiques", "Grande générosité", "Manque de confiance uniquement"], correct: 1, explanation: "Une petite écriture indique concentration, sens du détail, capacité d'analyse et souvent une grande intelligence méthodique. Les scientifiques, comptables et chercheurs ont souvent une petite écriture. Elle peut aussi indiquer une certaine économie d'énergie ou discrétion." },
    { question: "Que révèle une signature illisible avec des traits énergiques ?", answers: ["Manque d'éducation", "Personne pressée, confiante, qui n'a pas besoin de l'approbation des autres", "Timidité extrême", "Problème psychologique grave"], correct: 1, explanation: "Une signature illisible et dynamique appartient souvent à des personnes pressées, décidées, qui ont confiance en elles et n'ont pas besoin que tout le monde déchiffre leur identité. Beaucoup de dirigeants et célébrités ont ce type de signature." },
    { question: "Que révèle la zone supérieure des lettres (les hampes des 'l', 'h', 'd' montant très haut) ?", answers: ["Intelligence pratique et manuelle", "Vie intellectuelle active, idéalisme, ambitions élevées, pensée abstraite", "Agressivité refoulée", "Manque de logique"], correct: 1, explanation: "La zone supérieure (hampes hautes) représente la vie intellectuelle, spirituelle et les idéaux. Des hampes très hautes indiquent un idéalisme fort, une vie mentale intense, des ambitions élevées. En graphologie, l'écriture se divise en 3 zones : supérieure (intellect), médiane (quotidien), inférieure (instincts)." },
    { question: "Que signifie une pression très forte sur le papier lors de l'écriture ?", answers: ["Faiblesse physique", "Vitalité, énergie, sensorialité forte, fort ancrage dans le monde matériel", "Nervosité uniquement", "Timidité"], correct: 1, explanation: "Une pression forte indique vitalité, énergie physique et psychique, sensualité et un fort ancrage dans le monde matériel et les sensations. Une pression légère appartient plutôt aux personnes sensibles, délicates, spirituelles ou manquant d'énergie physique." },
    { question: "Dans quel pays la graphologie est-elle le plus utilisée dans les processus de recrutement ?", answers: ["USA", "Allemagne", "France", "Japon"], correct: 2, explanation: "La France est le pays où la graphologie est la plus utilisée dans le recrutement professionnel. 50 à 75% des grandes entreprises françaises auraient eu recours à la graphologie dans leurs processus de sélection, bien que son efficacité scientifique reste débattue." },
    { question: "Que révèle un 'i' dont le point est placé très loin et haut au-dessus de la lettre ?", answers: ["Négligence", "Esprit vif, imagination active, curiosité intellectuelle", "Désorganisation grave", "Mensonge habituel"], correct: 1, explanation: "Un point du 'i' placé haut et loin indique un esprit rapide, imaginatif et curieux. Le point du 'i' est révélateur : cercle = créativité artistique, virgule = sens de l'humour, très proche = méticulosité, absent = tête dans les nuages ou précipitation." },
    { question: "Comment s'appelle l'analyse de l'écriture pour déterminer si un document est authentique ou falsifié ?", answers: ["Graphologie judiciaire", "Calligraphie forensique", "Expertises en écritures — graphologie criminalistique", "Sémiologie scripturale"], correct: 2, explanation: "L'expertise en écritures (ou graphologie criminalistique/forensique) est utilisée par les tribunaux pour authentifier des documents, testaments, contrats et signatures. Les experts en écritures sont des témoins experts reconnus dans les procédures judiciaires." },
    { question: "Que révèle une écriture très régulière et uniforme sans variation ?", answers: ["Grande créativité", "Rigidité, contrôle de soi, besoin d'ordre et de structure, parfois manque de spontanéité", "Intelligence exceptionnelle", "Grande générosité"], correct: 1, explanation: "Une écriture très régulière et uniforme indique une personnalité ordonnée, méthodique, qui aime le contrôle et la structure. Ces personnes sont fiables, prévisibles et disciplinées mais peuvent manquer de spontanéité et d'adaptabilité face à l'imprévu." },
  ],
  tips: ["La graphologie analyse l'ensemble de l'écriture — jamais un seul signe isolé", "L'état émotionnel du moment influence l'écriture — une analyse sérieuse nécessite plusieurs échantillons", "En France, la graphologie est utilisée dans 50% des grandes entreprises pour le recrutement"],
};
export default quizGraphologie;
