const quizLeadership = {
  title: "Leadership",
  description: "Découvrez les qualités qui font les grands leaders !",
  emoji: "👑",
  questions: [
    { question: "👑 Quelle est la différence entre un manager et un leader ?", answers: ["Il n'y en a aucune", "Le manager gère des processus, le leader inspire des personnes vers une vision commune", "Le leader a plus d'autorité", "Le manager est plus expérimenté"], correct: 1, explanation: "Un manager s'assure que les tâches sont accomplies correctement. Un leader inspire, motive et guide les personnes vers une vision. On peut être l'un sans être l'autre — les meilleurs sont les deux." },
    { question: "🎯 Qu'est-ce que le leadership servant ?", answers: ["Servir des repas à son équipe", "Un style où le leader se met au service de son équipe pour l'aider à donner le meilleur d'elle-même", "Obéir à tous ses collaborateurs", "Un leadership faible"], correct: 1, explanation: "Le leadership servant (Robert Greenleaf) place les besoins de l'équipe en priorité. Le leader enlève les obstacles, développe les talents et crée un environnement où chacun peut s'épanouir." },
    { question: "💬 Pourquoi l'écoute active est-elle essentielle en leadership ?", answers: ["Pour gagner du temps", "Elle crée la confiance, révèle les vrais problèmes et montre que les opinions de l'équipe comptent", "Pour paraître intelligent", "Elle n'est pas importante"], correct: 1, explanation: "L'écoute active — écouter pour comprendre et non pour répondre — est la compétence la plus sous-estimée du leadership. Elle crée la confiance, améliore la prise de décision et renforce l'engagement de l'équipe." },
    { question: "🔥 Qu'est-ce que l'intelligence émotionnelle en leadership ?", answers: ["Contrôler ses émotions en les cachant", "La capacité à reconnaître, comprendre et gérer ses émotions et celles des autres", "Être toujours positif", "Ne jamais montrer de vulnérabilité"], correct: 1, explanation: "L'intelligence émotionnelle (Daniel Goleman) est souvent plus prédictive du succès en leadership que le QI. Elle comprend la conscience de soi, la maîtrise de soi, l'empathie et les compétences sociales." },
    { question: "🌱 Comment un bon leader gère-t-il l'échec de son équipe ?", answers: ["En punissant les responsables", "En transformant l'échec en opportunité d'apprentissage collectif sans chercher des coupables", "En ignorant l'échec", "En prenant seul la responsabilité pour protéger l'équipe"], correct: 1, explanation: "Les meilleurs leaders créent une culture où l'échec est perçu comme un apprentissage. Ils analysent ce qui n'a pas fonctionné, tirent les leçons et renforcent les processus — sans stigmatiser les personnes." },
    { question: "🌍 Qu'est-ce qui caractérise un leader inclusif ?", answers: ["Traiter tout le monde de façon identique", "Valoriser les différences, créer un sentiment d'appartenance et s'assurer que chaque voix est entendue", "Éviter les conflits à tout prix", "Favoriser uniquement les plus performants"], correct: 1, explanation: "Le leadership inclusif reconnaît que la diversité des perspectives renforce la prise de décision. Il crée un environnement où chacun peut contribuer pleinement, quelles que soient ses origines, croyances ou identité." },
  ],
  tips: ["👑 Le vrai leadership commence par se diriger soi-même", "🌍 La diaspora a des compétences interculturelles uniques qui font de grands leaders", "💡 Lisez 'Les 21 lois irréfutables du leadership' de John Maxwell"],
};
export default quizLeadership;
