/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizCommunication = {
  title: "Communication & Art de Convaincre",
  description: "Maîtrisez l'art de communiquer, persuader et influencer positivement !",
  emoji: "🗣️",
  questions: [
    { question: "Selon Albert Mehrabian, quelle proportion de la communication est non-verbale ?", answers: ["10%", "38%", "55%", "93%"], correct: 3, explanation: "La règle de Mehrabian (1967) : dans une communication émotionnelle, 7% = les mots, 38% = le ton de la voix, 55% = le langage corporel. Soit 93% non-verbal ! Attention : cette règle s'applique spécifiquement aux messages émotionnels, pas à toute communication." },
    { question: "Qu'est-ce que l'écoute active selon Carl Rogers ?", answers: ["Écouter en faisant autre chose", "Écouter avec toute son attention, reformuler et valider sans juger pour que l'autre se sente vraiment compris", "Prendre des notes pendant que l'autre parle", "Hocher la tête régulièrement"], correct: 1, explanation: "L'écoute active (Carl Rogers) implique : attention totale (ranger le téléphone), reformulation (répéter avec ses mots), validation émotionnelle (reconnaître les sentiments), questions ouvertes et absence de jugement. Les études montrent que se sentir écouté est l'un des besoins humains les plus fondamentaux." },
    { question: "Qu'est-ce que le principe de réciprocité de Robert Cialdini dans l'influence ?", answers: ["Donner seulement si on reçoit quelque chose", "Les personnes se sentent obligées de rendre un service ou cadeau reçu — donner en premier crée une obligation naturelle", "Ne rien donner pour ne rien devoir", "Exiger avant de donner"], correct: 1, explanation: "La réciprocité est l'un des 6 principes d'influence de Cialdini ('Influence', 1984). Les humains sont câblés pour rendre ce qu'ils reçoivent. Les commerciaux offrent des échantillons gratuits, les négociateurs font des concessions en premier. Donner sans attendre crée une puissante obligation naturelle de réciprocité." },
    { question: "Quelle technique d'argumentation structure un discours persuasif en 3 parties ?", answers: ["Introduction-Développement-Conclusion", "Problème-Agitation-Solution (PAS) ou Situation-Complication-Résolution", "Thèse-Antithèse-Synthèse uniquement", "Toutes ces structures sont équivalentes"], correct: 1, explanation: "La structure PAS (Problème-Agitation-Solution) est très efficace : 1. Identifier le problème du public, 2. Amplifier la douleur de ce problème (agitation), 3. Présenter votre solution comme le remède. Elle est très utilisée en marketing et prise de parole publique car elle suit le parcours émotionnel naturel de l'audience." },
    { question: "Qu'est-ce que le principe de preuve sociale (social proof) dans la persuasion ?", answers: ["Les gens font ce que la loi impose", "Les individus suivent le comportement des autres dans l'incertitude — 'si les autres le font, c'est que c'est bien'", "Les preuves scientifiques uniquement convainquent", "Les témoignages d'experts seulement"], correct: 1, explanation: "La preuve sociale (Cialdini) : les humains regardent les comportements des autres pour décider comment agir dans l'incertitude. C'est pourquoi les avis clients, témoignages, 'best-seller', foules et popularité sont si persuasifs. Les plateformes sociales exploitent massivement ce mécanisme." },
    { question: "Qu'est-ce que la technique du 'pied dans la porte' en persuasion ?", answers: ["Forcer une porte fermée", "Obtenir un petit accord d'abord pour faciliter l'acceptation d'une demande plus grande ensuite", "Frapper avant d'entrer", "Commencer par la plus grande demande"], correct: 1, explanation: "Le pied-dans-la-porte (Freedman & Fraser, 1966) : commencer par une petite demande facile à accepter, puis progressivement augmenter. Les personnes ayant dit oui une fois ont tendance à rester cohérentes et dire oui encore. Principe d'engagement et de cohérence." },
    { question: "Comment structurer un feedback constructif selon la méthode sandwich ?", answers: ["Critique-Critique-Critique", "Positif-Point d'amélioration-Positif", "Négatif d'abord pour être honnête", "Questions uniquement, jamais d'affirmations"], correct: 1, explanation: "Le feedback sandwich : 1. Commencer par un point positif sincère (le pain), 2. Le point d'amélioration spécifique et actionnable (la garniture), 3. Terminer par un encouragement positif (le pain). Cette structure rend le feedback plus facile à recevoir et moins défensif." },
    { question: "Qu'est-ce que le storytelling et pourquoi est-il plus persuasif que les arguments logiques ?", answers: ["Raconter des mensonges pour convaincre", "L'art de communiquer via des histoires qui activent les émotions et la mémoire plus efficacement que les faits seuls", "Parler longtemps pour impressionner", "Exagérer pour captiver l'attention"], correct: 1, explanation: "Les neurosciences montrent que les histoires activent jusqu'à 7 zones du cerveau (visuelles, sensorielles, émotionnelles) contre 2 pour les données pures. Les histoires libèrent de l'ocytocine (hormone de confiance). Un fait seul est oublié en 72 heures, une histoire liée à ce fait reste en mémoire pendant des années." },
    { question: "Quelle est la règle d'or de la communication interculturelle ?", answers: ["Parler fort et lentement dans sa langue", "Ne pas supposer que ses codes culturels sont universels — observer et s'adapter", "Apprendre l'anglais suffit partout", "Éviter les sujets sensibles dans toutes les cultures"], correct: 1, explanation: "La communication interculturelle exige de suspendre ses certitudes culturelles. Ce qui est poli dans une culture peut être impoli dans une autre (contact visuel, distance physique, ponctualité, silence, gestes). L'outil GLOBE ou les travaux de Geert Hofstede sur les dimensions culturelles sont des référence indispensables." },
    { question: "Qu'est-ce que l'assertivité, idéale entre passivité et agressivité ?", answers: ["S'affirmer en imposant sa volonté", "Exprimer ses besoins, opinions et limites clairement et respectueusement sans agressivité ni soumission", "Ne jamais dire non", "Toujours avoir le dernier mot"], correct: 1, explanation: "L'assertivité (Wolpe, 1950s) est la capacité à s'exprimer directement et honnêtement tout en respectant l'autre. Le triangle : Passivité (je cède, je me tais), Agressivité (j'impose, j'attaque), Assertivité (je dis clairement ce que je pense/veux/ressens dans le respect mutuel). Se développe avec la pratique." },
  ],
  tips: ["93% de la communication est non-verbale dans les messages émotionnels — soignez votre ton et posture", "Le storytelling active 7 zones du cerveau vs 2 pour les données — racontez toujours des histoires", "Donner en premier sans attente crée une réciprocité naturelle puissante"],
};
export default quizCommunication;
