/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizGestionStress = {
  title: "Gestion du Stress & Résilience",
  description: "Apprenez à maîtriser le stress, renforcer votre résilience et retrouver votre équilibre !",
  emoji: "🧘",
  questions: [
    { question: "Quelle est la différence entre le bon stress (eustress) et le mauvais stress (distress) ?", answers: ["Il n'y a pas de bon stress", "L'eustress est stimulant et motivant (défi positif), le distress est paralysant et destructeur (surcharge)", "Le bon stress dure longtemps", "Tout stress est mauvais pour la santé"], correct: 1, explanation: "Hans Selye (1956) a distingué l'eustress (bon stress) — qui motive, stimule et améliore la performance (avant une compétition, un entretien) — du distress (mauvais stress) — chronique, épuisant et destructeur pour la santé. L'objectif n'est pas de supprimer tout stress mais de le maintenir à un niveau optimal." },
    { question: "Quelle hormone est principale lors de la réponse au stress et quels sont ses effets chroniques ?", answers: ["L'ocytocine", "Le cortisol — à court terme utile, chronique il détruit l'immunité, la mémoire et la santé cardiovasculaire", "L'adrénaline uniquement", "La mélatonine"], correct: 1, explanation: "Le cortisol est l'hormone principale du stress. À court terme : augmente l'énergie, la vigilance (utile). Chronique : détruit le système immunitaire, réduit la mémoire (hippocampe), augmente le risque cardiovasculaire et dépression. La pratique régulière de relaxation réduit significativement le cortisol." },
    { question: "La technique 4-7-8 de respiration anti-stress consiste en quoi ?", answers: ["4 respirations rapides, 7 lentes, 8 très lentes", "Inspirer 4s, retenir 7s, expirer 8s — active le système nerveux parasympathique", "4 minutes de sport, 7 de repos, 8 d'étirement", "4 pauses dans la journée de 7-8 minutes"], correct: 1, explanation: "La technique 4-7-8 du Dr Andrew Weil : inspirer par le nez 4 secondes, retenir 7 secondes, expirer par la bouche 8 secondes. Répéter 4 cycles. Cette technique active le nerf vague et le système nerveux parasympathique (repos), contrebalançant le sympathique (stress). Efficace en 60 secondes." },
    { question: "Qu'est-ce que le burnout et comment le distinguer de la fatigue normale ?", answers: ["Une grande fatigue qui passe avec le sommeil", "L'épuisement total physique, émotionnel et mental avec cynisme et perte de sens — ne se récupère pas avec du repos", "Un manque de motivation passager", "Un syndrome uniquement médical rare"], correct: 1, explanation: "Le burnout (Christina Maslach) est un syndrome en 3 dimensions : épuisement émotionnel profond, dépersonnalisation/cynisme, et sentiment d'inefficacité. Différent de la fatigue : le repos ne suffit pas à récupérer. Reconnu par l'OMS en 2019 comme phénomène professionnel. Prévention : limites claires, sens du travail, soutien social." },
    { question: "Quelle pratique a été prouvée scientifiquement comme réduisant l'anxiété de 39% en 8 semaines ?", answers: ["Regarder la télévision", "La méditation de pleine conscience (MBSR — Mindfulness-Based Stress Reduction)", "Le sport intensif uniquement", "Les antidépresseurs seuls"], correct: 1, explanation: "Le programme MBSR (Jon Kabat-Zinn, Université du Massachusetts) a prouvé en 300+ études cliniques réduire l'anxiété de 39%, la dépression de 30% et la douleur chronique significativement en 8 semaines de pratique. Le cerveau se modifie structurellement (neuroplasticité) avec la méditation régulière." },
    { question: "Qu'est-ce que la 'douche froide' recommandée pour la résilience et la vitalité ?", answers: ["Un mythe sans fondement scientifique", "L'exposition volontaire au froid active la dopamine (+250%), renforce le système immunitaire et entraîne la tolérance à l'inconfort", "Uniquement utile pour les sportifs", "Efficace seulement en hiver"], correct: 1, explanation: "Les recherches de Wim Hof et des études récentes montrent : douche froide 2-3 minutes → augmentation de la dopamine de 250%, noradrénaline de 300%, activation du système immunitaire. Andrew Huberman (Stanford) confirme : 11 minutes/semaine d'exposition au froid transforment la tolérance au stress et l'énergie." },
    { question: "Quels sont les 5 piliers du bien-être selon le modèle PERMA de Martin Seligman ?", answers: ["Passion, Énergie, Repos, Méditation, Ambition", "Positive emotions, Engagement, Relations, Meaning, Accomplishment", "Plaisir, Équilibre, Repos, Mouvement, Alimentation", "Paix, Équité, Raison, Modération, Amour"], correct: 1, explanation: "Martin Seligman (père de la psychologie positive) a développé PERMA : Positive emotions (émotions positives), Engagement (état de flow), Relationships (relations positives), Meaning (sens et but), Accomplishment (réalisations). Ces 5 piliers constituent le bien-être durable selon ses recherches sur 23 pays." },
    { question: "Comment le sport agit-il biologiquement sur le stress et l'anxiété ?", answers: ["En vous fatiguant pour vous faire dormir", "Libère endorphines, BDNF (fertilisant du cerveau), réduit le cortisol et crée de nouveaux neurones dans l'hippocampe", "Uniquement par distraction mentale", "Réduit l'anxiété seulement à long terme (années)"], correct: 1, explanation: "L'exercice physique est l'antidépresseur et anti-anxieux le plus puissant connu : libère endorphines, dopamine, sérotonine, BDNF (Brain-Derived Neurotrophic Factor qui crée de nouveaux neurones). Réduit le cortisol. Une étude de Duke a montré que 30 minutes de jogging 3x/semaine = antidépresseur à 6 mois." },
    { question: "Qu'est-ce que le journal de gratitude et pourquoi change-t-il le cerveau ?", answers: ["Une pratique superficielle sans effet prouvé", "Noter 3 choses positives par jour reconfigure le cerveau vers le positif (biais de négativité contrebalancé)", "Écrire uniquement les grandes réussites", "Un journal intime traditionnel"], correct: 1, explanation: "Notre cerveau a un biais de négativité naturel (survie : mémoriser les menaces). Écrire 3 gratitudes spécifiques par jour pendant 21 jours reconfigure progressivement le cerveau. Martin Seligman a montré une hausse du bonheur de 25% et réduction de la dépression significative avec cette pratique simple." },
    { question: "Qu'est-ce que la technique STOP pour gérer un moment de stress aigu ?", answers: ["Arrêter tout travail et dormir", "Stop (s'arrêter), Take a breath (respirer), Observe (observer pensées et sensations), Proceed (reprendre avec conscience)", "Stopper la conversation, Téléphoner à un ami, Observer la nature, Prendre un médicament", "S'éloigner, Trouver de l'eau, Observer les autres, Parler"], correct: 1, explanation: "La technique STOP issue de la pleine conscience : S = Stop (s'arrêter physiquement), T = Take a breath (une respiration profonde), O = Observe (observer pensées, émotions, sensations sans jugement), P = Proceed (reprendre l'activité avec plus de conscience). Utilisable en toutes circonstances en 60 secondes." },
  ],
  tips: ["11 minutes de douche/bain froid par semaine augmentent la dopamine de 250% et la résilience au stress", "PERMA : les 5 piliers du bien-être durable — les émotions positives ne suffisent pas seules", "Le sport 3x30 minutes par semaine est aussi efficace qu'un antidépresseur — prouvé par l'Université Duke"],
};
export default quizGestionStress;
