/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizSuedeEssentiel = {
  title: "Suède — Essentiel Voyage & Culture",
  description: "Droits, règles, culture et bons à savoir avant d'aller en Suède !",
  emoji: "🇸🇪",
  questions: [
    { question: "🛂 Faut-il un visa pour aller en Suède depuis la France ?", answers: ["Oui visa Schengen", "Non espace Schengen libre", "Passeport biométrique obligatoire", "AVE suédoise"], correct: 1, explanation: "La Suède est dans l'espace Schengen depuis 1996. Les Français et Guadeloupéens circulent librement avec carte d'identité ou passeport. Pas de contrôle aux frontières terrestres normalement." },
    { question: "🌞 Quel phénomène naturel permet en Suède de ne jamais voir la nuit en été ?", answers: ["L'effet de serre", "Le Soleil de minuit", "La réflexion des glaciers", "L'aurore boréale"], correct: 1, explanation: "Au nord du cercle arctique (nord de la Suède), le soleil ne se couche pas pendant plusieurs semaines en été : c'est le soleil de minuit. À Kiruna en juin, il fait jour 24h/24. À l'inverse, en hiver, le soleil ne se lève parfois que 2-3 heures." },
    { question: "🏛️ La Suède est-elle une monarchie ou une République ?", answers: ["République présidentielle", "Monarchie constitutionnelle", "Monarchie absolue", "République parlementaire"], correct: 1, explanation: "La Suède est une monarchie constitutionnelle depuis 1809. Le roi Carl XVI Gustaf est chef d'État depuis 1973. La famille royale a un rôle symbolique et représentatif — aucun pouvoir politique. Le Parlement (Riksdag) détient le pouvoir législatif." },
    { question: "🌿 Qu'est-ce que l'Allemansrätten (droit de tous) en Suède ?", answers: ["Droit au chômage universel", "Droit d'accès libre à la nature, même privée", "Droit au logement gratuit", "Droit de vote à 16 ans"], correct: 1, explanation: "L'Allemansrätten est un droit unique : tout le monde peut marcher, camper, cueillir des baies et champignons sur n'importe quelle terre en Suède, même privée, tant qu'on respecte la nature et les propriétaires. Concept intraduisible et unique au monde." },
    { question: "💶 La Suède utilise-t-elle l'Euro ?", answers: ["Oui depuis 2002", "Non, la Couronne suédoise (SEK)", "Oui depuis 2010", "Non, le Krone danois"], correct: 1, explanation: "La Suède n'a pas adopté l'Euro malgré son appartenance à l'UE. La monnaie est la Couronne suédoise (SEK, kr). 1€ vaut environ 11 SEK. Les cartes bancaires sont acceptées PARTOUT — la Suède est le pays le plus sans-cash du monde." },
    { question: "🏥 Quel concept social suédois garantit le bien-être de l'enfant même dans le droit du travail ?", answers: ["Le droit à la crèche", "Le congé parental de 480 jours partageable entre les deux parents", "L'école gratuite de 0 à 18 ans", "L'allocation universelle enfant"], correct: 1, explanation: "La Suède offre 480 jours de congé parental (environ 16 mois) à se partager entre les deux parents. 90 jours sont réservés à chaque parent (use it or lose it). Payé à 80% du salaire. Modèle mondial d'égalité parentale." },
    { question: "❄️ Quelle est la température moyenne en janvier à Stockholm ?", answers: ["-20°C", "-3°C à -5°C", "0°C", "-15°C"], correct: 1, explanation: "Stockholm a en moyenne -3°C à -5°C en janvier avec des minimales pouvant aller à -15°C. Le nord de la Suède (Laponie) peut atteindre -30°C. Les Suédois ont un dicton : il n'y a pas de mauvais temps, seulement de mauvais vêtements." },
    { question: "🎶 Quel groupe suédois est l'un des plus vendus de l'histoire de la musique mondiale ?", answers: ["Roxette", "ABBA", "Ace of Base", "Europe"], correct: 1, explanation: "ABBA (Agnetha, Björn, Benny, Anni-Frid) est l'un des groupes les plus vendus au monde avec 400 millions d'albums. Formé en 1972 à Stockholm, leurs titres (Dancing Queen, Waterloo, Mamma Mia) restent des classiques mondiaux. Le musée ABBA est à Stockholm." },
    { question: "🐻 Combien d'ours bruns vivent en liberté en Suède ?", answers: ["100", "500", "3 000", "10 000"], correct: 2, explanation: "La Suède abrite environ 3 000 ours bruns, la plus grande population d'Europe occidentale. Ils vivent principalement dans les forêts du centre et nord du pays. Les rencontres sont très rares mais en randonnée, faites du bruit pour vous signaler." },
    { question: "♻️ Quel pourcentage des déchets ménagers suédois est recyclé ou transformé en énergie ?", answers: ["50%", "75%", "99%", "85%"], correct: 2, explanation: "La Suède recycle ou transforme en énergie 99% de ses déchets ménagers. Seulement 1% finit en décharge. La Suède importe même des déchets d'autres pays pour alimenter ses usines de valorisation énergétique. Modèle mondial de gestion des déchets." },
  ],
  tips: ["La Suède est quasi 100% sans cash — carte bancaire acceptée partout, même pour 1 SEK", "L'Allemansrätten vous permet de camper librement dans la nature suédoise", "Emportez des vêtements chauds même en été dans le nord — températures imprévisibles"],
};
export default quizSuedeEssentiel;
