const quizAstrologie = {
  title: "Astrologie — Les 12 Signes & Leurs Secrets",
  description: "Découvrez les secrets des 12 signes du zodiaque, leurs planètes et leur influence !",
  emoji: "⭐",
  questions: [
    { question: "Quel signe du zodiaque est représenté par le Bélier et quelles sont ses dates ?", answers: ["21 mars - 20 avril", "21 avril - 20 mai", "21 février - 20 mars", "21 mai - 20 juin"], correct: 0, explanation: "Le Bélier (21 mars - 20 avril) est le premier signe du zodiaque. Planète maîtresse : Mars. Élément : Feu. Qualités : courageux, pionnier, dynamique, leadership naturel. Défauts : impulsif, impatient, autoritaire." },
    { question: "Quelle planète gouverne le signe de la Balance ?", answers: ["Mars", "Saturne", "Vénus", "Jupiter"], correct: 2, explanation: "La Balance (23 sept - 22 oct) est gouvernée par Vénus, planète de l'amour et de la beauté. Ce signe est celui de l'harmonie, la justice et les relations. Les Balance sont diplomates, charmants et recherchent l'équilibre en toute chose." },
    { question: "Quel est le seul signe du zodiaque représenté par un objet inanimé (non vivant) ?", answers: ["Verseau", "Balance", "Sagittaire", "Capricorne"], correct: 1, explanation: "La Balance est le seul signe représenté par un objet inanimé : la balance de la justice. Tous les autres signes sont représentés par des êtres vivants (humains ou animaux). La Balance symbolise l'équité, la justice et l'harmonie." },
    { question: "Quel signe est gouverné par Pluton et associé aux transformations profondes et aux mystères ?", answers: ["Capricorne", "Scorpion", "Poissons", "Cancer"], correct: 1, explanation: "Le Scorpion (23 oct - 21 nov) est gouverné par Pluton (et Mars en astrologie traditionnelle). C'est le signe de la transformation, de la mort et de la renaissance symbolique, de la sexualité et des mystères. Intense, magnétique et profond." },
    { question: "Les signes de Feu sont le Bélier, le Lion et quel troisième signe ?", answers: ["Verseau", "Sagittaire", "Gémeaux", "Scorpion"], correct: 1, explanation: "Les 3 signes de Feu sont Bélier, Lion et Sagittaire. Ils partagent : enthousiasme, passion, créativité, leadership et optimisme. Les signes de Terre sont Taureau, Vierge, Capricorne. D'Air : Gémeaux, Balance, Verseau. D'Eau : Cancer, Scorpion, Poissons." },
    { question: "Quelle est la particularité du signe des Gémeaux symbolisé par les Jumeaux ?", answers: ["Très solitaire et introverti", "Double personnalité, curiosité insatiable, adaptabilité", "Très stable et routinier", "Très émotionnel et sensible"], correct: 1, explanation: "Les Gémeaux (21 mai - 21 juin) sont gouvernés par Mercure. Symbolisés par les Jumeaux, ils incarnent la dualité. Curieux, communicatifs, adaptables, ils peuvent sembler changeants ou inconstants. Excellents communicateurs et intellectuels." },
    { question: "Quel signe astrologique est associé au leadership, à l'orgueil et est symbolisé par l'animal roi ?", answers: ["Bélier", "Capricorne", "Lion", "Sagittaire"], correct: 2, explanation: "Le Lion (23 juil - 22 août) est gouverné par le Soleil, l'astre roi. Symbolisé par le lion, il incarne le leadership, la générosité, la créativité et le besoin de reconnaissance. Naturellement charismatique, il aime briller et inspirer les autres." },
    { question: "Mercure, planète de la communication, gouverne quels signes ?", answers: ["Gémeaux seulement", "Vierge seulement", "Gémeaux et Vierge", "Balance et Verseau"], correct: 2, explanation: "Mercure gouverne à la fois les Gémeaux (communication, intellect, légèreté) et la Vierge (analyse, précision, méthode). Ces deux signes ont en commun l'intelligence vive et le goût du détail, bien qu'exprimés très différemment." },
    { question: "Qu'est-ce que l'Ascendant en astrologie ?", answers: ["Le signe du mois de naissance", "Le signe zodiacal qui se levait à l'horizon à l'heure exacte de la naissance", "La planète la plus proche de la Lune", "Le signe de la mère"], correct: 1, explanation: "L'Ascendant est le signe qui se levait à l'est de l'horizon à l'heure précise de votre naissance. Il représente votre façade sociale, comment les autres vous perçoivent au premier abord. Un thème natal complet prend en compte Soleil + Lune + Ascendant." },
    { question: "Quel signe du zodiaque est associé à la spiritualité, l'empathie et est symbolisé par deux poissons nageant en sens opposés ?", answers: ["Cancer", "Verseau", "Poissons", "Scorpion"], correct: 2, explanation: "Les Poissons (19 fév - 20 mars) sont gouvernés par Neptune. Dernier signe du zodiaque, ils incarnent la dissolution des frontières, l'empathie universelle, la spiritualité et la créativité artistique. Très intuitifs mais parfois perdus entre rêve et réalité." },
  ],
  tips: ["Votre signe solaire n'est qu'une partie de votre personnalité — Lune et Ascendant sont tout aussi importants", "L'astrologie occidentale se base sur la position du Soleil au moment de la naissance", "Il existe aussi l'astrologie chinoise, védique (indienne) et maya — toutes différentes"],
};
export default quizAstrologie;
