const quizStreetFood = {
  title: "Street Food Mondiale — Saveurs des Rues",
  description: "Tour du monde des meilleures cuisines de rue — culture, histoire et secrets des plats emblématiques !",
  emoji: "🍜",
  questions: [
    { question: "Quelle ville asiatique est considérée comme la capitale mondiale du street food selon CNN et Lonely Planet ?", answers: ["Tokyo", "Bangkok", "Singapour", "Penang (Malaisie)"], correct: 3, explanation: "Penang (Malaisie) est régulièrement couronnée meilleure destination street food mondiale. Son histoire de carrefour commercial (Chinois, Malais, Indiens, Arabes) a créé une fusion culinaire unique. Plats emblématiques : Char Kway Teow (nouilles sautées), Laksa (soupe épicée), Asam Laksa (poisson), Nasi Kandar, Cendol. Les hawker centres sont actifs 24h/24." },
    { question: "Qu'est-ce que le Pad Thaï et quand a-t-il été créé ?", answers: ["Plat ancestral thaïlandais millénaire", "Plat relativement récent créé dans les années 1940 par un programme gouvernemental pour unifier la nation et réduire la consommation de riz", "Plat d'origine chinoise importé en Thaïlande", "Recette familiale traditionnelle sans histoire politique"], correct: 1, explanation: "Le Pad Thaï a été créé/popularisé dans les années 1940 sous le Premier Ministre Plaek Phibunsongkhram dans le cadre d'un programme nationaliste visant à créer une identité culinaire thaïlandaise unifiée. Base : nouilles de riz, œuf, germes de soja, cacahuètes, crevettes ou tofu, sauce de tamarin. Aujourd'hui l'un des plats les plus connus au monde." },
    { question: "Qu'est-ce que le 'doubles', street food incontournable de Trinidad-et-Tobago ?", answers: ["Un double espresso trinidadien", "Deux pains bara frits garnis de channa (pois chiches épicés), chutneys et piment — petit-déjeuner national", "Un sandwich double couche", "Un rhum cocktail double dose"], correct: 1, explanation: "Le doubles est le street food emblématique de Trinidad, héritage indo-trinidadien. Deux petits pains plats frits (bara) garnis de channa (pois chiches en curry), sauce tamarind, chutney de mangue verte et piment. Vendu aux carrefours depuis 5h du matin. Un doubles coûte environ 5 TTD (0,70€). Culture ouvrière et fusion afro-indienne unique." },
    { question: "Quelle est l'histoire du hot dog américain, devenu symbole de la culture de rue US ?", answers: ["Invention américaine pure du XIXe siècle", "Saucisse amenée par les immigrants allemands (Frankfurter Würstchen) popularisée dans les années 1870-1900 à New York et lors des Expositions Universelles", "Invention des années 1950 pour les fast-foods", "Origine inconnue"], correct: 1, explanation: "Le hot dog vient de la Frankfurter Würstchen (saucisse de Francfort, Allemagne). Les immigrants allemands l'ont apportée aux États-Unis. Charles Feltman l'a popularisée à Coney Island (Brooklyn) en 1867 dans un petit pain. Le nom hot dog viendrait des plaisanteries sur la viande de chien (début XXe siècle). 20 milliards de hot dogs consommés aux USA chaque année." },
    { question: "Qu'est-ce que le 'accra de morue', street food emblématique des Antilles françaises ?", answers: ["Un gâteau antillais sucré", "Beignet salé de morue dessalée mélangée à de la pâte à beignet épicée — apéritif et street food des marchés antillais", "Un poisson grillé en papillote", "Un sandwich créole"], correct: 1, explanation: "L'accra de morue est le beignet frit salé incontournable des marchés et fêtes antillaises. Morue dessalée émiettée, farine, œuf, piment végétarien, cive, ail, thym. Frit à l'huile très chaude. Servi brûlant à l'apéritif ou en entrée. Héritage africain (akara = beignet en yoruba) adapté aux Antilles avec la morue de la pêche coloniale." },
    { question: "D'où vient le kebab, street food mondial vendu sur tous les continents ?", answers: ["D'Allemagne (invention des années 1970)", "Du Moyen-Orient et d'Asie centrale — technique de cuisson de viande sur broche millénaire, popularisée en Europe par la diaspora turque", "De Grèce (gyros uniquement)", "D'Iran uniquement"], correct: 1, explanation: "Le kebab (en turc : viande grillée) est une technique millénaire du Moyen-Orient et d'Asie centrale. Le döner kebab moderne tel qu'on le connaît en Europe a été popularisé en Allemagne par Kadir Nurman (Berlin, 1972), immigrant turc. Il y a aujourd'hui 16 000 restaurants kebab en Allemagne, plus que McDonald's. Le dürüm (wrap) est une innovation allemande de la diaspora turque." },
    { question: "Qu'est-ce que la 'arepas', street food incontournable de Colombie et Venezuela ?", answers: ["Un dessert sucré en feuille de bananier", "Galette de maïs blanc (masa) grillée ou frite, garnie de fromage, viande, avocat — base alimentaire andine millénaire", "Un beignet sucré au sirop", "Un cocktail de fruits tropicaux"], correct: 1, explanation: "L'arepa est une galette de maïs blanc précolombien, base de l'alimentation de Colombie et Venezuela depuis plus de 3000 ans. En Colombie : généralement plus petite et moins garnie. Au Venezuela : plus grande, coupée en deux et farcie (reina pepiada = poulet/avocat, pabellón = viande effilochée/haricots noirs). Classée au patrimoine culturel vénézuélien." },
    { question: "Quel pays asiatique a la plus grande diversité de dim sum, ces bouchées vapeur de la cuisine cantonaise ?", answers: ["Le Japon", "Hong Kong et la Chine cantonaise — tradition du Yum Cha (boire le thé) avec dim sum depuis les maisons de thé de la Route de la Soie", "Singapour uniquement", "La Thaïlande"], correct: 1, explanation: "Le dim sum (點心 = toucher le cœur) est une tradition cantonaise née dans les maisons de thé (茶樓 cha lau) de la Route de la Soie. Hong Kong est la capitale du dim sum avec des centaines de variétés : har gow (crevette), siu mai (porc/crevette), cheong fun (rouleaux de riz), egg tart, turnip cake. Le brunch dim sum du dimanche matin est un rituel familial sacré à Hong Kong." },
    { question: "Qu'est-ce que la 'pani puri' (golgappa), street food la plus populaire d'Inde ?", answers: ["Une soupe de rue chaude", "Petite sphère de pâte frite creuse remplie d'eau aromatisée épicée (pani), pois chiches, chutney — explosion de saveurs en une bouchée", "Un sandwich épicé indien", "Un dessert sucré soufflé"], correct: 1, explanation: "La pani puri est sans doute le street food le plus populaire d'Inde. Une petite boule de pâte soufflée et frite (puri) est percée, remplie de pois chiches, pomme de terre écrasée, puis d'eau aromatisée (pani : eau, menthe, tamarin, cumin, piment). À manger d'une seule bouchée avant qu'elle se ramollisse. Chaque région a sa version différente." },
    { question: "Pourquoi le street food est-il souvent plus authentique et culturellement révélateur qu'un restaurant gastronomique ?", answers: ["Parce qu'il est moins cher uniquement", "Il reflète la cuisine populaire quotidienne, les techniques ancestrales et les saveurs que les habitants consomment réellement, non adaptées aux touristes", "Les restaurants gastronomiques utilisent les mêmes recettes", "Le street food n'est pas représentatif de la vraie culture culinaire"], correct: 1, explanation: "Le street food est la cuisine populaire authentique : recettes transmises de génération en génération, ingrédients locaux de saison, techniques ancestrales non modifiées pour plaire aux touristes. Anthony Bourdain, avant d'être chef célèbre, prônait le street food local comme porte d'entrée la plus honnête dans une culture. Les Guides Michelin ont commencé à récompenser des stands de street food à Singapour en 2016." },
  ],
  tips: ["L'accra de morue antillaise vient du mot yoruba 'akara' (beignet) — lien direct Afrique-Antilles dans la gastronomie", "Penang (Malaisie) est la capitale mondiale du street food — carrefour de 4 cultures culinaires", "Le Pad Thaï a été inventé dans les années 1940 par un gouvernement nationaliste — la politique aussi crée des plats emblématiques"],
};
export default quizStreetFood;
