/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizBresilEssentiel = {
  title: "Brésil — Essentiel Voyage & Culture",
  description: "Droits, règles, culture et bons à savoir avant d'aller au Brésil !",
  emoji: "🇧🇷",
  questions: [
    { question: "🛂 Faut-il un visa pour visiter le Brésil depuis la France ?", answers: ["Oui visa obligatoire", "Non, 90 jours sans visa", "e-Visa obligatoire en ligne", "Carte d'identité suffit"], correct: 1, explanation: "Les ressortissants français n'ont PAS besoin de visa pour le Brésil : séjour touristique libre jusqu'à 90 jours renouvelable une fois (180 jours max par an). Passeport valide 6 mois obligatoire. Décision réciproque de 2019." },
    { question: "💉 Quel vaccin est OBLIGATOIRE pour entrer au Brésil depuis certains pays ?", answers: ["COVID-19", "Fièvre Jaune obligatoire si venant de pays à risque", "Hépatite B", "Paludisme"], correct: 1, explanation: "Le vaccin contre la fièvre jaune est OBLIGATOIRE si vous venez de pays endémiques (Afrique, certains pays d'Amérique du Sud). Recommandé pour voyager dans les régions de forêt amazonienne du Brésil. Carnet de vaccination international exigé." },
    { question: "🌡 Quelle est la saison des pluies à Rio de Janeiro ?", answers: ["Juin-août", "Novembre-mars (été austral)", "Avril-mai uniquement", "Toute l'année également"], correct: 1, explanation: "La saison des pluies au Brésil (été austral) va de novembre à mars avec des pluies tropicales intenses pouvant provoquer des inondations et glissements de terrain à Rio. Le carnaval en février tombe en pleine saison des pluies mais est quand même incontournable." },
    { question: "🏖 Quelle règle de sécurité est absolue sur les plages de Rio de Janeiro ?", answers: ["Ne pas nager seul", "Ne jamais laisser ses affaires sans surveillance — vol quasi certain", "Se baigner uniquement le matin", "Toujours porter un gilet de sauvetage"], correct: 1, explanation: "Sur les plages de Rio, NE JAMAIS laisser sac, téléphone, appareil photo ou objets de valeur sans surveillance, même 30 secondes. Le vol à l'arraché est fréquent. Les Cariocas (habitants de Rio) vont à la plage avec le minimum : serviette, crème, argent liquide minimum." },
    { question: "🗣 Quelle langue parle-t-on au Brésil ?", answers: ["L'espagnol comme dans toute l'Amérique du Sud", "Le portugais brésilien", "Le français en Amazonie", "L'anglais dans les villes"], correct: 1, explanation: "Le Brésil est le seul pays lusophone d'Amérique du Sud. Le portugais brésilien diffère significativement du portugais européen. L'anglais n'est pas largement parlé hors des zones touristiques. Apprendre quelques mots de portugais est très apprécié." },
    { question: "💵 Quelle est la monnaie du Brésil ?", answers: ["Le Dollar brésilien", "Le Real brésilien (BRL)", "Le Peso", "L'Euro"], correct: 1, explanation: "La monnaie brésilienne est le Real (R$, BRL). 1€ vaut environ 5-6 R$. Les cartes de crédit sont largement acceptées dans les villes mais gardez du cash pour les zones rurales et marchés locaux. Les distributeurs sont disponibles partout." },
    { question: "🌿 L'Amazonie brésilienne représente quelle proportion de la forêt tropicale mondiale ?", answers: ["20%", "30%", "50% de la forêt tropicale mondiale", "10%"], correct: 2, explanation: "La forêt amazonienne au Brésil représente 50% de toutes les forêts tropicales restantes sur Terre. Elle produit 20% de l'oxygène mondial et abrite 10% de toutes les espèces connues. Sa déforestation est l'un des enjeux environnementaux majeurs du XXIe siècle." },
    { question: "🎉 Le Carnaval de Rio tombe généralement quand dans l'année ?", answers: ["Décembre-janvier", "Février-mars (avant le Carême catholique)", "Juin-juillet", "Octobre"], correct: 1, explanation: "Le Carnaval de Rio se tient en février ou mars (date variable selon le calendrier catholique — 46 jours avant Pâques). C'est le plus grand carnaval du monde avec 2 millions de participants par jour pendant 5 jours. Réservez hôtels et billets 6 mois à l'avance." },
    { question: "🚕 Comment se déplacer en sécurité dans les grandes villes brésiliennes ?", answers: ["Taxi dans la rue toujours sûr", "Uber et apps de transport officiel uniquement", "Bus de nuit recommandé", "Marche à pied la nuit acceptable"], correct: 1, explanation: "Utilisez UNIQUEMENT Uber, 99 (l'Uber brésilien) ou taxis d'hôtel. Ne hailez jamais un taxi dans la rue, surtout la nuit. Évitez de marcher la nuit dans les zones inconnues. Les favelas ne sont visitables qu'avec des tours organisés et guides locaux de confiance." },
    { question: "⚽ Le Brésil a remporté combien de Coupes du Monde de Football ?", answers: ["3 fois", "4 fois", "5 fois", "6 fois"], correct: 2, explanation: "Le Brésil est le pays le plus titré de l'histoire de la Coupe du Monde avec 5 titres (1958, 1962, 1970, 1994, 2002). Le football est une religion au Brésil. Pelé, Ronaldo, Ronaldinho, Neymar sont des dieux nationaux. Le stade Maracanã de Rio est mythique." },
  ],
  tips: ["Vaccin fièvre jaune obligatoire selon votre pays de provenance", "Ne jamais laisser ses affaires sur les plages de Rio — le vol est quasi certain", "Utilisez Uber uniquement — ne prenez jamais de taxi non identifié dans la rue"],
};
export default quizBresilEssentiel;
