/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizPaysBasEssentiel = {
  title: "Pays-Bas — Essentiel Voyage & Culture",
  description: "Droits, règles, culture et bons à savoir avant d'aller aux Pays-Bas !",
  emoji: "🇳🇱",
  questions: [
    { question: "🚲 Combien de vélos y a-t-il aux Pays-Bas par rapport à la population ?", answers: ["1 vélo pour 2 habitants", "Autant de vélos que d'habitants (23 millions)", "1 vélo pour 10 habitants", "2 vélos par habitant"], correct: 1, explanation: "Les Pays-Bas comptent environ 23 millions de vélos pour 17 millions d'habitants ! Amsterdam a plus de vélos que d'habitants. 27% de tous les déplacements se font à vélo. Attention aux pistes cyclables — ne marchez jamais dessus !" },
    { question: "🌿 Le cannabis est-il légal aux Pays-Bas ?", answers: ["Oui totalement légal", "Toléré dans les coffeeshops (gedoogbeleid), pas légal mais non poursuivi", "Illégal et poursuivi", "Légal seulement à Amsterdam"], correct: 1, explanation: "Le cannabis aux Pays-Bas n'est pas légal mais toléré (gedoogbeleid) dans les coffeeshops agréés. Achat max 5g par personne par jour. La vente dans la rue reste illégale. Depuis 2023, l'accès aux coffeeshops est interdit aux touristes dans plusieurs villes dont Maastricht." },
    { question: "🚲 Que se passe-t-il si vous marchez sur une piste cyclable aux Pays-Bas ?", answers: ["Rien de spécial", "Amende possible + danger réel des cyclistes", "Interdit seulement à Amsterdam", "Toléré pour les touristes"], correct: 1, explanation: "Les pistes cyclables (fietspad) sont sacrées aux Pays-Bas. Les cyclistes ont la priorité et roulent vite (25-30 km/h). Marcher dessus est dangereux et impoli. Les Néerlandais n'hésiteront pas à vous sonner et à vous interpeller vigoureusement !" },
    { question: "💐 Les Pays-Bas sont le premier exportateur mondial de quoi ?", answers: ["Fromage", "Fleurs coupées et bulbes", "Bière", "Chocolat"], correct: 1, explanation: "Les Pays-Bas exportent 52% des fleurs mondiales ! La Hollande est synonyme de tulipes mais exporte aussi roses, lys, orchidées. La criée florale d'Aalsmeer est la plus grande place de commerce du monde par superficie." },
    { question: "🧀 Quel est le fromage le plus célèbre des Pays-Bas exporté dans le monde entier ?", answers: ["Brie", "Edam et Gouda", "Camembert", "Parmesan"], correct: 1, explanation: "Gouda et Edam sont les fromages néerlandais les plus célèbres. Les Pays-Bas exportent 650 000 tonnes de fromage par an. La ville de Gouda organise un marché traditionnel du fromage d'avril à août le jeudi matin." },
    { question: "🌊 Quelle proportion des Pays-Bas se trouve sous le niveau de la mer ?", answers: ["5%", "15%", "26%", "50%"], correct: 2, explanation: "26% du territoire néerlandais est sous le niveau de la mer, dont Amsterdam et Rotterdam. Un réseau de digues (dijken), écluses et pompes gigantesques maintient le pays hors de l'eau. Le Delta Works est considéré comme l'une des 7 merveilles du monde moderne." },
    { question: "🏳️‍🌈 Quel pays a légalisé le mariage homosexuel en premier au monde ?", answers: ["France", "Canada", "Pays-Bas", "Suède"], correct: 2, explanation: "Les Pays-Bas ont été le premier pays au monde à légaliser le mariage homosexuel, le 1er avril 2001. Amsterdam est réputée comme l'une des villes les plus LGBT-friendly au monde avec la Gay Pride annuelle sur les canaux." },
    { question: "🚗 Dans quelle ville néerlandaise les voitures sont-elles quasi bannies du centre-ville ?", answers: ["Rotterdam", "La Haye", "Utrecht", "Amsterdam"], correct: 3, explanation: "Amsterdam a progressivement banni les voitures du centre historique. Des parkings Park & Ride existent en périphérie. La ville est conçue pour les vélos et les tramways. En 2030, Amsterdam veut être 100% zéro émission en centre-ville." },
    { question: "💶 Quel est le salaire minimum aux Pays-Bas en 2024, parmi les plus élevés d'Europe ?", answers: ["10€/heure", "13,27€/heure", "9€/heure", "15€/heure"], correct: 1, explanation: "Le salaire minimum néerlandais (minimumloon) était d'environ 13,27€/heure en 2024, parmi les plus élevés d'Europe. Le coût de la vie à Amsterdam est élevé : loyer, sortie et restaurant sont significativement plus chers qu'en France." },
    { question: "🔴 Qu'est-ce que le Quartier Rouge (De Wallen) à Amsterdam ?", answers: ["Quartier des restaurants gastronomiques", "Zone touristique de la prostitution légale et réglementée", "Marché alimentaire historique", "Quartier des musées"], correct: 1, explanation: "Le Quartier Rouge d'Amsterdam est la zone légale et réglementée de prostitution. Les travailleuses du sexe paient des impôts, ont des droits sociaux et bénéficient de contrôles sanitaires. Les prostituées exercent derrière des vitrines éclairées en rouge." },
  ],
  tips: ["Ne marchez JAMAIS sur les pistes cyclables — danger réel et impolitesse grave", "Le cannabis dans les coffeeshops est toléré mais interdit aux touristes dans certaines villes depuis 2023", "Prévoyez un vélo pour vous déplacer — c'est le mode de transport le plus pratique"],
};
export default quizPaysBasEssentiel;
