const quizUSAEssentiel = {
  title: "USA — Essentiel Voyage & Culture",
  description: "Droits, règles, culture et bons à savoir avant d'aller aux États-Unis !",
  emoji: "🇺🇸",
  questions: [
    { question: "🇺🇸 Faut-il un visa pour visiter les USA depuis la France ou la Guadeloupe ?", answers: ["Oui, visa obligatoire", "Non, ESTA suffit pour 90 jours", "Passeport seul suffit", "Carte d'identité suffit"], correct: 1, explanation: "Les ressortissants français n'ont pas besoin de visa mais doivent obtenir un ESTA (Electronic System for Travel Authorization) avant de partir. Coût : 21$, valable 2 ans, séjour max 90 jours." },
    { question: "💵 Quel est le pourboire standard aux USA dans un restaurant ?", answers: ["5%", "10%", "15 à 20%", "Non obligatoire"], correct: 2, explanation: "Aux USA, le pourboire (tip) de 15 à 20% est une norme sociale très forte. Les serveurs gagnent souvent moins du SMIC car ils comptent sur les tips. Ne pas laisser de pourboire est très mal vu." },
    { question: "🚗 À quel âge peut-on louer une voiture aux USA sans surcharge ?", answers: ["18 ans", "21 ans", "25 ans", "16 ans"], correct: 2, explanation: "La plupart des loueurs américains appliquent des frais supplémentaires pour les conducteurs de moins de 25 ans. Certains refusent même les moins de 21 ans. Prévoyez ce coût extra dans votre budget." },
    { question: "🚬 À quel âge peut-on acheter de l'alcool et du tabac aux USA ?", answers: ["16 ans", "18 ans", "21 ans", "19 ans"], correct: 2, explanation: "Aux USA, l'âge légal pour acheter alcool et tabac est 21 ans dans tous les États. Vous serez systématiquement demandé une pièce d'identité. La loi est très strictement appliquée." },
    { question: "🔫 Dans combien d'États américains est-il légal de porter une arme à feu en public sans permis ?", answers: ["5 États", "15 États", "27 États", "50 États"], correct: 2, explanation: "En 2023, plus de 27 États autorisent le port d'arme en public sans permis (Constitutional Carry). Soyez conscient de cette réalité dans les lieux publics, bars et rues américaines." },
    { question: "🏥 Une hospitalisation d'une nuit aux USA sans assurance peut coûter combien ?", answers: ["500$", "2 000$", "10 000$ ou plus", "Gratuit comme en France"], correct: 2, explanation: "Une nuit d'hôpital aux USA peut coûter 10 000$ à 30 000$ ou plus. Une assurance voyage est ABSOLUMENT indispensable. Ne jamais aller aux USA sans couverture médicale complète." },
    { question: "📱 Quel réseau électrique utilisent les USA ?", answers: ["220V / 50Hz comme en France", "110V / 60Hz", "240V / 50Hz", "110V / 50Hz"], correct: 1, explanation: "Les USA utilisent 110V / 60Hz. Les appareils européens (220V) peuvent être endommagés sans adaptateur/transformateur. La plupart des téléphones et laptops modernes acceptent les deux tensions." },
    { question: "🚔 Que faire si la police vous arrête en voiture aux USA ?", answers: ["Descendre de la voiture immédiatement", "Rester dans la voiture, mains visibles sur le volant", "Appeler un avocat avant de parler", "Montrer passeport seulement"], correct: 1, explanation: "Aux USA : restez dans la voiture, mains visibles sur le volant, ne faites pas de gestes brusques. Dites clairement où se trouve votre permis avant d'y toucher. Ces règles peuvent littéralement vous sauver la vie." },
    { question: "💳 Les taxes sont-elles incluses dans les prix affichés aux USA ?", answers: ["Oui, toujours", "Non, elles s'ajoutent à la caisse", "Seulement dans les supermarchés", "Seulement pour les touristes"], correct: 1, explanation: "Contrairement à l'Europe, les prix affichés aux USA n'incluent PAS les taxes (sales tax). Elles varient de 0% à 10% selon l'État et s'ajoutent au moment de payer. Prévoyez ce surplus." },
    { question: "🌡️ Quelle est la ville la plus chaude des USA en été, pouvant dépasser 50°C ?", answers: ["Miami", "Las Vegas / Phoenix", "Los Angeles", "Houston"], correct: 1, explanation: "Phoenix (Arizona) et Las Vegas (Nevada) peuvent dépasser 45-50°C en juillet-août. La chaleur sèche du désert est dangereuse. Hydratation intensive indispensable, limitez les activités en plein air entre 11h et 17h." },
  ],
  tips: ["ESTA obligatoire avant de partir, se demande sur esta.cbp.dhs.gov", "Assurance médicale voyage indispensable — les soins sont extrêmement chers", "Le tip de 15-20% est une règle sociale, pas une option"],
};
export default quizUSAEssentiel;
