/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizMedecinesDouces = {
  title: "Médecines Douces du Monde",
  description: "Explorez les grandes traditions médicales alternatives reconnues mondialement !",
  emoji: "🏥",
  questions: [
    { question: "Qu'est-ce que l'acupuncture et quel pays l'a développée il y a plus de 2500 ans ?", answers: ["Une technique de massage indien", "L'insertion de fines aiguilles sur des points énergétiques — médecine traditionnelle chinoise reconnue par l'OMS", "Une technique européenne moderne", "Une forme de chirurgie mineure"], correct: 1, explanation: "L'acupuncture est une composante de la Médecine Traditionnelle Chinoise (MTC) vieille de 2500 ans. Elle stimule des points sur des méridiens (canaux d'énergie Qi). L'OMS reconnaît son efficacité pour 28 pathologies : douleurs chroniques, migraines, nausées, addictions. Mécanisme neurologique partiellement expliqué par la libération d'endorphines." },
    { question: "Qu'est-ce que l'Ayurveda, médecine traditionnelle indienne vieille de 5000 ans ?", answers: ["Un régime végétarien indien", "Système médical holistique basé sur les 3 doshas (Vata, Pitta, Kapha) et l'équilibre corps-esprit-âme", "Une forme de yoga médicale", "Une médecine basée uniquement sur les plantes"], correct: 1, explanation: "L'Ayurveda (Inde, 5000 ans) est l'un des systèmes médicaux les plus anciens du monde. Il identifie 3 doshas (constitutions) : Vata (air/espace), Pitta (feu/eau), Kapha (terre/eau). La maladie = déséquilibre des doshas. Traitement : alimentation, plantes (ashwagandha, triphala), yoga, méditation, panchakarma (détox). Reconnu par l'OMS." },
    { question: "Comment fonctionne l'ostéopathie et pour quelles pathologies est-elle efficace ?", answers: ["Uniquement pour les maux de dos", "Manipulation des structures musculo-squelettiques pour restaurer la mobilité et l'auto-guérison — efficace pour douleurs chroniques, troubles fonctionnels", "Technique chirurgicale non invasive", "Médecine basée sur les médicaments naturels"], correct: 1, explanation: "L'ostéopathie (Andrew Taylor Still, 1874) : le corps a la capacité de s'auto-guérir si les structures sont libres. Les manipulations ostéopathiques restaurent la mobilité articulaire et tissulaire. Efficacité prouvée : lombalgies, cervicalgies, céphalées de tension, troubles digestifs fonctionnels, troubles du sommeil. Remboursée partiellement par certaines mutuelles." },
    { question: "Qu'est-ce que la médecine traditionnelle créole des Antilles et comment a-t-elle survécu à l'esclavage ?", answers: ["Une médecine récente créée au XXe siècle", "Un système de soins transmis oralement depuis l'Afrique, enrichi de plantes caribéennes, pratiqué par les guérisseurs créoles", "Uniquement la médecine des békés", "Une branche de la médecine française"], correct: 1, explanation: "La médecine créole antillaise est un héritage africain transmis oralement et enrichi de plantes locales. Les esclaves, privés de médecins, ont maintenu leurs savoirs médicinaux africains et les ont adaptés aux plantes des Caraïbes. Les 'gadédzafè' (guérisseurs) et 'manman fey' (plantes médicinales) restent une pratique vivante en Guadeloupe et Martinique." },
    { question: "Qu'est-ce que l'homéopathie et pourquoi est-elle controversée scientifiquement ?", answers: ["Une médecine par les plantes concentrées", "Traitement par substances ultra-diluées censées stimuler l'auto-guérison — efficacité non prouvée au-delà du placebo selon la majorité des études", "Une médecine ayurvédique indienne", "Un traitement par les aliments"], correct: 1, explanation: "L'homéopathie (Samuel Hahnemann, 1796) : 'le semblable guérit le semblable' par dilutions extrêmes. Les dilutions CH30 ne contiennent plus aucune molécule active (loi d'Avogadro). La Haute Autorité de Santé française a conclu en 2019 à une efficacité non prouvée et a déremboursé l'homéopathie en 2021. L'effet placebo est réel et puissant." },
    { question: "Quelle médecine traditionnelle africaine est encore pratiquée aux Antilles et inclut rituels, plantes et dimension spirituelle ?", answers: ["L'homéopathie africaine", "La médecine des griots, guérisseurs et le Quimbois — dimension spirituelle, plantes et rituels indissociables", "L'acupuncture africaine", "La médecine du désert touareg uniquement"], correct: 1, explanation: "Le Quimbois aux Antilles (surtout Martinique) est un système de soins et de protection mêlant plantes médicinales, rituels africains et dimension spirituelle. Le guérisseur (quimboiseur) traite à la fois le corps, l'esprit et les liens sociaux. Malgré la stigmatisation coloniale, cette pratique survit et est reconnue comme patrimoine culturel." },
    { question: "Qu'est-ce que la réflexologie plantaire et sur quel principe repose-t-elle ?", answers: ["Un massage des pieds uniquement relaxant", "La stimulation de zones réflexes des pieds correspondant à des organes et systèmes du corps", "Une technique de chirurgie des pieds", "Un diagnostic par les pieds uniquement"], correct: 1, explanation: "La réflexologie plantaire repose sur le principe que les pieds contiennent des zones réflexes correspondant à tous les organes et systèmes du corps. La stimulation de ces zones stimulerait la circulation énergétique et l'auto-guérison. Effets prouvés : relaxation, réduction du stress et de l'anxiété, amélioration du sommeil." },
    { question: "Qu'est-ce que la naturopathie et ses 6 grandes modalités thérapeutiques ?", answers: ["Uniquement la médecine par les plantes", "Approche holistique utilisant alimentation, plantes, hydrologie, exercice, psychologie et techniques manuelles pour stimuler la vitalité", "Une forme d'ostéopathie", "La médecine de prévention uniquement"], correct: 1, explanation: "La naturopathie (médecine naturelle) utilise 6 modalités : 1. Alimentation vivante, 2. Phytothérapie, 3. Hydrothérapie (eau froide/chaude), 4. Exercice physique, 5. Gestion du stress et psychologie, 6. Techniques manuelles. Philosophie : stimuler la vis medicatrix naturae (force vitale naturelle) plutôt que de combattre le symptôme." },
    { question: "La méditation de pleine conscience est-elle reconnue médicalement ?", answers: ["Non, uniquement pratique spirituelle", "Oui — protocole MBSR reconnu en médecine pour anxiété, dépression, douleur chronique et prévention des rechutes dépressives", "Uniquement en psychiatrie aux USA", "Reconnue mais non pratiquée en France"], correct: 1, explanation: "Le MBSR (Mindfulness-Based Stress Reduction, Kabat-Zinn) et le MBCT (thérapie cognitive basée sur la pleine conscience) sont reconnus médicalement. Le MBCT est recommandé par le NHS britannique pour la prévention des rechutes dépressives. Des centaines d'hôpitaux intègrent la méditation dans les protocoles de soins (douleur chronique, cancer, maladies cardiovasculaires)." },
    { question: "Qu'est-ce que la balnéothérapie thermale et pourquoi les Antilles ont-elles un potentiel exceptionnel ?", answers: ["Uniquement des bains de boue", "Thérapie par les eaux thermales minérales — les Antilles ont des sources chaudes volcaniques uniques", "Un spa de luxe uniquement", "Une technique uniquement européenne"], correct: 1, explanation: "La balnéothérapie utilise les propriétés thérapeutiques des eaux thermales (minéraux, température, pression). Les Antilles volcaniques (Guadeloupe, Martinique, Dominique, Montserrat) possèdent des sources thermales naturelles riches en soufre, magnésium et minéraux aux propriétés anti-inflammatoires, cutanées et respiratoires reconnues." },
  ],
  tips: ["La médecine créole antillaise est un patrimoine de savoirs africains précieux transmis depuis l'esclavage", "L'OMS reconnaît l'acupuncture efficace pour 28 pathologies — dont les douleurs chroniques", "Médecines douces et médecine conventionnelle sont complémentaires — informez toujours votre médecin"],
};
export default quizMedecinesDouces;
