/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizCanadaEssentiel = {
  title: "Canada — Essentiel Voyage & Culture",
  description: "Droits, règles, culture et bons à savoir avant d'aller au Canada !",
  emoji: "🇨🇦",
  questions: [
    { question: "🛂 Faut-il un visa ou une AVE pour visiter le Canada depuis la France ?", answers: ["Visa obligatoire", "AVE (Autorisation de Voyage Électronique) obligatoire", "Passeport seul suffit", "Carte d'identité suffit"], correct: 1, explanation: "Les ressortissants français doivent obtenir une AVE (Autorisation de Voyage Électronique) avant de prendre l'avion pour le Canada. Coût : 7 CAD, valable 5 ans. À demander sur le site officiel du gouvernement canadien." },
    { question: "🌡 Quelle température peut-il faire à Montréal en hiver ?", answers: ["0°C maximum", "-10°C à -30°C régulièrement", "-5°C maximum", "Jamais moins de -15°C"], correct: 1, explanation: "Montréal peut connaître des températures de -20°C à -30°C en janvier-février, avec un vent qui les fait ressentir jusqu'à -40°C. Équipement hivernal indispensable : manteau -40°C, bottes imperméables, gants, cache-oreilles." },
    { question: "🍁 Combien de provinces et territoires compte le Canada ?", answers: ["5 provinces", "10 provinces et 3 territoires", "12 régions", "8 provinces"], correct: 1, explanation: "Le Canada compte 10 provinces (Ontario, Québec, Colombie-Britannique...) et 3 territoires (Yukon, Territoires du Nord-Ouest, Nunavut). Chaque province a ses propres lois, taxes et règles — comme des petits pays différents." },
    { question: "🌿 Dans quelles provinces canadiennes le cannabis est-il légal ?", answers: ["Seulement en Colombie-Britannique", "Uniquement au Québec", "Dans tout le Canada depuis 2018", "Illégal partout au Canada"], correct: 2, explanation: "Le Canada a légalisé le cannabis récréatif dans tout le pays le 17 octobre 2018, deuxième pays au monde après l'Uruguay. Chaque province réglemente l'âge minimum (18-19 ans), les lieux de vente et de consommation." },
    { question: "💵 Le Canada utilise-t-il le dollar américain ?", answers: ["Oui, même monnaie", "Non, dollar canadien (CAD) distinct", "Les deux sont acceptés", "L'euro dans certaines régions"], correct: 1, explanation: "Le Canada utilise le dollar canadien (CAD ou $), distinct du dollar américain (USD). 1 USD vaut environ 1,35 CAD. Bien que les USD soient parfois acceptés près de la frontière, les prix sont toujours en CAD." },
    { question: "🏥 La santé est-elle gratuite pour les touristes au Canada ?", answers: ["Oui, comme en France", "Non, assurance voyage obligatoire", "Gratuit seulement pour francophones", "Gratuit aux urgences seulement"], correct: 1, explanation: "La santé est gratuite pour les RÉSIDENTS canadiens uniquement. Les touristes paient plein tarif : une consultation d'urgence peut coûter 500 à 5 000 CAD. Assurance voyage OBLIGATOIRE avant de partir." },
    { question: "🚗 À quelle vitesse maximum peut-on rouler sur les autoroutes canadiennes ?", answers: ["100 km/h", "110 km/h", "120 km/h", "90 km/h"], correct: 1, explanation: "La limite maximale sur les autoroutes canadiennes est généralement 100-110 km/h selon les provinces. En Ontario : 100 km/h. En Colombie-Britannique : 110 km/h. Beaucoup moins qu'en Europe. Les radars sont fréquents." },
    { question: "🗣 Le Québec est la seule province officiellement francophone. Quelle loi protège le français ?", answers: ["Loi sur les langues officielles", "Loi 101 (Charte de la langue française)", "Constitution canadienne", "Traité de Paris"], correct: 1, explanation: "La Loi 101 (1977), adoptée par le Parti Québécois de René Lévesque, fait du français la seule langue officielle du Québec. Affichage commercial en français obligatoire, travail en français, scolarité en français pour immigrants." },
    { question: "🐻 Que faire en cas de rencontre avec un ours noir en randonnée au Canada ?", answers: ["Courir le plus vite possible", "Faire le mort", "Parler calmement, reculer lentement, sembler grand", "Grimper à un arbre"], correct: 2, explanation: "Face à un ours noir : parlez calmement, reculez lentement sans tourner le dos, faites-vous paraître grand. Ne courez JAMAIS (instinct de poursuite). Portez une bombe anti-ours en randonnée. Les attaques sont rares mais réelles." },
    { question: "🌊 Le Canada possède combien de kilomètres de côtes, le plus long littoral au monde ?", answers: ["20 000 km", "60 000 km", "202 080 km", "100 000 km"], correct: 2, explanation: "Le Canada possède 202 080 km de côtes, le plus long littoral au monde ! Il borde trois océans : Pacifique, Atlantique et Arctique. Ce territoire immense contient 20% des eaux douces mondiales." },
  ],
  tips: ["AVE obligatoire avant l'avion — à demander sur canada.ca", "Assurance voyage indispensable — la santé n'est pas gratuite pour les touristes", "Préparez des vêtements pour -30°C si vous visitez en hiver"],
};
export default quizCanadaEssentiel;
