/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizReves = {
  title: "Rêves & Leur Interprétation",
  description: "Plongez dans le monde fascinant des rêves — significations, symboles et messages de l'inconscient !",
  emoji: "🌙",
  questions: [
    { question: "Combien d'heures par jour l'être humain rêve-t-il en moyenne ?", answers: ["30 minutes", "2 heures", "4 à 6 heures", "8 heures"], correct: 1, explanation: "On rêve environ 2 heures par nuit, réparties en 4 à 6 cycles de rêves. La phase de rêves (REM - Rapid Eye Movement) dure de 20 à 90 minutes et se rallonge au cours de la nuit. On oublie 95% de ses rêves dans les 5 minutes après le réveil." },
    { question: "Que symbolise généralement tomber dans un rêve selon l'interprétation psychologique ?", answers: ["Chance imminente", "Perte de contrôle dans la vie éveillée, insécurité, anxiété face à une situation", "Voyage à venir", "Mort symbolique uniquement"], correct: 1, explanation: "Tomber dans un rêve est l'un des rêves les plus universels. Il symbolise souvent une perte de contrôle, une insécurité face à une situation professionnelle ou personnelle, ou une transition difficile. Le contexte du rêve précise le domaine concerné." },
    { question: "Qu'est-ce qu'un rêve lucide ?", answers: ["Un rêve très réaliste", "Un état où le rêveur sait qu'il rêve et peut potentiellement contrôler le rêve", "Un rêve prémonitoire", "Un souvenir du rêve très détaillé"], correct: 1, explanation: "Un rêve lucide est un état de conscience où le dormeur réalise qu'il est en train de rêver. Des techniques (WILD, MILD, DILD) permettent d'induire cet état. Dans un rêve lucide, on peut parfois contrôler les événements. Les armées et des entreprises étudient cette technique." },
    { question: "Que représente rêver de ses dents qui tombent, l'un des rêves les plus répandus au monde ?", answers: ["Problèmes dentaires à venir", "Anxiété, peur du jugement des autres, crainte de perdre son pouvoir ou son attractivité", "Chance au jeu", "Signe de bonne santé"], correct: 1, explanation: "Rêver de dents qui tombent est l'un des rêves les plus universellement partagés. Il symbolise l'anxiété sociale, la peur d'être jugé, la crainte de perdre son image ou son pouvoir. Certaines cultures y voient un présage de mort dans la famille." },
    { question: "Selon Carl Jung, que représentent les personnages qui poursuivent le rêveur dans ses cauchemars ?", answers: ["Des ennemis réels", "L'Ombre — les aspects refoulés et non acceptés de notre propre personnalité", "Des esprits malveillants", "Des traumatismes physiques"], correct: 1, explanation: "Carl Jung appelait 'l'Ombre' les parties de notre personnalité que nous refusons de reconnaître ou que nous avons refoulées. Ces aspects non intégrés apparaissent dans les rêves comme des poursuivants menaçants. L'intégration de l'Ombre est centrale dans la psychologie jungienne." },
    { question: "Que signifie rêver de voler librement dans les airs ?", answers: ["Danger imminent", "Désir de liberté, de s'élever au-dessus des problèmes, confiance en soi et ambitions élevées", "Voyage en avion prochain", "Peur des hauteurs refoulée"], correct: 1, explanation: "Voler dans un rêve est généralement positif : liberté, élévation spirituelle, désir de s'affranchir des contraintes terrestres. Si le vol est difficile ou qu'on tombe, cela peut indiquer des obstacles à cette liberté. Rêver de voler est souvent associé aux périodes de créativité intense." },
    { question: "Qu'est-ce que la technique du journal de rêves recommandée par tous les spécialistes ?", answers: ["Enregistrer ses rêves en vidéo", "Noter ses rêves immédiatement au réveil pour mieux les mémoriser et les analyser", "Partager ses rêves sur internet", "Ne jamais noter ses rêves pour ne pas les amplifier"], correct: 1, explanation: "Le journal de rêves consiste à noter ses rêves immédiatement au réveil (stylo et carnet sur la table de nuit). En 3-4 semaines, le cerveau développe une meilleure mémoire onirique. Les thèmes récurrents deviennent visibles et permettent une analyse de fond." },
    { question: "Les recherches scientifiques ont prouvé que les rêves servent à quoi principalement ?", answers: ["À rien — activité aléatoire du cerveau", "Consolidation de la mémoire, traitement émotionnel des expériences et résolution créative de problèmes", "Prédire l'avenir", "Communiquer avec les ancêtres"], correct: 1, explanation: "Les neurosciences ont prouvé que les rêves (phase REM) jouent un rôle crucial dans : la consolidation des souvenirs et apprentissages, le traitement émotionnel des événements difficiles, et la résolution créative de problèmes. Paul McCartney a composé 'Yesterday' après l'avoir entendu en rêve." },
    { question: "Dans quelle tradition les rêves sont-ils considérés comme des messages des ancêtres ou des dieux ?", answers: ["Dans aucune tradition", "Dans de nombreuses traditions africaines, amérindiennes, et dans l'Égypte antique", "Seulement en psychanalyse moderne", "Uniquement dans la tradition chrétienne"], correct: 1, explanation: "Dans les traditions africaines, amérindiennes, hawaïennes, égyptiennes et bien d'autres, les rêves sont des espaces sacrés de communication avec les ancêtres, les guides spirituels et les divinités. Les chamanes utilisent des rêves intentionnels (voyage chamanique) pour obtenir des guérisons et des enseignements." },
    { question: "Que signifie rêver d'eau, l'un des symboles oniriques les plus universels ?", answers: ["La richesse matérielle"], correct: 0, explanation: "L'eau en rêve représente l'inconscient et les émotions. Eau calme = paix intérieure. Eau turbulente = émotions débordantes. Noyade = être submergé par les émotions. Eau claire = clarté mentale. Pluie = renouveau et purification. La signification varie selon l'état de l'eau dans le rêve.", answers: ["L'inconscient et les émotions — calme ou turbulente selon l'état psychologique", "La richesse matérielle uniquement", "Les voyages en bateau à venir", "Le manque de sommeil"], correct: 0 },
  ],
  tips: ["Posez un carnet et stylo sur votre table de nuit — notez vos rêves dans les 3 premières minutes au réveil", "Les rêves récurrents sont les plus importants — ils portent un message que l'inconscient veut transmettre", "Paul McCartney, Einstein et Mendeleïev ont eu des intuitions majeures en rêve"],
};
export default quizReves;
