/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizIndeEssentiel = {
  title: "Inde — Essentiel Voyage & Culture",
  description: "Droits, règles, culture et bons à savoir avant d'aller en Inde !",
  emoji: "🇮🇳",
  questions: [
    { question: "🛂 Faut-il un visa pour visiter l'Inde depuis la France ?", answers: ["Non, passeport suffit", "Oui, e-Visa obligatoire en ligne", "Visa ambassade uniquement", "Carte d'identité suffit"], correct: 1, explanation: "Un e-Visa (Tourist e-Visa) est obligatoire pour les Français avant de partir en Inde. Demande en ligne sur indianvisaonline.gov.in, coût 25 USD, validité 1 an, max 90 jours par séjour. À demander au moins 4 jours avant le départ." },
    { question: "🐄 Pourquoi ne faut-il JAMAIS insulter ou toucher irrespecteusement une vache en Inde ?", answers: ["Elles sont dangereuses", "La vache est sacrée dans l'hindouisme — risque d'emprisonnement", "Elles appartiennent au gouvernement", "Simple superstition locale"], correct: 1, explanation: "La vache est sacrée dans l'hindouisme (80% de la population indienne). Dans de nombreux États, tuer, maltraiter ou exporter du bœuf est illégal avec des peines de prison. Les vaches se promènent librement dans les rues." },
    { question: "🤝 Comment salue-t-on respectueusement en Inde ?", answers: ["Bise sur la joue", "Poignée de main ferme", "Namaste (mains jointes devant le cœur)", "Inclination de tête japonaise"], correct: 2, explanation: "Le Namaste (mains jointes devant le cœur, légère inclinaison) est le salut traditionnel indien respectueux. Évitez de serrer la main de femmes indiennes sauf si elles vous tendent la main en premier. Le respect des codes sociaux est essentiel." },
    { question: "💉 Quels vaccins sont recommandés avant de partir en Inde ?", answers: ["Aucun vaccin nécessaire", "Hépatite A, Typhoïde, DTP, et selon régions : fièvre jaune, rage", "Seulement le COVID", "Vaccin contre le paludisme uniquement"], correct: 1, explanation: "Vaccins recommandés pour l'Inde : Hépatite A, Typhoïde, DTP (Diphtérie-Tétanos-Polio). Selon les régions : antipaludéen (médicament préventif), rage si activités outdoor. Consultez un médecin du voyage au moins 6 semaines avant." },
    { question: "🚰 L'eau du robinet est-elle potable en Inde pour les touristes étrangers ?", answers: ["Oui, partout en Inde", "Non — eau en bouteille uniquement, même pour se brosser les dents", "Potable dans les grandes villes uniquement", "Potable après ébullition seulement"], correct: 1, explanation: "NE JAMAIS boire l'eau du robinet en Inde, même dans les hôtels 5 étoiles. Utilisez UNIQUEMENT de l'eau en bouteille scellée, même pour vous brosser les dents. Évitez les glaçons dans les restaurants locaux et les crudités lavées à l'eau locale." },
    { question: "👗 Quelle tenue vestimentaire est respectueuse dans les temples indiens ?", answers: ["Tenue de plage acceptée", "Épaules, bras et genoux couverts + enlever les chaussures", "Tenue de sport acceptable", "Aucune règle vestimentaire"], correct: 1, explanation: "Dans les temples hindous, sikhs, mosquées et sites sacrés : épaules couvertes, genoux couverts, chaussures enlevées à l'entrée. Certains temples refusent les non-hindous. Apportez toujours un foulard ou étole." },
    { question: "🌶️ L'Inde est le premier producteur mondial de quelle épice ?", answers: ["Curcuma", "Safran", "Piment", "Cannelle"], correct: 2, explanation: "L'Inde produit 90% du piment mondial ! Elle est aussi premier producteur de curcuma, cardamome et nombreuses épices. La cuisine indienne varie radicalement selon les régions : du très épicé au doux selon les États." },
    { question: "💊 Que faire en cas de diarrhée du voyageur (tourista) en Inde ?", answers: ["Manger épicé pour tuer les bactéries", "Antidiarrhéiques + réhydratation + consulter si fièvre", "Ne rien faire, ça passe seul", "Boire de l'eau locale pour s'habituer"], correct: 1, explanation: "La tourista affecte 30-70% des voyageurs en Inde. Emportez : Imodium, Smecta, sels de réhydratation. Si fièvre ou sang dans les selles, consultez un médecin. Évitez les aliments crus, glaces artisanales, jus de fruits frais des vendeurs de rue." },
    { question: "🕌 Quelle est la religion pratiquée par environ 80% de la population indienne ?", answers: ["Islam", "Bouddhisme", "Hindouisme", "Christianisme"], correct: 2, explanation: "80% des 1,4 milliard d'Indiens sont hindous, faisant de l'Inde le pays avec la plus grande population hindoue au monde. L'Inde compte aussi 200 millions de musulmans (2ème population mondiale), 28 millions de chrétiens, 20 millions de sikhs." },
    { question: "🚕 Comment éviter les arnaques en taxi à Delhi ou Mumbai ?", answers: ["Toujours accepter le prix proposé", "Utiliser Uber/Ola ou insister pour le compteur", "Négocier à 50% du prix", "Prendre uniquement les taxis blancs officiels"], correct: 1, explanation: "Les applications Uber et Ola (l'Uber indien) sont les plus sûres avec prix fixe. En taxi traditionnel, insistez toujours pour le compteur (meter). Les conducteurs à l'aéroport proposent souvent des prix 3-5 fois supérieurs aux touristes." },
  ],
  tips: ["e-Visa obligatoire — à demander sur indianvisaonline.gov.in minimum 4 jours avant", "Ne jamais boire l'eau du robinet — eau en bouteille scellée uniquement", "Vaccins Hépatite A et Typhoïde recommandés — consultez un médecin du voyage"],
};
export default quizIndeEssentiel;
