/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizCuisineAntillaise = {
  title: "Cuisine Antillaise",
  description: "Découvrez les saveurs et les spécialités culinaires des Antilles !",
  emoji: "🥘",
  questions: [
    { question: "🥘 Quel est le plat national de la Guadeloupe ?", answers: ["Le boudin créole", "Le colombo de poulet", "Le court-bouillon de poisson", "La bokit"], correct: 1, explanation: "Le colombo, épice arrivée avec les travailleurs indiens au XIXe siècle, est devenu un symbole de la cuisine guadeloupéenne. Le colombo de poulet, cabri ou porc est incontournable lors des fêtes et réunions familiales." },
    { question: "🌶️ Quel piment emblématique des Antilles est l'un des plus forts au monde ?", answers: ["Le piment doux", "Le piment végétarien", "Le piment antillais (Habanero/Scotch Bonnet)", "Le poivre noir"], correct: 2, explanation: "Le piment antillais (cousin du Scotch Bonnet et Habanero) est l'un des piments les plus forts au monde avec 100 000 à 350 000 Scoville. Il est indispensable dans la cuisine créole mais doit être utilisé avec parcimonie !" },
    { question: "🐟 Qu'est-ce que l'accras de morue ?", answers: ["Un dessert sucré", "Des beignets frits à base de morue dessalée et de farine — l'apéritif antillais par excellence", "Un plat de résistance", "Une boisson traditionnelle"], correct: 1, explanation: "Les accras de morue sont LE symbole de l'apéritif antillais. Ces petits beignets croustillants à base de morue, farine, œuf, oignons et piment sont présents dans toutes les fêtes, mariages et réunions de famille." },
    { question: "🥤 Qu'est-ce que le shrub ?", answers: ["Un cocktail américain", "Une boisson traditionnelle antillaise à base de rhum, de cédrat (citron vert) et d'aromates", "Un jus de fruits tropical", "Une bière locale"], correct: 1, explanation: "Le shrub est une liqueur traditionnelle des fêtes de Noël aux Antilles, préparée avec du rhum blanc, du cédrat ou citron vert et d'autres épices. Sa préparation se transmet de génération en génération." },
    { question: "🍌 Quel fruit est au cœur de nombreux plats salés antillais ?", answers: ["La mangue", "L'ananas", "Le fruit à pain (le chadec)", "La banane plantain"], correct: 3, explanation: "La banane plantain (à ne pas confondre avec la banane douce) est un incontournable de la cuisine antillaise. Frite, bouillie ou en gratin, elle accompagne viandes, poissons et est la base du 'matété' de crabes." },
    { question: "🦀 Quel plat traditionnel est préparé lors du week-end de Pâques en Guadeloupe ?", answers: ["Le poulet boucané", "Le matété de crabes", "Le blaff de poisson", "Le gratin de christophine"], correct: 1, explanation: "Le matété de crabes est le plat traditionnel du week-end de Pâques en Guadeloupe. Ce riz cuisiné avec des crabes de terre est préparé en famille et représente un moment convivial fort de la culture guadeloupéenne." },
  ],
  tips: ["🥘 La cuisine antillaise reflète l'histoire de la Guadeloupe — influences africaines, indiennes, européennes et amérindiennes", "🌶️ Le secret : le piment et le bois d'inde (poivre jamaïcain) dans presque tous les plats", "🍹 Le rhum agricole guadeloupéen est classé AOC — une fierté locale mondiale"],
};
export default quizCuisineAntillaise;
