/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizJeuxVideo = {
  title: "Jeux Vidéo",
  description: "Testez vos connaissances sur l'univers du gaming !",
  emoji: "🎮",
  questions: [
    { question: "🎮 Quelle est l'industrie du jeu vidéo en valeur annuelle comparée au cinéma et à la musique ?", answers: ["Plus petite que les deux", "Environ la même taille", "Plus grande que le cinéma et la musique réunis", "Deux fois plus petite que le cinéma"], correct: 2, explanation: "L'industrie du jeu vidéo génère plus de 200 milliards de dollars annuellement, dépassant largement Hollywood (environ 90 milliards) et la musique (environ 26 milliards) combinés. C'est l'industrie culturelle la plus lucrative au monde." },
    { question: "🍄 Quel personnage Nintendo est le plus reconnu au monde ?", answers: ["Link", "Pikachu", "Mario", "Donkey Kong"], correct: 2, explanation: "Mario est le personnage de jeu vidéo le plus reconnu mondialement. Créé par Shigeru Miyamoto, il est apparu pour la première fois dans Donkey Kong en 1981. La franchise Mario est la plus vendue de l'histoire des jeux vidéo." },
    { question: "🏆 Qu'est-ce que l'e-sport ?", answers: ["Un sport joué avec des équipements électroniques", "La compétition professionnelle de jeux vidéo avec des tournois, des équipes et des prix pouvant atteindre des millions de dollars", "Un jeu d'arcade", "Les Jeux Olympiques virtuels"], correct: 1, explanation: "L'e-sport est la compétition professionnelle de jeux vidéo. Les tournois comme le Mondial de League of Legends ou The International (Dota 2) remplissent des stades et diffusent des prize pools de dizaines de millions de dollars. Les meilleurs joueurs gagnent des millions." },
    { question: "🌍 Quel jeu a battu des records de popularité mondiale pendant le confinement COVID-19 ?", answers: ["Minecraft", "Among Us et Animal Crossing", "GTA V", "FIFA 21"], correct: 1, explanation: "Animal Crossing: New Horizons (Nintendo) et Among Us ont explosé pendant les confinements de 2020. Among Us, sorti en 2018 dans l'indifférence, est devenu viral avec des millions de joueurs simultanés et des streams Twitch record." },
    { question: "📱 Quel est le jeu mobile le plus téléchargé de tous les temps ?", answers: ["Clash of Clans", "PUBG Mobile", "Subway Surfers ou Candy Crush", "Pokémon GO"], correct: 2, explanation: "Subway Surfers et Candy Crush se disputent la première place des jeux mobiles les plus téléchargés de l'histoire avec des milliards de téléchargements. Pokémon GO a été un phénomène culturel unique en 2016." },
    { question: "🎲 Qu'est-ce qu'un jeu 'open world' ?", answers: ["Un jeu sans règles", "Un jeu dans lequel le joueur peut explorer librement un vaste monde virtuel à son rythme", "Un jeu multijoueur", "Un jeu sans fin définie"], correct: 1, explanation: "Un jeu open world (monde ouvert) offre une liberté d'exploration totale. GTA, The Legend of Zelda: Breath of the Wild, Minecraft et Elden Ring en sont des exemples. Le joueur choisit ses objectifs et explore sans couloir imposé." },
  ],
  tips: ["🎮 Le gaming développe des compétences réelles : stratégie, travail d'équipe, résolution de problèmes", "💡 L'industrie du jeu vidéo offre des carrières passionnantes : développement, design, e-sport, streaming", "🌍 Le gaming connecte les jeunes de la diaspora aux mêmes univers culturels"],
};
export default quizJeuxVideo;
