/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizFinancesPersonnelles = {
  title: "Finances Personnelles & Liberté Financière",
  description: "Maîtrisez votre argent, construisez votre patrimoine et atteignez la liberté financière !",
  emoji: "💰",
  questions: [
    { question: "Qu'est-ce que la règle des 50-30-20 pour gérer son budget ?", answers: ["Épargner 50%, dépenser 30%, investir 20%", "50% besoins essentiels, 30% désirs, 20% épargne et investissement", "50% logement, 30% nourriture, 20% loisirs", "50% pour l'État, 30% pour soi, 20% pour la famille"], correct: 1, explanation: "La règle 50-30-20 (Elizabeth Warren) : 50% du revenu net pour les besoins (loyer, nourriture, transport), 30% pour les envies (loisirs, restaurants, voyages), 20% pour l'épargne et le remboursement de dettes. Simple et applicable immédiatement pour reprendre le contrôle de ses finances." },
    { question: "Qu'est-ce que l'intérêt composé, surnommé la 8ème merveille du monde par Einstein ?", answers: ["Les intérêts que la banque prend sur votre compte", "Les intérêts qui génèrent eux-mêmes des intérêts — l'argent qui travaille et se multiplie exponentiellement", "Un type de prêt immobilier avantageux", "Un bonus bancaire annuel"], correct: 1, explanation: "L'intérêt composé : vos intérêts génèrent eux-mêmes des intérêts. 1 000€ à 7%/an → 2 000€ en 10 ans, 4 000€ en 20 ans, 8 000€ en 30 ans (sans rien ajouter). La règle des 72 : divisez 72 par le taux d'intérêt = nombre d'années pour doubler votre capital. À 6% : 72/6 = 12 ans pour doubler." },
    { question: "Selon Robert Kiyosaki (Père Riche Père Pauvre), quelle est la différence entre un actif et un passif ?", answers: ["Un actif vaut plus qu'un passif", "Un actif met de l'argent dans votre poche, un passif en sort", "Les actifs sont les économies, les passifs les dettes", "Un actif appartient à la banque, un passif vous appartient"], correct: 1, explanation: "Kiyosaki définit : un ACTIF = quelque chose qui génère des revenus (immeuble locatif, actions à dividendes, business). Un PASSIF = quelque chose qui coûte de l'argent (voiture de luxe, maison principale selon lui). Les riches accumulent des actifs, les classes moyennes accumulent des passifs qu'ils croient être des actifs." },
    { question: "Qu'est-ce qu'un fonds d'urgence et quel montant est recommandé ?", answers: ["Un prêt bancaire d'urgence", "L'épargne couvrant 3 à 6 mois de dépenses — liquidité immédiate pour les imprévus", "Une assurance vie", "Un compte épargne bloqué à 10 ans"], correct: 1, explanation: "Le fonds d'urgence est la base de toute sécurité financière : 3 à 6 mois de dépenses mensuelles en épargne liquide (livret A, compte courant). Il protège contre les imprévus (perte d'emploi, réparation voiture, santé) sans s'endetter. À constituer AVANT tout investissement." },
    { question: "Qu'est-ce que la diversification de portefeuille et pourquoi est-elle essentielle ?", answers: ["Avoir de l'argent dans plusieurs banques", "Répartir ses investissements entre différentes classes d'actifs pour réduire le risque global", "Investir uniquement en bourse", "Changer d'investissements régulièrement"], correct: 1, explanation: "La diversification ('ne pas mettre tous ses œufs dans le même panier') réduit le risque sans réduire le rendement attendu. Harry Markowitz (Nobel d'économie) a prouvé mathématiquement que diversifier entre actifs peu corrélés (actions, obligations, immobilier, or) améliore le ratio rendement/risque." },
    { question: "Qu'est-ce que la règle des 4% pour la retraite/liberté financière (FIRE) ?", answers: ["Épargner 4% de son salaire", "Avec un patrimoine de 25x ses dépenses annuelles, retirer 4% par an permet de vivre à vie sans travailler", "Investir dans des produits à 4% de rendement garanti", "Payer 4% d'impôts sur ses investissements"], correct: 1, explanation: "La règle des 4% (étude Trinity, 1998) : si votre patrimoine = 25x vos dépenses annuelles, retirer 4%/an permet statistiquement de ne jamais épuiser votre capital sur 30 ans. Ex: dépenses de 2 000€/mois = 24 000€/an → capital nécessaire = 600 000€. Base du mouvement FIRE (Financial Independence, Retire Early)." },
    { question: "Qu'est-ce qu'un ETF (tracker) et pourquoi les recommandent la plupart des experts financiers ?", answers: ["Un compte bancaire à terme", "Un fonds indiciel qui réplique un indice (ex: CAC40, S&P500) avec frais très bas et diversification automatique", "Une action d'entreprise technologique", "Un investissement immobilier collectif"], correct: 1, explanation: "Un ETF (Exchange-Traded Fund) réplique passivement un indice boursier. Avantages : frais très bas (0,07-0,20% vs 1-2% pour fonds actifs), diversification immédiate, liquidité. Historiquement, 90% des fonds gérés activement sous-performent les ETF indiciels sur 15 ans. Warren Buffett recommande les ETF S&P500 pour la majorité des gens." },
    { question: "Quelle est la différence entre revenu actif et revenu passif ?", answers: ["Le revenu actif est plus élevé", "Revenu actif = échangez du temps contre de l'argent. Revenu passif = l'argent travaille pour vous même quand vous dormez", "Le revenu passif est illégal", "Il n'y a pas de différence réelle"], correct: 1, explanation: "Revenu actif : vous vendez votre temps (salaire, freelance). S'arrête quand vous vous arrêtez. Revenu passif : loyers, dividendes, royalties, revenus d'affiliation Amazon comme REUSSITESS®971. Continue même quand vous dormez. L'objectif de la liberté financière est que vos revenus passifs dépassent vos dépenses." },
    { question: "Que signifie le terme 'effet de levier' dans l'investissement immobilier ?", answers: ["Vendre rapidement pour faire une plus-value", "Utiliser l'argent de la banque (crédit) pour acheter un bien générant plus que le coût du crédit", "Rénover un bien pour l'améliorer", "Négocier le prix d'achat à la baisse"], correct: 1, explanation: "L'effet de levier : emprunter 100 000€ à 3% pour acheter un bien rapportant 6% = profit sur capital emprunté. Vous investissez 20 000€ (apport), la banque prête 80 000€. Si le bien vaut 20% de plus en 5 ans, votre rendement sur les 20 000€ investis est de 100% ! C'est le principal avantage de l'immobilier vs autres investissements." },
    { question: "Qu'est-ce que l'éducation financière et pourquoi n'est-elle pas enseignée à l'école selon les experts ?", answers: ["Elle est bien enseignée dans tous les lycées", "Comprendre comment fonctionne l'argent, les investissements et la création de richesse — absente des programmes scolaires car système éducatif conçu pour former des employés", "C'est uniquement pour les riches", "Elle est enseignée uniquement dans les grandes écoles de commerce"], correct: 1, explanation: "Robert Kiyosaki et d'autres dénoncent l'absence d'éducation financière à l'école : le système éducatif forme des employés (qui échangent temps contre argent) et non des investisseurs. Résultat : 70% des Français ne comprennent pas la différence entre action et obligation, 80% n'investissent pas en bourse." },
  ],
  tips: ["Règle des 72 : divisez 72 par votre taux d'intérêt = années pour doubler votre capital", "Constituez votre fonds d'urgence (3-6 mois de dépenses) AVANT tout investissement", "Les revenus passifs (affiliation Amazon, dividendes, loyers) sont la clé de la liberté financière"],
};
export default quizFinancesPersonnelles;
