/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizAustralieEssentiel = {
  title: "Australie — Essentiel Voyage & Culture",
  description: "Droits, règles, culture et bons à savoir avant d'aller en Australie !",
  emoji: "🇦🇺",
  questions: [
    { question: "🛂 Quel document faut-il obligatoirement pour visiter l'Australie ?", answers: ["Passeport + ETA (visa électronique)", "Passeport seul", "Carte d'identité", "ESTA américain"], correct: 0, explanation: "L'Australie exige un ETA (Electronic Travel Authority, sous-classe 601) pour les ressortissants français. Coût : 20 AUD, disponible en ligne ou via l'app AustraliaNow. Séjour touristique max 3 mois." },
    { question: "✈️ Quelle est la durée de vol minimale depuis Paris pour atteindre Sydney ?", answers: ["12 heures", "17-21 heures", "8 heures", "24 heures"], correct: 1, explanation: "Sydney est à environ 17-21 heures de vol de Paris (avec escale généralement à Dubaï, Singapour ou Doha). C'est l'un des vols les plus longs au monde. Le décalage horaire est de +9h à +11h selon la saison." },
    { question: "🐍 L'Australie abrite combien des 25 serpents les plus venimeux au monde ?", answers: ["5", "10", "20 sur 25", "Aucun"], correct: 2, explanation: "L'Australie abrite 20 des 25 serpents les plus venimeux au monde dont le taipan intérieur, le serpent le plus venimeux de la planète. En randonnée : bottes montantes, pantalon long, regardez où vous mettez les pieds !" },
    { question: "🌡️ Dans quel sens tournent les cyclones en Australie ?", answers: ["Sens antihoraire comme dans le nord", "Sens horaire (hémisphère sud)", "Ils ne tournent pas", "Alternativement"], correct: 1, explanation: "Dans l'hémisphère sud, les cyclones tournent dans le sens horaire (effet Coriolis inversé). La saison cyclonique va de novembre à avril dans le nord de l'Australie (Queensland, Territoire du Nord). Restez informés si vous visitez en été austral." },
    { question: "🌿 Quelles espèces végétales ou animales est-il strictement interdit d'importer en Australie ?", answers: ["Seulement les armes", "Fruits, légumes, viandes, plantes, certains produits alimentaires", "Alcool uniquement", "Aucune restriction alimentaire"], correct: 1, explanation: "L'Australie a les lois biosécurité les plus strictes au monde. Fruits, légumes, viandes, plantes, graines et certains aliments sont interdits. Les chiens sont en quarantaine obligatoire. Amendes de 420 AUD sur le champ, jusqu'à 10 ans de prison." },
    { question: "☀️ L'Australie est l'un des pays avec le taux le plus élevé de quel problème de santé ?", answers: ["Diabète", "Cancer de la peau (mélanome)", "Obésité", "Malaria"], correct: 1, explanation: "L'Australie a l'un des taux de mélanome les plus élevés au monde à cause de l'intense rayonnement UV (trou dans la couche d'ozone). Indice UV peut atteindre 12+ (extrême). Crème solaire 50+, chapeau et lunettes UV obligatoires." },
    { question: "💰 Quel est le salaire minimum en Australie, parmi les plus élevés au monde ?", answers: ["15 AUD/heure", "18 AUD/heure", "23,23 AUD/heure", "12 AUD/heure"], correct: 2, explanation: "Le salaire minimum australien est de 23,23 AUD/heure (2024), soit environ 14€/heure. C'est l'un des plus élevés au monde. Un café coûte 5-7 AUD, un repas 20-30 AUD. Le coût de la vie est élevé." },
    { question: "🦘 Quel danger représentent les kangourous pour les conducteurs la nuit en Australie ?", answers: ["Aucun danger", "Risque majeur d'accident — surtout à l'aube et au crépuscule", "Seulement dans les parcs nationaux", "Danger seulement pour les motos"], correct: 1, explanation: "Les kangourous causent des milliers d'accidents chaque année. Ils sautent devant les voitures, surtout à l'aube et au crépuscule. En Outback, conduire de nuit est fortement déconseillé. Certains camions ont des bull-bars (barres de protection)." },
    { question: "🏄 Quelle règle est absolue sur les plages surveillées australiennes ?", answers: ["Nager seulement le matin", "Nager uniquement entre les drapeaux jaunes et rouges", "Interdiction de nager avec maillot de bain", "Toujours nager en groupe"], correct: 1, explanation: "En Australie, on ne nage JAMAIS hors des drapeaux jaunes et rouges sur les plages surveillées. Les courants (rip currents) sont mortels et invisibles. 80 personnes se noient en moyenne chaque année en Australie. Les maîtres-nageurs (Surf Lifesavers) sont bénévoles." },
    { question: "🕐 Combien de fuseaux horaires l'Australie possède-t-elle ?", answers: ["2", "3", "5", "8"], correct: 2, explanation: "L'Australie a 5 fuseaux horaires officiels dont un demi-fuseau unique (Australie du Sud et Territoire du Nord sont à UTC+9h30 !). Quand il est 12h à Sydney, il est 9h30 à Adélaïde et 9h à Perth." },
  ],
  tips: ["ETA obligatoire avant de partir — sur eta.immi.gov.au", "Crème solaire 50+ obligatoire — rayonnement UV extrême toute l'année", "Ne jamais nager hors des drapeaux jaunes et rouges — les courants tuent"],
};
export default quizAustralieEssentiel;
