/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizEspagneEssentiel = {
  title: "Espagne — Essentiel Voyage & Culture",
  description: "Droits, règles, culture et bons à savoir avant d'aller en Espagne !",
  emoji: "🇪🇸",
  questions: [
    { question: "⏰ À quelle heure les Espagnols dînent-ils généralement le soir ?", answers: ["18h-19h", "20h-21h", "21h30-23h", "17h"], correct: 2, explanation: "Les Espagnols dînent très tard, entre 21h30 et 23h. Les restaurants ouvrent rarement avant 21h pour le dîner. La sieste l'après-midi (14h-17h) décale tout le rythme de vie. Ne vous étonnez pas des rues animées à minuit !" },
    { question: "🏖️ Les nudistes ont-ils des droits légaux sur les plages espagnoles ?", answers: ["Interdit partout", "Légal sur toutes les plages", "Légal sur plages désignées et toléré ailleurs", "Seulement aux Îles Canaries"], correct: 2, explanation: "Le nudisme est légal en Espagne sur les plages désignées et généralement toléré. L'Espagne est l'une des destinations nudistes les plus importantes d'Europe. Cependant dans les villes, se promener en maillot peut valoir une amende." },
    { question: "🚬 Depuis quelle année est-il interdit de fumer dans les bars et restaurants en Espagne ?", answers: ["2006", "2010", "2015", "2003"], correct: 1, explanation: "L'Espagne a interdit la cigarette dans tous les lieux fermés publics en 2010 (loi antitabac). Cette loi a été un choc culturel car l'Espagne était connue pour ses bars enfumés. Des amendes de 30 à 600€ s'appliquent." },
    { question: "🎉 Quelle fête espagnole implique de jeter des tomates sur les participants ?", answers: ["Las Fallas", "La Tomatina", "San Fermin", "Semana Santa"], correct: 1, explanation: "La Tomatina de Buñol (Valence) se tient le dernier mercredi d'août. Des milliers de participants se jettent 150 tonnes de tomates. C'est un événement mondial, billetterie obligatoire. Les vêtements blancs sont traditionnels." },
    { question: "💶 Quel est le salaire minimum en Espagne en 2024 ?", answers: ["800€/mois", "1 000€/mois", "1 134€/mois", "900€/mois"], correct: 2, explanation: "Le salaire minimum interprofessionnel (SMI) espagnol était de 1 134€/mois en 2024, après une forte hausse sous le gouvernement Sanchez. C'est l'un des SMI les plus élevés d'Europe du Sud." },
    { question: "🚗 Que se passe-t-il si on est contrôlé sans assurance auto en Espagne ?", answers: ["Simple avertissement", "Amende 600€ à 3 000€ + immobilisation du véhicule", "Retrait de permis immédiat", "Prison possible"], correct: 1, explanation: "En Espagne, conduire sans assurance est une infraction grave : amende de 601€ à 3 005€, immobilisation du véhicule et mise en fourrière. L'assurance au tiers minimum est obligatoire pour tout véhicule circulant." },
    { question: "🌊 Combien de kilomètres de côtes possède l'Espagne, troisième pays côtier d'Europe ?", answers: ["2 000 km", "4 964 km", "8 000 km", "1 500 km"], correct: 1, explanation: "L'Espagne possède 4 964 km de côtes, troisième pays côtier d'Europe. Avec les îles Baléares et Canaries, elle est la 1ère destination touristique mondiale certaines années, accueillant 85 millions de touristes par an." },
    { question: "🐂 La corrida est-elle toujours légale en Espagne en 2024 ?", answers: ["Interdite dans tout le pays", "Légale partout", "Légale dans certaines régions, interdite dans d'autres", "Seulement pour les touristes"], correct: 2, explanation: "La corrida est légale en Espagne mais interdite en Catalogne depuis 2011 et aux Canaries depuis 1991. Elle reste protégée comme patrimoine culturel national en Andalousie, Madrid et d'autres régions. Débat politique vif." },
    { question: "🍷 L'Espagne est le premier pays mondial pour quelle production agricole ?", answers: ["Riz", "Tomates", "Superficie de vignes", "Oranges"], correct: 2, explanation: "L'Espagne possède la plus grande superficie de vignes au monde (950 000 hectares), devant la France et l'Italie. Elle est le 3ème producteur de vin. La Rioja, la Ribera del Duero et le Priorat sont ses régions viticoles phares." },
    { question: "🏛️ Combien de langues officielles l'Espagne compte-t-elle ?", answers: ["1 (castillan)", "2", "4", "6"], correct: 2, explanation: "L'Espagne a 4 langues officielles selon les régions : le castillan (espagnol, national), le catalan (Catalogne, Valence, Baléares), le galicien (Galice) et le basque (Pays Basque). Le catalan est parlé par 10 millions de personnes." },
  ],
  tips: ["Les restaurants ouvrent pour dîner à 21h minimum — ne venez pas à 19h vous serez seuls", "La sieste est réelle : beaucoup de commerces ferment de 14h à 17h", "Emporter un maillot même en ville — la culture balnéaire est omniprésente"],
};
export default quizEspagneEssentiel;
