/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizSpiritualite = {
  title: "Spiritualité & Méditation Mondiale",
  description: "Explorez les grandes traditions spirituelles, la méditation et la conscience du monde !",
  emoji: "🕊",
  questions: [
    { question: "Qu'est-ce que la pleine conscience (mindfulness) ?", answers: ["Une religion asiatique", "L'attention intentionnelle au moment présent sans jugement", "Une technique de sommeil", "Un régime alimentaire"], correct: 1, explanation: "La pleine conscience (mindfulness) est la pratique d'attention intentionnelle au moment présent, sans jugement. Issue du bouddhisme, elle a été adaptée en médecine par Jon Kabat-Zinn (MBSR). Réduire le stress, l'anxiété et améliorer le bien-être sont ses effets prouvés scientifiquement." },
    { question: "Qu'est-ce que le concept hindou de 'Dharma' ?", answers: ["Le destin immuable qu'on ne peut changer", "Le devoir moral, la voie juste, l'ordre naturel de chaque être", "La réincarnation de l'âme", "Le paradis après la mort"], correct: 1, explanation: "Le Dharma est un concept central de l'hindouisme, du bouddhisme et du jaïnisme. Il représente le devoir moral, la loi cosmique, la voie juste propre à chaque individu selon sa nature. Vivre selon son Dharma c'est être en accord avec sa véritable nature et l'ordre universel." },
    { question: "Combien de chakras principaux le corps humain possède-t-il selon la tradition yogique indienne ?", answers: ["3", "5", "7", "12"], correct: 2, explanation: "La tradition yogique reconnaît 7 chakras principaux : Muladhara (racine), Svadhisthana (sacré), Manipura (plexus), Anahata (cœur), Vishuddha (gorge), Ajna (3ème œil), Sahasrara (couronne). Chaque chakra est associé à une couleur, un élément et une dimension de l'être." },
    { question: "Qu'est-ce que le concept bouddhiste de 'Karma' ?", answers: ["La punition divine après la mort", "La loi de cause à effet — chaque action génère une conséquence de même nature", "Le hasard de la vie", "La récompense des bonnes personnes uniquement"], correct: 1, explanation: "Le Karma (sanskrit : action) est la loi universelle de cause à effet. Chaque pensée, parole et action génère des conséquences de même nature. Ce n'est pas une punition externe mais une loi naturelle. Le Karma peut se jouer dans cette vie ou dans des vies futures selon la croyance." },
    { question: "Quelle pratique spirituelle africaine-caribéenne reconnaît les forces de la nature comme divinités ?", answers: ["Le Vaudou haïtien et le Candomblé brésilien", "L'islam soufi uniquement", "Le christianisme évangélique", "Le bouddhisme zen"], correct: 0, explanation: "Le Vaudou haïtien et le Candomblé brésilien sont des religions afro-caribéennes syncrétiques issues de l'Afrique de l'Ouest. Les Loas (Vaudou) et Orixás (Candomblé) sont des forces divines de la nature. Ces religions ont survécu à l'esclavage, transmises secrètement." },
    { question: "Qu'est-ce que la cohérence cardiaque ?", answers: ["Un régime alimentaire pour le cœur", "Une technique de respiration synchronisant cœur et cerveau, réduisant le stress en 5 minutes", "Un exercice sportif cardio", "Une médecine traditionnelle chinoise"], correct: 1, explanation: "La cohérence cardiaque est une technique de respiration (5 secondes inspir, 5 secondes expir, 6 cycles/minute, 5 minutes) qui synchronise le rythme cardiaque et le cerveau. Effets prouvés : réduction du cortisol (hormone du stress), amélioration de la concentration et du bien-être. Pratique 3 fois par jour idéalement." },
    { question: "Que signifie 'Namaste', salutation spirituelle indienne ?", answers: ["Bonjour en hindi uniquement", "Je reconnais la lumière divine en vous / La divinité en moi s'incline devant la divinité en vous", "Merci pour votre hospitalité", "Que la paix soit avec vous"], correct: 1, explanation: "Namaste (mains jointes au niveau du cœur, légère inclinaison) signifie littéralement 'je m'incline devant toi'. Sa signification profonde : la lumière divine en moi reconnaît et honore la lumière divine en toi. C'est une reconnaissance de l'unité fondamentale de tous les êtres." },
    { question: "Qu'est-ce que la loi de l'attraction dans la spiritualité contemporaine ?", answers: ["Une loi physique de Newton", "Le principe que nos pensées dominantes attirent des réalités de même nature dans notre vie", "Une technique de séduction", "Un dogme religieux catholique"], correct: 1, explanation: "La loi de l'attraction stipule que nos pensées dominantes, émotions et croyances attirent des situations, personnes et opportunités de même vibration. Popularisée par 'Le Secret' (Rhonda Byrne, 2006). Ses racines sont dans la Nouvelle Pensée du XIXe siècle et des enseignements comme ceux de Neville Goddard." },
    { question: "Quelle est la signification du symbole universel Yin-Yang ?", answers: ["Bien contre Mal en combat éternel", "La complémentarité et l'interdépendance des forces opposées — l'équilibre dynamique du tout", "Le jour et la nuit uniquement", "La mort et la vie en opposition"], correct: 1, explanation: "Le Yin-Yang (taijitu) représente la complémentarité des opposés : dans chaque Yin il y a du Yang et vice versa. Féminin/masculin, nuit/jour, repos/action ne s'opposent pas mais se complètent et se transforment mutuellement. Concept fondamental du taoïsme chinois." },
    { question: "Qu'est-ce que la méditation Vipassana, l'une des plus anciennes techniques bouddhistes ?", answers: ["Une méditation avec mantras chantés", "L'observation pure et non-réactive des sensations corporelles et des pensées", "Une méditation guidée avec visualisation", "Une technique de sommeil profond"], correct: 1, explanation: "Vipassana signifie 'voir les choses telles qu'elles sont'. C'est une méditation d'observation silencieuse des sensations corporelles sans réaction. Les retraites Vipassana durent 10 jours en silence total. Cette technique remonte à Bouddha Gautama il y a 2500 ans et est enseignée gratuitement dans le monde entier." },
  ],
  tips: ["La méditation 10 minutes par jour change profondément le cerveau en 8 semaines — prouvé par neurosciences", "Les traditions spirituelles afro-caribéennes comme le Vaudou et le Candomblé sont des religions à part entière — pas de la sorcellerie", "La cohérence cardiaque (5-5-5) est la technique anti-stress la plus rapidement efficace connue"],
};
export default quizSpiritualite;
