const quizPhotographie = {
  title: "Photographie",
  description: "Découvrez l'art de capturer le monde à travers un objectif !",
  emoji: "📸",
  questions: [
    { question: "📸 Qu'est-ce que le triangle d'exposition en photographie ?", answers: ["La composition en triangle", "Les trois réglages fondamentaux : ISO, vitesse d'obturation et ouverture (f)", "Un filtre photographique", "Un type d'éclairage studio"], correct: 1, explanation: "Le triangle d'exposition est la relation entre les 3 paramètres qui contrôlent la lumière : l'ISO (sensibilité), la vitesse d'obturation (durée d'exposition) et l'ouverture du diaphragme (quantité de lumière). Maîtriser ces 3 éléments permet de contrôler totalement son exposition." },
    { question: "🌅 Qu'est-ce que la règle des tiers en composition photographique ?", answers: ["Diviser la photo en trois parties égales horizontalement", "Diviser l'image en une grille 3×3 et placer les éléments importants aux intersections", "Utiliser trois sources de lumière", "Prendre trois photos identiques"], correct: 1, explanation: "La règle des tiers divise l'image en une grille de 9 cases égales. En plaçant les sujets importants sur les lignes ou aux intersections (points forts), vous créez des compositions plus dynamiques et plus agréables à l'œil que le simple centrage." },
    { question: "🎭 Qu'est-ce que la profondeur de champ ?", answers: ["La distance entre le photographe et son sujet", "La zone de netteté dans une image — une grande ouverture (f/1.8) = faible profondeur = arrière-plan flou", "La résolution de l'image", "Le zoom de l'objectif"], correct: 1, explanation: "La profondeur de champ définit ce qui est net dans votre image. Une grande ouverture (petit chiffre f/) donne une faible profondeur de champ : le sujet est net, l'arrière-plan est flou (bokeh). Idéal pour les portraits. Une petite ouverture (grand f/) garde tout net — parfait pour les paysages." },
    { question: "🌴 Pourquoi la 'golden hour' est-elle appréciée des photographes ?", answers: ["Parce qu'on voit de l'or dans le ciel", "La lumière est douce, chaude et directionnelle juste après le lever ou avant le coucher du soleil — idéale pour les photos", "C'est l'heure de pointe pour les photos de rue", "La lumière est la plus intense"], correct: 1, explanation: "La golden hour (heure dorée) se produit dans l'heure suivant le lever du soleil et l'heure précédant le coucher. La lumière est basse, douce, chaude et crée de longues ombres dramatiques. En Guadeloupe, ces moments offrent des couchers de soleil et lumières caribéennes exceptionnels." },
    { question: "📱 Qu'est-ce qui différencie une bonne photo smartphone d'une photo professionnelle ?", answers: ["La taille du capteur uniquement", "La composition, la lumière, le moment décisif et l'intention artistique — pas seulement le matériel", "Le nombre de mégapixels", "La marque du téléphone"], correct: 1, explanation: "Les meilleurs photographes disent : 'Le meilleur appareil photo est celui que vous avez sur vous.' Un smartphone peut produire des photos exceptionnelles avec une bonne composition et lumière. La technique et l'œil artistique comptent plus que le matériel." },
  ],
  tips: ["📸 Apprenez la règle des tiers — elle transforme immédiatement vos photos", "🌅 En Guadeloupe, les couchers de soleil et la lumière caribéenne offrent des conditions photographiques exceptionnelles", "💡 Photographier avec intention, pas juste appuyer sur le bouton"],
};
export default quizPhotographie;
