/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizModeBeaute = {
  title: "Mode & Beauté",
  description: "Explorez le monde de la mode, du style et de la beauté !",
  emoji: "👗",
  questions: [
    { question: "👗 Quelle maison de mode française est considérée comme la plus ancienne haute couture encore active ?", answers: ["Chanel", "Dior", "Givenchy", "Hermès (fondé en 1837)"], correct: 3, explanation: "Hermès, fondée en 1837, est l'une des plus anciennes maisons de luxe françaises encore en activité. Bien que connue pour ses sacs Birkin et Kelly et ses carrés de soie, elle a démarré comme sellier-harnacheur." },
    { question: "💄 Qu'est-ce que la 'Fast Fashion' ?", answers: ["La mode pour les personnes pressées", "La production rapide et bon marché de vêtements qui imitent les tendances des défilés, à fort impact environnemental", "Les collections haute couture", "La mode sportive"], correct: 1, explanation: "La Fast Fashion (H&M, Zara, Shein...) renouvelle ses collections très rapidement à bas prix. Son impact environnemental est catastrophique : 2ème industrie la plus polluante au monde, avec des millions de tonnes de textiles jetés annuellement." },
    { question: "🌺 Qu'est-ce que le madras aux Antilles ?", answers: ["Un plat traditionnel", "Un tissu à carreaux colorés originaire de l'Inde, devenu le tissu identitaire du costume traditionnel antillais", "Une danse créole", "Un instrument de musique"], correct: 1, explanation: "Le madras est un tissu à carreaux colorés arrivé aux Antilles avec les immigrants indiens au XIXe siècle. Il est devenu l'élément central du costume traditionnel créole — la robe à l'identique chez les femmes, notamment lors du carnaval et des fêtes folkloriques." },
    { question: "💅 Qu'est-ce que la beauté inclusive ?", answers: ["Des produits moins chers", "Une approche qui célèbre et propose des produits adaptés à toutes les carnations, morphologies et identités", "La beauté naturelle sans maquillage", "Des produits bio uniquement"], correct: 1, explanation: "La beauté inclusive valorise la diversité : des fondations pour toutes les carnations (initiative lancée par Fenty Beauty de Rihanna en 2017 avec 40 teintes), des mannequins de toutes tailles et origines, des produits pour tous les types de cheveux." },
    { question: "👘 Quel pays est réputé pour son industrie textile de luxe (soie, haute couture) ?", answers: ["Chine uniquement", "France (haute couture), Italie (luxe), Japon (artisanat textile)", "USA", "Brésil"], correct: 1, explanation: "La France est le berceau de la haute couture mondiale (Paris Fashion Week). L'Italie excelle dans le luxe (Gucci, Prada, Versace). Le Japon perpétue des techniques textiles artisanales uniques (soie, indigo, kimono)." },
    { question: "🌍 Pourquoi la mode africaine connaît-elle un essor mondial ?", answers: ["Uniquement grâce aux célébrités américaines", "Les créateurs africains et de la diaspora apportent des tissus, couleurs et designs uniques qui s'imposent sur la scène mondiale", "C'est une tendance passagère", "Grâce aux grandes maisons européennes uniquement"], correct: 1, explanation: "Des créateurs comme Ozwald Boateng (Ghana/UK), Lisa Folawiyo (Nigeria) ou Hanifa (Congo/USA) imposent la mode africaine mondialement. Le Wakanda Fashion de Black Panther a aussi propulsé l'intérêt pour l'esthétique africaine." },
  ],
  tips: ["👗 Le costume créole madras est un patrimoine culturel antillais à valoriser", "🌍 La mode africaine et afro-caribéenne monte en puissance sur la scène internationale", "💡 Acheter local et durable vaut mieux que la fast fashion"],
};
export default quizModeBeaute;
