/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizAfroCaraibes1 = {
  title: "Afro-Caraïbes & Indépendances",
  description: "Découvrez l'histoire des peuples afro-caribéens, leurs luttes et les dates d'indépendance des ex-colonies !",
  emoji: "✊",
  questions: [
    { question: "Quel pays caribéen fut le premier à obtenir son indépendance en 1804 après une révolte d'esclaves ?", answers: ["La Jamaïque", "Haïti", "Cuba", "La Barbade"], correct: 1, explanation: "Haïti est la première République noire du monde, née le 1er janvier 1804 après la révolution menée par Toussaint Louverture et Jean-Jacques Dessalines contre la France." },
    { question: "En quelle année la Jamaïque a-t-elle obtenu son indépendance du Royaume-Uni ?", answers: ["1958", "1962", "1970", "1945"], correct: 1, explanation: "La Jamaïque a obtenu son indépendance le 6 août 1962. Elle faisait partie des Indes occidentales britanniques depuis le XVIIe siècle." },
    { question: "En quelle année la Barbade est-elle devenue indépendante ET République ?", answers: ["1966 et 2001", "1966 et 2021", "1970 et 2015", "1962 et 2021"], correct: 1, explanation: "La Barbade a obtenu son indépendance le 30 novembre 1966, puis est devenue République le 30 novembre 2021. Sandra Mason est devenue la première présidente." },
    { question: "Quel leader de la révolution haïtienne était surnommé Le Précurseur ?", answers: ["Jean-Jacques Dessalines", "Henri Christophe", "Toussaint Louverture", "Boukman"], correct: 2, explanation: "Toussaint Louverture (1743-1803), né esclave, a dirigé l'armée révolutionnaire contre la France, l'Espagne et l'Angleterre. Il reste le symbole de la liberté afro-caribéenne." },
    { question: "Haïti fut forcée de payer une dette d'indépendance à quel pays ?", answers: ["Angleterre", "Espagne", "France", "États-Unis"], correct: 2, explanation: "Haïti fut forcée de payer 150 millions de francs-or à la France pour compenser les pertes des colons esclavagistes. Cette dette a été payée jusqu'en 1947, paralysant l'économie haïtienne." },
    { question: "Trinidad-et-Tobago a obtenu son indépendance du Royaume-Uni en quelle année ?", answers: ["1958", "1960", "1962", "1965"], correct: 2, explanation: "Trinidad-et-Tobago est devenu indépendant le 31 août 1962. Le pays est le berceau du calypso et du steelpan, instrument inventé par les Afro-Trinidadiens." },
    { question: "Le Guyana a obtenu son indépendance du Royaume-Uni en quelle année ?", answers: ["1962", "1966", "1970", "1975"], correct: 1, explanation: "Le Guyana a obtenu son indépendance le 26 mai 1966. C'est le seul pays d'Amérique du Sud dont la langue officielle est l'anglais." },
    { question: "Les Bahamas ont obtenu leur indépendance du Royaume-Uni en quelle année ?", answers: ["1968", "1970", "1973", "1975"], correct: 2, explanation: "Les Bahamas sont devenus indépendants le 10 juillet 1973. La population est à 90% afro-caribéenne." },
    { question: "Le Suriname a obtenu son indépendance des Pays-Bas en quelle année ?", answers: ["1970", "1973", "1975", "1980"], correct: 2, explanation: "Le Suriname a obtenu son indépendance le 25 novembre 1975. Sa culture est un mélange unique d'influences africaines, indiennes, javanaises et amérindiennes." },
    { question: "Qui était le leader du mouvement Black Power né à Trinidad ?", answers: ["Eric Williams", "Stokely Carmichael (Kwame Ture)", "CLR James", "George Padmore"], correct: 1, explanation: "Stokely Carmichael, né à Trinidad, a popularisé le slogan Black Power. Il a ensuite émigré en Guinée et pris le nom de Kwame Ture, continuant son combat panafricaniste." },
    { question: "Aimé Césaire, père du mouvement Négritude, était originaire de quelle île ?", answers: ["Haïti", "Guadeloupe", "Martinique", "Réunion"], correct: 2, explanation: "Aimé Césaire (1913-2008) était originaire de la Martinique. Il a co-fondé la Négritude avec Senghor. Il fut aussi maire de Fort-de-France pendant 56 ans." },
    { question: "Cuba a obtenu son indépendance de l'Espagne en quelle année ?", answers: ["1895", "1898", "1901", "1959"], correct: 1, explanation: "Cuba a officiellement obtenu son indépendance de l'Espagne en 1898. Antonio Maceo, le Titan de Bronze, était un général afro-cubain majeur dans ces guerres d'indépendance." },
    { question: "En quelle année Saint-Kitts-et-Nevis a-t-il obtenu son indépendance ?", answers: ["1981", "1983", "1985", "1979"], correct: 1, explanation: "Saint-Kitts-et-Nevis est devenu indépendant le 19 septembre 1983, devenant la plus petite nation indépendante des Amériques." },
    { question: "Quel mouvement spirituel afro-caribéen est né en Jamaïque dans les années 1930 ?", answers: ["Le Calypso", "Le Rastafari", "La Soca", "Le Reggaeton"], correct: 1, explanation: "Le mouvement Rastafari est né en Jamaïque dans les années 1930, inspiré par Marcus Garvey. Bob Marley l'a popularisé mondialement." },
    { question: "La Dominique a obtenu son indépendance du Royaume-Uni en quelle année ?", answers: ["1974", "1976", "1978", "1980"], correct: 2, explanation: "La Dominique a obtenu son indépendance le 3 novembre 1978. Elle abrite la dernière communauté amérindienne Kalinago de la région." },
    { question: "Quel commandant afro-cubain était l'un des survivants du débarquement du Granma en 1956 ?", answers: ["José Martí", "Che Guevara", "Juan Almeida Bosque", "Camilo Cienfuegos"], correct: 2, explanation: "Juan Almeida Bosque (1927-2011) était un commandant afro-cubain de la révolution. Il fut l'un des leaders les plus importants aux côtés de Castro." },
    { question: "Sainte-Lucie a obtenu son indépendance du Royaume-Uni en quelle année ?", answers: ["1977", "1979", "1981", "1975"], correct: 1, explanation: "Sainte-Lucie est devenue indépendante le 22 février 1979. L'île a donné naissance à deux Prix Nobel : Derek Walcott (Littérature) et Sir Arthur Lewis (Économie)." },
    { question: "La Grenade a obtenu son indépendance du Royaume-Uni en quelle année ?", answers: ["1972", "1974", "1976", "1979"], correct: 1, explanation: "La Grenade a obtenu son indépendance le 7 février 1974. En 1979, Maurice Bishop a mené une révolution socialiste. C'est aussi l'île aux épices." },
    { question: "Quel écrivain afro-caribéen a écrit 'In the Castle of My Skin' sur la Barbade coloniale ?", answers: ["Derek Walcott", "George Lamming", "CLR James", "Frantz Fanon"], correct: 1, explanation: "George Lamming (1927-2022) est l'auteur de ce chef-d'œuvre de 1953 décrivant la vie coloniale en Barbade." },
    { question: "Frantz Fanon, auteur de Les Damnés de la Terre, était originaire de quelle île ?", answers: ["Haïti", "Trinidad", "Martinique", "Guadeloupe"], correct: 2, explanation: "Frantz Fanon (1925-1961), né en Martinique, est l'un des penseurs les plus importants de la décolonisation. Il a rejoint le FLN algérien." },
    { question: "Quel leader jamaïcain a fondé l'UNIA, le plus grand mouvement noir de masse de l'histoire ?", answers: ["Bob Marley", "Marcus Garvey", "Walter Rodney", "CLR James"], correct: 1, explanation: "Marcus Mosiah Garvey (1887-1940) a fondé l'UNIA en 1914. Son drapeau rouge-noir-vert est devenu le symbole du panafricanisme mondial." },
    { question: "Saint-Vincent-et-les-Grenadines a obtenu son indépendance en quelle année ?", answers: ["1978", "1979", "1981", "1983"], correct: 1, explanation: "Saint-Vincent est devenu indépendant le 27 octobre 1979. Les Garifunas, peuple mélangé d'Africains et d'Amérindiens, ont résisté aux Britanniques jusqu'en 1797." },
    { question: "Quel historien trinidadien a écrit 'The Black Jacobins' sur la révolution haïtienne ?", answers: ["Eric Williams", "CLR James", "Walter Rodney", "George Padmore"], correct: 1, explanation: "CLR James (1901-1989), né à Trinidad, a écrit The Black Jacobins (1938), l'une des œuvres historiques les plus importantes du XXe siècle." },
    { question: "Belize a obtenu son indépendance du Royaume-Uni en quelle année ?", answers: ["1979", "1981", "1983", "1985"], correct: 1, explanation: "Belize a obtenu son indépendance le 21 septembre 1981. Les Garifunas au Belize ont été reconnus par l'UNESCO comme patrimoine culturel immatériel en 2001." },
    { question: "Que symbolise le Rouge dans le drapeau panafricain de Marcus Garvey ?", answers: ["Le sang versé par les Africains", "Le courage", "La révolution", "Le soleil"], correct: 0, explanation: "Marcus Garvey a créé ce drapeau en 1920 : Rouge = sang versé, Noir = peuple noir, Vert = richesses de l'Afrique. Repris par de nombreux pays africains et mouvements de libération." },
  ],
  tips: [
    "La révolution haïtienne de 1804 reste l'unique révolte d'esclaves ayant fondé une nation libre",
    "Marcus Garvey, né en Jamaïque, a inspiré Haïlé Sélassié, le mouvement Rastafari et des générations de leaders africains",
    "La Martinique et la Guadeloupe sont des DOM français — leur histoire coloniale est aussi riche que celle des îles indépendantes"
  ],
};
export default quizAfroCaraibes1;
