/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizDeveloppementSoi = {
  title: "Développement de Soi — Mindset Gagnant",
  description: "Les clés mentales et psychologiques pour transformer votre vie et atteindre vos objectifs !",
  emoji: "🧠",
  questions: [
    { question: "Qu'est-ce que le Growth Mindset selon Carol Dweck, psychologue de Stanford ?", answers: ["Croire que l'intelligence est fixe à la naissance", "Croire que les capacités peuvent se développer avec l'effort et l'apprentissage", "Penser positivement en permanence", "Éviter les défis pour ne pas échouer"], correct: 1, explanation: "Carol Dweck a identifié deux mentalités : Fixed Mindset (les capacités sont fixes) vs Growth Mindset (les capacités se développent avec l'effort). Les personnes à Growth Mindset voient les échecs comme des apprentissages. Cette découverte a révolutionné l'éducation mondiale." },
    { question: "Quelle est la règle des 21 jours souvent citée en développement personnel ?", answers: ["Il faut 21 jours pour guérir une blessure", "Il faudrait 21 jours pour créer une nouvelle habitude — chiffre popularisé mais révisé à 66 jours en moyenne", "21 minutes de sport suffisent par jour", "Lire 21 pages par jour suffit pour progresser"], correct: 1, explanation: "La règle des 21 jours vient du Dr Maxwell Maltz (1960) qui observait ses patients après chirurgie. Popularisée dans le développement personnel, elle est inexacte : une étude de Phillippa Lally (UCL, 2010) montre qu'une habitude prend en moyenne 66 jours (18 à 254 jours selon les personnes et l'habitude)." },
    { question: "Qu'est-ce que la méthode Kaizen pour progresser ?", answers: ["Amélioration spectaculaire et rapide par révolution totale", "Amélioration continue par petits pas quotidiens — 1% mieux chaque jour", "Technique de méditation japonaise", "Méthode de gestion du temps intensive"], correct: 1, explanation: "Kaizen (japonais : kai = changement, zen = bon) est la philosophie de l'amélioration continue par petits pas. 1% d'amélioration par jour = 37 fois meilleur en un an (1.01^365 = 37.78). Adoptée par Toyota, elle a révolutionné l'industrie mondiale et s'applique à tous les domaines de vie." },
    { question: "Qu'est-ce que la Zone de Confort et pourquoi la quitter est essentiel ?", answers: ["Un espace physique relaxant", "L'espace psychologique où tout est familier et sans stress — en sortir crée la croissance personnelle", "Une technique de relaxation", "Un état de santé optimal"], correct: 1, explanation: "La Zone de Confort est l'espace mental où les actions sont routinières et sans anxiété. La Zone d'Apprentissage (juste au-delà) est là où la croissance se produit. La Zone de Panique (trop loin) paralyse. La progression optimale se fait dans la zone d'apprentissage — challenge adapté." },
    { question: "Selon la pyramide de Maslow, quel est le besoin humain le plus élevé ?", answers: ["La sécurité physique", "L'appartenance sociale", "L'estime de soi", "L'accomplissement de soi (Self-actualization)"], correct: 3, explanation: "La pyramide de Maslow (1943) hiérarchise les besoins humains : 1. Physiologiques (manger, dormir), 2. Sécurité, 3. Appartenance/Amour, 4. Estime de soi, 5. Accomplissement de soi. On ne peut véritablement viser le niveau 5 que si les niveaux inférieurs sont suffisamment satisfaits." },
    { question: "Qu'est-ce que la technique Pomodoro pour la productivité ?", answers: ["Manger des tomates pour la concentration", "Travailler 25 minutes de façon intense puis pause 5 minutes — cycles répétés", "Se lever à 5h du matin", "Travailler sans pause pendant 4 heures"], correct: 1, explanation: "La technique Pomodoro (Francesco Cirillo, 1980s) : 25 minutes de travail intensif + 5 minutes de pause = 1 Pomodoro. Après 4 Pomodoros, pause longue de 15-30 minutes. Cette méthode exploite les cycles naturels d'attention du cerveau et combat la procrastination efficacement." },
    { question: "Que signifie l'ikigai, concept japonais de développement personnel ?", answers: ["L'art de la méditation zen", "La raison d'être — l'intersection entre ce qu'on aime, ce pour quoi on est doué, ce dont le monde a besoin et ce pour quoi on peut être payé", "La retraite anticipée", "Le bonheur par la richesse"], correct: 1, explanation: "L'Ikigai (iki = vie, gai = valeur) est votre raison de vous lever le matin. Il se trouve à l'intersection de 4 cercles : Passion (ce qu'on aime), Mission (ce dont le monde a besoin), Vocation (ce pour quoi on peut être payé), Profession (ce pour quoi on est doué). Les Japonais d'Okinawa, les plus centenaires au monde, vivent leur Ikigai." },
    { question: "Qu'est-ce que la visualisation créatrice utilisée par les grands sportifs et entrepreneurs ?", answers: ["Regarder des vidéos inspirantes", "Créer mentalement des images vives de ses objectifs atteints pour programmer le cerveau vers le succès", "Dessiner ses objectifs sur papier", "Créer un tableau de vision Pinterest"], correct: 1, explanation: "La visualisation créatrice consiste à imaginer avec tous les sens ses objectifs déjà atteints. Des études montrent que le cerveau ne distingue pas vraiment une visualisation intense de la réalité — les mêmes neurones s'activent. Michael Jordan, Serena Williams et Muhammad Ali utilisaient cette technique quotidiennement." },
    { question: "Qu'est-ce que la procrastination et quelle en est la vraie cause selon les psychologues ?", answers: ["La paresse pure", "Un problème de gestion du temps", "Une régulation émotionnelle défaillante — on évite les émotions négatives liées à une tâche", "Un manque de motivation uniquement"], correct: 2, explanation: "La recherche montre que la procrastination n'est PAS un problème de gestion du temps mais de régulation émotionnelle. On procrastine pour éviter les émotions négatives (anxiété, ennui, doute) associées à une tâche. La solution : accepter ces émotions et commencer malgré elles — la technique des 2 minutes est efficace." },
    { question: "Qu'est-ce que la méthode SMART pour fixer des objectifs efficaces ?", answers: ["Simple, Mesurable, Attractif, Réaliste, Temporel", "Spécifique, Mesurable, Atteignable, Réaliste, Temporellement défini", "Stratégique, Motivant, Ambitieux, Responsable, Transformateur", "Solide, Motivant, Actionnable, Récompensé, Transparent"], correct: 1, explanation: "SMART : Spécifique (précis, pas vague), Mesurable (quantifiable), Atteignable (challengeant mais possible), Réaliste (avec les ressources disponibles), Temporellement défini (date limite). Un objectif SMART transforme un vœu en plan d'action concret. Méthode créée par George Doran en 1981." },
  ],
  tips: ["1% d'amélioration par jour = 37 fois meilleur en un an — la magie des petits pas (Kaizen)", "La procrastination est une régulation émotionnelle, pas de la paresse — acceptez l'inconfort et commencez", "Votre Ikigai est à l'intersection de ce que vous aimez, savez faire, ce dont le monde a besoin et ce qui vous fait vivre"],
};
export default quizDeveloppementSoi;
