/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizDroit = {
  title: "Droit & Justice",
  description: "Connaissez vos droits et comprenez le système juridique !",
  emoji: "⚖️",
  questions: [
    { question: "⚖️ Quelle est la différence entre le droit civil et le droit pénal ?", answers: ["Il n'y en a aucune", "Le droit civil règle les litiges entre personnes privées, le droit pénal punit les infractions contre la société", "Le droit civil est plus sévère", "Le droit pénal concerne uniquement les entreprises"], correct: 1, explanation: "Le droit civil gère les conflits entre particuliers (divorce, contrats, succession). Le droit pénal (ou criminel) sanctionne les comportements que la société juge dangereux (vol, meurtre, fraude). Deux affaires peuvent coexister pour les mêmes faits." },
    { question: "🇫🇷 Qu'est-ce que la présomption d'innocence ?", answers: ["Présumer que tout accusé est coupable", "Tout accusé est considéré innocent jusqu'à ce que sa culpabilité soit prouvée par un tribunal", "Un droit réservé aux citoyens français", "Une notion obsolète"], correct: 1, explanation: "La présomption d'innocence est un principe fondamental du droit : c'est à l'accusation de prouver la culpabilité, pas à l'accusé de prouver son innocence. Elle est garantie par la Déclaration des Droits de l'Homme de 1789 et la Convention européenne des droits de l'homme." },
    { question: "📋 Qu'est-ce qu'un contrat ?", answers: ["Un document officiel signé devant notaire uniquement", "Un accord entre deux ou plusieurs parties créant des obligations juridiques", "Un document gouvernemental", "Une loi locale"], correct: 1, explanation: "Un contrat est un accord de volontés entre parties qui crée des obligations. Il peut être écrit ou oral (même si l'écrit facilite la preuve). Pour être valide, il nécessite : consentement libre, capacité des parties, objet licite et cause réelle." },
    { question: "🏢 Qu'est-ce qu'une SARL ?", answers: ["Une association à but non lucratif", "Une Société à Responsabilité Limitée — les associés ne sont responsables qu'à hauteur de leurs apports", "Une société publique", "Un type de coopérative"], correct: 1, explanation: "La SARL est la forme juridique la plus courante pour les PME françaises. La responsabilité des associés est limitée à leurs apports (ce qu'ils ont investi) — leur patrimoine personnel est protégé en cas de dettes de la société." },
    { question: "🌍 Qu'est-ce que la double nationalité ?", answers: ["Avoir deux passeports de pays différents simultanément", "Détenir la nationalité de deux pays en même temps — légal dans de nombreux pays dont la France", "Un statut diplomatique spécial", "Être né dans deux pays différents"], correct: 1, explanation: "La double nationalité permet d'être citoyen de deux pays simultanément. La France l'autorise depuis 1973. Elle offre des avantages pratiques (deux passeports, droits dans deux pays) mais peut créer des obligations (service militaire dans certains pays)." },
    { question: "📱 En France, quels sont vos droits concernant vos données personnelles ?", answers: ["Les entreprises peuvent faire ce qu'elles veulent", "Le RGPD vous garantit : droit d'accès, rectification, effacement, portabilité et opposition au traitement de vos données", "Vous n'avez aucun droit sur vos données en ligne", "Seulement les données bancaires sont protégées"], correct: 1, explanation: "Le RGPD (Règlement Général sur la Protection des Données) en vigueur depuis 2018 vous donne des droits étendus sur vos données personnelles. Toute entreprise traitant vos données doit obtenir votre consentement et vous permettre d'y accéder ou de les supprimer." },
  ],
  tips: ["⚖️ Connaître ses droits fondamentaux est essentiel pour tout citoyen et entrepreneur", "📋 Faites toujours rédiger vos accords importants par écrit", "🌍 En Guadeloupe, le droit français s'applique intégralement avec quelques adaptations locales"],
};
export default quizDroit;
