const quizDroitsNumeriques = {
  title: "Droits Numériques & RGPD",
  description: "Maîtrisez vos droits sur internet, vos données personnelles et la protection numérique !",
  emoji: "💻",
  questions: [
    { question: "Qu'est-ce que le RGPD et depuis quand est-il applicable en Europe ?", answers: ["Un antivirus européen", "Règlement Général sur la Protection des Données — applicable depuis le 25 mai 2018 dans toute l'UE", "Une loi française uniquement de 2015", "Un standard volontaire pour les entreprises tech"], correct: 1, explanation: "Le RGPD (Règlement UE 2016/679) est applicable depuis le 25 mai 2018 dans toute l'UE. Il encadre la collecte et le traitement des données personnelles. Il s'applique à toute organisation traitant des données de résidents européens, où qu'elle soit dans le monde. Sanctions : jusqu'à 4% du chiffre d'affaires mondial ou 20 millions d'euros." },
    { question: "Quels sont vos droits sur vos données personnelles selon le RGPD ?", answers: ["Aucun droit une fois les données transmises", "Droit d'accès, de rectification, d'effacement (droit à l'oubli), de portabilité, d'opposition et de limitation du traitement", "Uniquement le droit de voir ses données", "Seulement le droit de suppression"], correct: 1, explanation: "Vos droits RGPD : Accès (obtenir une copie de vos données), Rectification (corriger les inexactitudes), Effacement/Oubli (supprimer vos données sous conditions), Portabilité (récupérer vos données en format lisible), Opposition (refuser certains traitements), Limitation (restreindre l'usage). Exercez-les auprès du DPO de l'organisation ou de la CNIL." },
    { question: "Qu'est-ce que le droit à l'oubli sur internet et comment l'exercer ?", answers: ["Impossible de supprimer des informations d'internet", "Droit de demander la suppression de résultats de recherche vous concernant sur Google/Bing — CNIL ou formulaire en ligne", "Uniquement pour les mineurs", "Seulement pour les informations fausses"], correct: 1, explanation: "Le droit au déréférencement (droit à l'oubli) permet de demander la suppression de liens de résultats de recherche contenant des informations vous concernant obsolètes, inexactes ou non pertinentes. Formulaire Google : myaccount.google.com/delete-services. Si refus, recours auprès de la CNIL. Plus de 1 million de demandes traitées par Google depuis 2014." },
    { question: "Qu'est-ce qu'un cookie et quels sont vos droits selon le RGPD ?", answers: ["Un virus informatique", "Fichier déposé sur votre navigateur pour vous suivre — vous pouvez refuser les cookies non essentiels", "Uniquement utilisé par les sites illégaux", "Obligatoire pour naviguer sur internet"], correct: 1, explanation: "Un cookie est un petit fichier texte déposé par un site web sur votre navigateur pour vous identifier, mémoriser vos préférences ou vous tracer à des fins publicitaires. Le RGPD impose : consentement explicite pour les cookies non essentiels (statistiques, publicité). Vous pouvez refuser sans perdre l'accès au site. Bannières cookie obligatoires depuis 2020." },
    { question: "Qu'est-ce que le phishing (hameçonnage) et comment s'en protéger ?", answers: ["Un virus qui détruit les fichiers", "Technique de fraude par email/SMS usurpant une identité connue pour voler identifiants et données bancaires", "Un spam publicitaire uniquement", "Un piratage de compte par force brute"], correct: 1, explanation: "Le phishing : email ou SMS imitant une banque, administration ou service connu (Ameli, impôts, Amazon) pour vous faire cliquer sur un faux lien et voler vos identifiants ou données bancaires. Protection : vérifier l'adresse email exacte de l'expéditeur, ne jamais cliquer sur les liens d'emails inattendus, aller directement sur le site officiel. Signaler sur phishing-initiative.fr." },
    { question: "Que risque une entreprise qui viole le RGPD en France ?", answers: ["Un simple avertissement", "Amende jusqu'à 4% du CA mondial ou 20M€ (le plus élevé) — Google condamné à 150M€ en 2022 par la CNIL", "Uniquement une obligation de correction", "Aucune sanction en pratique"], correct: 1, explanation: "La CNIL (Commission Nationale Informatique et Libertés) peut sanctionner jusqu'à 4% du chiffre d'affaires mondial ou 20 millions d'euros (le montant le plus élevé). Sanctions réelles : Google condamné à 150M€ (2022), Facebook/Meta 1,2 milliard€ par l'autorité irlandaise (2023). En 2023, la CNIL a prononcé 42 sanctions pour un total de 89M€ d'amendes." },
    { question: "Qu'est-ce que la neutralité du net et pourquoi est-elle importante ?", answers: ["Internet gratuit pour tous", "Principe selon lequel les FAI doivent traiter tous les flux de données de manière égale sans discrimination", "Interdiction de la censure sur internet", "Accès identique à internet dans tous les pays"], correct: 1, explanation: "La neutralité du net (net neutrality) : les Fournisseurs d'Accès à Internet (FAI) doivent traiter tous les flux de données de manière égale, sans ralentir, bloquer ou favoriser certains services. Garantie par le Règlement européen sur l'internet ouvert (2015). Sans elle, les FAI pourraient créer des internet à deux vitesses et favoriser leurs propres services." },
    { question: "Quel est l'âge minimum légal en France pour créer un compte sur les réseaux sociaux ?", answers: ["13 ans sans condition", "13 ans avec consentement parental obligatoire selon la loi française (15 ans souhaité par la CNIL)", "10 ans", "18 ans"], correct: 1, explanation: "En France, la loi pour une République Numérique (2016) et le RGPD fixent 15 ans comme âge minimum pour consentir seul au traitement de ses données (donc créer un compte). En dessous de 15 ans : consentement parental obligatoire. Les plateformes (TikTok, Instagram) affichent 13 ans mais doivent recueillir le consentement parental pour les moins de 15 ans en France." },
    { question: "Qu'est-ce que le droit à la déconnexion et comment s'applique-t-il en France ?", answers: ["Droit de ne pas avoir internet chez soi", "Droit du salarié à ne pas être contacté professionnellement en dehors des heures de travail — négocié en entreprise depuis 2017", "Interdiction de travailler le weekend", "Droit de couper son téléphone pendant les vacances"], correct: 1, explanation: "Le droit à la déconnexion (loi El Khomri 2016) oblige les entreprises de 50+ salariés à négocier avec les syndicats les modalités du droit à la déconnexion dans l'accord sur le temps de travail. Chaque salarié a le droit de ne pas répondre aux emails et appels professionnels en dehors des heures de travail, sans sanction. Aucune amende n'est prévue pour le salarié qui répond quand même." },
    { question: "Comment déposer une plainte pour cyberharcèlement en France ?", answers: ["Impossible de porter plainte pour des actes numériques", "Plainte au commissariat/gendarmerie, plateforme PHAROS (signalement en ligne), Numéro 3018 pour les mineurs", "Seulement si les actes sont répétés plus de 100 fois", "Uniquement via un avocat spécialisé"], correct: 1, explanation: "Cyberharcèlement (art. 222-33-2-2 Code Pénal) : jusqu'à 3 ans prison et 45 000€ d'amende. Démarches : 1. Capturer les preuves (screenshots horodatés), 2. Signaler sur PHAROS (internet-signalement.gouv.fr), 3. Déposer plainte au commissariat ou gendarmerie, 4. Numéro 3018 (cybermalveillance) pour les mineurs. La plainte peut être déposée même si l'auteur est anonyme." },
  ],
  tips: ["Exercez votre droit à l'oubli Google via myaccount.google.com — plus d'1 million de demandes acceptées", "Vous pouvez refuser tous les cookies non essentiels sans perdre l'accès au site — c'est votre droit RGPD", "Le numéro 3018 aide les mineurs victimes de cyberharcèlement — gratuit et disponible 7j/7"],
};
export default quizDroitsNumeriques;
