/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizJeuneDetox = {
  title: "Jeûne Intermittent & Détox",
  description: "Découvrez la science du jeûne, de la détoxification et de la régénération cellulaire !",
  emoji: "⚡",
  questions: [
    { question: "Qu'est-ce que l'autophagie et quel scientifique a reçu le Nobel pour cette découverte en 2016 ?", answers: ["La digestion des aliments", "Le mécanisme de nettoyage cellulaire par lequel les cellules recyclent leurs déchets — Prix Nobel Yoshinori Ohsumi", "La mort cellulaire programmée", "La reproduction des cellules souches"], correct: 1, explanation: "L'autophagie (auto = soi, phagein = manger) est le mécanisme par lequel les cellules dégradent et recyclent leurs propres composants endommagés. Yoshinori Ohsumi a reçu le Prix Nobel de médecine 2016 pour cette découverte. Le jeûne active puissamment l'autophagie — c'est l'un des mécanismes principaux de ses bénéfices santé." },
    { question: "Quels sont les différents types de jeûne intermittent et leurs spécificités ?", answers: ["Il n'existe qu'un seul type", "16:8 (16h jeûne/8h repas), 5:2 (5 jours normal/2 jours 500 kcal), 24h hebdomadaire, OMAD (1 repas/jour)", "Jeûne total de plusieurs semaines uniquement", "Seulement le jeûne du ramadan"], correct: 1, explanation: "Principaux protocoles : 16:8 (le plus populaire et durable), 18:6, 20:4 (progressivement plus intense), 5:2 (2 jours de restriction calorique sévère/semaine), 24h (jeûne complet une fois/semaine). L'OMAD (One Meal A Day) est le plus restrictif. Le 16:8 est le meilleur point d'entrée pour les débutants." },
    { question: "Quels organes le corps utilise-t-il en premier pour la détoxification naturelle ?", answers: ["Les poumons et la peau uniquement", "Le foie (filtration principale), les reins (excrétion urinaire), les poumons (expiration), la peau (transpiration) et les intestins", "L'estomac uniquement", "Le système lymphatique uniquement"], correct: 1, explanation: "Le corps dispose de 5 émonctoires (organes de détoxification) : Foie (neutralise 90% des toxines, produit la bile), Reins (filtre 180L de sang/jour), Intestins (élimination fécale), Peau (transpiration), Poumons (CO2 et composés volatils). Soutenir ces organes naturellement suffit — les 'cures détox' commerciales sont souvent inutiles voire nocives." },
    { question: "Qu'est-ce que la cétose et comment le corps l'atteint-il pendant le jeûne ?", answers: ["Un état pathologique dangereux", "État métabolique où le corps brûle les graisses en énergie (corps cétoniques) après épuisement du glycogène — atteint après 12-16h de jeûne", "La digestion des protéines uniquement", "Un état de manque de sucre sans conséquence"], correct: 1, explanation: "La cétose : après 12-16h de jeûne, les réserves de glycogène hépatique s'épuisent. Le foie produit des corps cétoniques (BHB, acétoacétate) à partir des graisses. Le cerveau préfère alors les cétones au glucose. État caractérisé par : énergie mentale claire, brûlage de graisses actif, réduction de l'inflammation. Base du régime cétogène." },
    { question: "La cure de jus est-elle une vraie détox selon la science ?", answers: ["Oui, les jus détoxifient profondément le corps", "Non — le corps se détoxifie seul via foie/reins. Les jus peuvent apporter nutriments mais ne 'détoxifient' pas plus que l'alimentation normale", "Oui uniquement si bio et pressés à froid", "Seuls les jus verts ont un effet détox prouvé"], correct: 1, explanation: "Scientifiquement, le terme 'détox' par les jus est un mythe marketing. Aucune étude clinique rigoureuse ne prouve qu'une cure de jus 'détoxifie' le corps au-delà de ce que fait naturellement le foie et les reins. Les jus peuvent apporter vitamines et antioxydants mais sont pauvres en fibres et riches en sucres. Le vrai détox : soutenir les émonctoires naturels." },
    { question: "Qu'est-ce que le jeûne de Ramadan pratiqué par 1,8 milliard de musulmans et ses effets santé ?", answers: ["Un jeûne total sans eau ni nourriture 24h/24", "Jeûne de l'aube au coucher du soleil (environ 12-16h) pendant 30 jours — études montrant effets bénéfiques sur le métabolisme", "Un jeûne uniquement spirituel sans effets physiques", "Un jeûne de 3 jours uniquement"], correct: 1, explanation: "Le Ramadan est le plus grand événement mondial de jeûne intermittent : 1,8 milliard de personnes jeûnent de l'aube au coucher du soleil. Des études (INTERMAP Ramadan) montrent : réduction du cholestérol LDL, amélioration de la glycémie à jeun, perte de graisse viscérale. Le timing (manger la nuit vs le jour) a moins d'effets bénéfiques que le jeûne de jour classique." },
    { question: "Quels sont les signes que le corps commence à se régénérer pendant un jeûne prolongé (3-5 jours) ?", answers: ["Aucun signe visible", "Réduction de l'inflammation, disparition des douleurs chroniques, clarté mentale (cétones), régénération du système immunitaire", "Uniquement perte de poids", "Signes uniquement dangereux"], correct: 1, explanation: "Lors d'un jeûne prolongé (étudié par Valter Longo, USC) : J1-2 épuisement glycogène + cétose, J3 autophagie maximale + clarté mentale, J4-5 régénération des cellules souches immunitaires. La refeeding (reprise alimentaire) est cruciale : légumes cuits, soupes, progressif. Valter Longo a développé la Fasting Mimicking Diet (FMD) de 5 jours." },
    { question: "Quels aliments soutiennent naturellement le foie, organe principal de détoxification ?", answers: ["Alcool en petites quantités", "Artichaut, radis noir, chardon-marie, citron le matin, betterave, brocoli, œufs (choline)", "Uniquement les jus verts commerciaux", "Les protéines animales en grande quantité"], correct: 1, explanation: "Le foie traite 1,5L de sang par minute. Aliments hépatoprotecteurs prouvés : Artichaut (cynarine → bile), Radis noir (drainage biliaire), Chardon-marie/silymarine (régénérateur hépatique, le plus étudié), Citron à jeun (alcalinisant, stimule bile), Brocoli/brassicas (sulforaphane), Betterave (bétaïne), Curcuma (curcumine hépatoprotectrice)." },
    { question: "Combien d'heures de jeûne sont nécessaires pour que l'autophagie s'active significativement ?", answers: ["2-4 heures", "12-14 heures minimum, maximum vers 24-48h", "1 heure après le dernier repas", "Seulement après 72h de jeûne"], correct: 1, explanation: "L'autophagie commence à s'activer après environ 12-14h de jeûne et augmente progressivement jusqu'à 24-48h. Elle dépend aussi du niveau d'activité physique (le sport accélère l'activation), de la restriction calorique et des niveaux d'insuline (une faible insuline active mTOR → autophagie). La protéine mTOR est le frein principal de l'autophagie." },
    { question: "Quelles populations ne doivent PAS pratiquer le jeûne intermittent sans supervision médicale ?", answers: ["Uniquement les personnes âgées de plus de 80 ans", "Femmes enceintes/allaitantes, enfants/adolescents, diabétiques type 1, troubles alimentaires, sous certains médicaments", "Personne — le jeûne est sans risque pour tous", "Uniquement les personnes très maigres (IMC < 18)"], correct: 1, explanation: "Contre-indications au jeûne intermittent : grossesse et allaitement (besoins nutritionnels élevés), enfants et adolescents (croissance), diabétiques sous insuline ou sulfamides (risque hypoglycémie), antécédents de troubles alimentaires (anorexie, boulimie), certains médicaments nécessitant prise alimentaire. Toujours consulter un médecin avant de commencer." },
  ],
  tips: ["Le Prix Nobel 2016 de médecine a récompensé la découverte de l'autophagie — le jeûne est scientifiquement validé", "Le jeûne de Ramadan pratiqué par 1,8 milliard de personnes est la plus grande étude mondiale du jeûne intermittent", "L'artichaut, le radis noir et le chardon-marie soutiennent naturellement votre foie — la vraie détox"],
};
export default quizJeuneDetox;
