/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizNutrition = {
  title: "Nutrition & Alimentation Saine",
  description: "Découvrez les secrets d'une alimentation optimale pour votre santé et votre énergie !",
  emoji: "🥗",
  questions: [
    { question: "Qu'est-ce que l'index glycémique (IG) et pourquoi est-il important ?", answers: ["La teneur en sucre d'un aliment", "La vitesse à laquelle un aliment fait monter la glycémie — IG élevé = pic de sucre puis fringale", "Le nombre de calories d'un aliment", "La quantité de glucides totaux"], correct: 1, explanation: "L'IG mesure la vitesse d'élévation de la glycémie après consommation. IG élevé (pain blanc, sucre, riz blanc) : pic glycémique rapide → insuline → stockage en graisse → fringale. IG bas (légumineuses, légumes, fruits entiers) : énergie stable, satiété durable. Concept clé pour la prévention du diabète et la gestion du poids." },
    { question: "Quels sont les 3 macronutriments essentiels et leurs rôles ?", answers: ["Vitamines, minéraux, fibres", "Glucides (énergie), protéines (construction), lipides (hormones, cellules, absorption vitamines)", "Sucres, sel, graisses", "Calories, protéines, eau"], correct: 1, explanation: "Les 3 macronutriments : Glucides (4 kcal/g) = carburant principal du cerveau et muscles. Protéines (4 kcal/g) = construction et réparation des tissus, enzymes, hormones. Lipides (9 kcal/g) = membranes cellulaires, hormones stéroïdiennes, absorption vitamines ADEK, cerveau (60% de graisses). Tous trois sont indispensables." },
    { question: "Qu'est-ce que le microbiome intestinal et pourquoi est-il surnommé le 2ème cerveau ?", answers: ["Les bactéries mauvaises à éliminer", "Les 100 000 milliards de micro-organismes intestinaux influençant l'immunité, l'humeur, le poids et la santé globale", "Uniquement les probiotiques des yaourts", "Les enzymes digestives du pancréas"], correct: 1, explanation: "Le microbiome intestinal = 100 000 milliards de micro-organismes, 10 fois plus que nos cellules humaines. Il produit 95% de la sérotonine (hormone du bonheur), influence le système immunitaire (70% dans l'intestin), le poids, l'anxiété et même les décisions. Une alimentation riche en fibres et fermentés l'entretient." },
    { question: "Quels aliments sont les plus riches en oméga-3, acides gras essentiels anti-inflammatoires ?", answers: ["Les huiles végétales raffinées", "Poissons gras (sardine, maquereau, saumon), graines de lin, noix, huile de colza", "Viandes rouges et charcuteries", "Produits laitiers entiers"], correct: 1, explanation: "Les oméga-3 (EPA, DHA) sont essentiels : anti-inflammatoires, protecteurs cardiovasculaires, cerveau (DHA = 25% du cerveau), yeux. Meilleures sources : sardines, maquereaux, harengs (petits poissons moins contaminés), graines de lin broyées, noix, huile de colza. Objectif : ratio oméga-6/oméga-3 inférieur à 4:1 (alimentation moderne souvent à 20:1)." },
    { question: "Qu'est-ce que le jeûne intermittent 16:8 et quels sont ses bénéfices prouvés ?", answers: ["Jeûner 16 jours sur 8 semaines", "Manger pendant une fenêtre de 8 heures, jeûner 16 heures — active l'autophagie et brûle les graisses", "Ne manger qu'un repas par jour", "Sauter le dîner uniquement"], correct: 1, explanation: "Le jeûne intermittent 16:8 (ex: manger de 12h à 20h, jeûner de 20h à 12h) : bénéfices prouvés : perte de graisses (sans perte musculaire), réduction inflammatoire, autophagie (nettoyage cellulaire — Nobel 2016 Yoshinori Ohsumi), amélioration sensibilité insulinique, longévité. Contre-indiqué : grossesse, troubles alimentaires, certains diabétiques." },
    { question: "Quels sont les superaliments de la cuisine antillaise particulièrement nutritifs ?", answers: ["Frites de banane plantain uniquement", "Fruit à pain, patate douce, chou calalou, goyave, papaye, manioc, christophine", "Riz blanc et haricots rouges uniquement", "Les épices seulement"], correct: 1, explanation: "La cuisine antillaise regorge de superaliments : fruit à pain (riche en fibres, potassium), patate douce (bêta-carotène, IG modéré), calalou (fer, calcium), goyave (5x plus de vitamine C que l'orange), papaye (papaïne digestive, bêta-carotène), manioc (résistant à la sécheresse), christophine (hypotensive). Un trésor nutritionnel local !" },
    { question: "Qu'est-ce que l'inflammation chronique de bas grade et comment l'alimentation l'influence-t-elle ?", answers: ["Une infection visible et aiguë", "Un état inflammatoire silencieux et persistant — alimentation ultra-transformée l'aggrave, alimentation anti-inflammatoire le réduit", "Uniquement causée par les blessures", "Un marqueur d'inflammation uniquement chez les personnes âgées"], correct: 1, explanation: "L'inflammation chronique silencieuse est à la base de la plupart des maladies chroniques : maladies cardiovasculaires, diabète T2, cancer, Alzheimer. Alimentation pro-inflammatoire : sucres raffinés, huiles végétales riches en oméga-6, ultra-transformés. Anti-inflammatoire : légumes colorés, fruits, poissons gras, curcuma, huile d'olive, herbes aromatiques." },
    { question: "Combien de verres d'eau faut-il boire par jour selon les recommandations générales ?", answers: ["1 à 2 verres suffisent", "8 verres (1,5 à 2 litres) — plus par forte chaleur ou sport", "5 litres minimum", "La soif suffit à guider"], correct: 1, explanation: "La recommandation générale est 1,5 à 2 litres par jour (environ 8 verres), plus en cas de chaleur intense (Antilles : +0,5 à 1L), de sport ou de fièvre. La soif est un signal tardif de déshydratation (déjà -1% d'eau = -10% de performance cognitive). Urines jaune pâle = bonne hydratation." },
    { question: "Qu'est-ce que la chrononutrition, science de l'heure des repas ?", answers: ["Manger très lentement", "L'heure des repas influence profondément le métabolisme — le corps utilise différemment les aliments selon l'heure", "Ne manger que des aliments de saison", "Compter les calories à chaque repas"], correct: 1, explanation: "La chrononutrition (Alain Delabos, Dr Satchin Panda) : le même repas pris à des heures différentes a des effets métaboliques différents. Le matin : métabolisme actif, glucides et graisses bien gérés. Le soir : moins efficace, stockage plus probable. L'horloge biologique circadienne régule les enzymes digestives, l'insuline et le métabolisme." },
    { question: "Quelle vitamine produite par le soleil est en déficit chez 80% des Antillais malgré le soleil tropical ?", answers: ["Vitamine C", "Vitamine D — déficit paradoxal car peur du soleil, travail en intérieur et pigmentation cutanée", "Vitamine B12", "Vitamine A"], correct: 1, explanation: "Paradoxalement, des études montrent un déficit en vitamine D même aux Antilles : peur du soleil (cancer), travail en intérieur, climatisation, pigmentation cutanée (melanine réduit la synthèse). La vitamine D est indispensable : immunité, os, humeur, prévention de nombreux cancers. Exposition solaire 15-20 minutes/jour avant 10h ou après 16h." },
  ],
  tips: ["Les superaliments antillais (goyave, papaye, patate douce, calalou) sont parmi les plus nutritifs du monde", "Le microbiome intestinal produit 95% de votre sérotonine — votre intestin influence votre humeur directement", "Vitamine D déficitaire même aux Antilles — exposition solaire 15 min/jour avant 10h ou dosage sanguin recommandé"],
};
export default quizNutrition;
