const quizIntelligenceEmotionnelle = {
  title: "Intelligence Émotionnelle",
  description: "Maîtrisez vos émotions, développez votre empathie et transformez vos relations !",
  emoji: "❤️",
  questions: [
    { question: "Quelles sont les 4 composantes principales de l'intelligence émotionnelle selon Salovey et Mayer ?", answers: ["Joie, tristesse, colère, peur", "Percevoir, utiliser, comprendre et réguler les émotions", "QI, QE, créativité, logique", "Empathie, communication, leadership, confiance"], correct: 1, explanation: "Le modèle original de Salovey et Mayer (1990) définit 4 branches : 1. Percevoir les émotions (les reconnaître chez soi et autrui), 2. Utiliser les émotions (pour faciliter la pensée), 3. Comprendre les émotions (leur évolution), 4. Réguler les émotions (gérer les siennes et influencer celles des autres)." },
    { question: "Qu'est-ce que l'empathie cognitive, différente de l'empathie émotionnelle ?", answers: ["Ressentir exactement les mêmes émotions qu'une autre personne", "Comprendre intellectuellement le point de vue et les émotions de l'autre sans nécessairement les ressentir", "Ignorer les émotions des autres", "Être d'accord avec tout le monde"], correct: 1, explanation: "L'empathie émotionnelle = ressentir ce que l'autre ressent (risque de surcharge émotionnelle). L'empathie cognitive = comprendre le point de vue et l'état émotionnel de l'autre sans le ressentir soi-même. Les grands leaders utilisent principalement l'empathie cognitive : elle permet d'aider sans se noyer." },
    { question: "Qu'est-ce que le 'hijacking amygdalien' (amygdala hijack) en intelligence émotionnelle ?", answers: ["Une technique de méditation", "La prise de contrôle soudaine du cerveau émotionnel sur le rationnel dans les moments de stress intense", "Un type de migraine", "Une méthode de négociation"], correct: 1, explanation: "L'amygdala hijack (Daniel Goleman) est le moment où l'amygdale (cerveau émotionnel) prend le contrôle en situation de menace perçue, court-circuitant le cortex préfrontal (raison). Résultat : réactions impulsives qu'on regrette. La conscience de ce mécanisme et la respiration profonde permettent de le désamorcer." },
    { question: "Quelle technique simple permet de gérer une émotion forte en 90 secondes selon la neurobiologiste Jill Bolte Taylor ?", answers: ["La nier complètement", "Identifier et accueillir l'émotion sans jugement — la vague neurochimique dure 90 secondes", "La supprimer par la pensée positive", "Distraire son attention immédiatement"], correct: 1, explanation: "Jill Bolte Taylor (neuroscientifique qui a eu un AVC) explique qu'une émotion provoque une vague neurochimique qui dure 90 secondes. Si on laisse l'émotion passer sans la nourrir de pensées, elle se dissout naturellement. Ce sont les pensées qui entretiennent l'émotion au-delà des 90 secondes." },
    { question: "Qu'est-ce que la Communication Non-Violente (CNV) de Marshall Rosenberg ?", answers: ["Ne jamais exprimer de désaccord", "Un processus en 4 étapes : Observation, Sentiment, Besoin, Demande — sans jugement ni reproche", "Parler doucement en toutes circonstances", "Éviter tout conflit"], correct: 1, explanation: "La CNV de Rosenberg : 1. Observation (faits sans jugement), 2. Sentiment (ce que je ressens), 3. Besoin (besoin sous-jacent non satisfait), 4. Demande (concrète, positive, négociable). Exemple : 'Quand tu rentres tard sans prévenir (O), je me sens inquiète (S) car j'ai besoin de sécurité (B). Pourrais-tu m'envoyer un message (D) ?'" },
    { question: "Pourquoi les personnes avec une haute intelligence émotionnelle réussissent-elles mieux professionnellement ?", answers: ["Elles travaillent plus longtemps", "Elles gèrent mieux le stress, les relations et les conflits — compétences indispensables en équipe", "Elles ont un QI plus élevé", "Elles ne ressentent pas d'émotions négatives"], correct: 1, explanation: "TalentSmart a étudié 500 000 personnes : le QE est le plus fort prédicteur de performance professionnelle, expliquant 58% du succès. 90% des top performers ont un QE élevé. Les personnes avec haut QE gagnent en moyenne 29 000$ de plus par an. Le QE se développe tout au long de la vie, contrairement au QI." },
    { question: "Qu'est-ce que la régulation émotionnelle par 'recadrage cognitif' (cognitive reframing) ?", answers: ["Ignorer ses émotions négatives", "Changer volontairement la perspective sur une situation pour modifier l'émotion associée", "Prendre des médicaments", "Distraire son attention avec des activités"], correct: 1, explanation: "Le recadrage cognitif consiste à changer consciemment l'interprétation d'une situation. Ex: 'J'ai perdu mon emploi' → 'J'ai l'opportunité de trouver mieux'. Les émotions ne viennent pas des événements mais de l'interprétation qu'on en fait. Base de la thérapie cognitivo-comportementale (TCC)." },
    { question: "Comment développer son intelligence émotionnelle au quotidien selon les experts ?", answers: ["Éviter toute situation stressante", "Journal émotionnel, méditation, écoute active, feedback et thérapie si nécessaire", "Regarder des films tristes", "Lire des livres de philosophie uniquement"], correct: 1, explanation: "Pratiques prouvées pour développer le QE : 1. Journal émotionnel (nommer ses émotions précisément), 2. Méditation pleine conscience, 3. Écoute active sans interruption, 4. Demander du feedback honnête à ses proches, 5. Thérapie ou coaching. Le QE augmente significativement avec la pratique intentionnelle." },
    { question: "Qu'est-ce que la contagion émotionnelle et comment l'utiliser positivement ?", answers: ["Une maladie psychologique", "Le transfert inconscient d'émotions entre personnes — les émotions sont littéralement contagieuses", "La manipulation émotionnelle", "Un trouble de la personnalité"], correct: 1, explanation: "La contagion émotionnelle est le phénomène par lequel les émotions se transmettent d'une personne à l'autre via les neurones miroirs. Un leader ou parent avec émotions positives les répand autour de lui. C'est pourquoi l'entourage influence profondément notre état émotionnel — choisir ses fréquentations est vital." },
    { question: "Qu'est-ce que la vulnérabilité selon Brené Brown, chercheuse américaine mondialement reconnue ?", answers: ["Une faiblesse à cacher absolument", "Le courage de se montrer authentique malgré l'incertitude — source de connexion et d'innovation", "Un défaut de caractère", "Un état temporaire à surmonter vite"], correct: 1, explanation: "Brené Brown (20 ans de recherche sur la honte et la vulnérabilité) a découvert que la vulnérabilité n'est pas une faiblesse mais le berceau de l'amour, de l'appartenance, de la joie et de la créativité. Les personnes épanouies embrassent la vulnérabilité au lieu de la fuir. Son TED Talk est le 4ème le plus vu de l'histoire." },
  ],
  tips: ["90 secondes suffisent pour laisser passer une émotion si on ne l'alimente pas de pensées", "Le QE se développe tout au long de la vie — contrairement au QI qui reste relativement stable", "La CNV transforme les conflits en connexions — 4 étapes : Observation, Sentiment, Besoin, Demande"],
};
export default quizIntelligenceEmotionnelle;
