const quizDroitNumerique2 = {
  title: "Droits du Numérique — Réseaux & Plateformes",
  description: "Vos droits face aux géants du numérique, aux réseaux sociaux et aux plateformes digitales !",
  emoji: "📱",
  questions: [
    { question: "Peut-on légalement publier la photo de quelqu'un sur les réseaux sociaux sans son autorisation ?", answers: ["Oui si c'est dans un lieu public", "Non — le droit à l'image s'applique partout, même en lieu public, sauf exception d'information publique", "Oui si c'est un personnage public", "Oui si on ne l'identifie pas par son nom"], correct: 1, explanation: "Le droit à l'image (art. 9 Code Civil) protège toute personne y compris en lieu public. Exceptions : personnages publics dans l'exercice de leur fonction (politiciens lors d'un discours), manifestations publiques (foules indistinctes), actualité. Mais même une célébrité peut s'opposer à une photo dans sa vie privée. Violation : jusqu'à 45 000€ d'amende." },
    { question: "Qu'est-ce que la liberté d'expression sur internet et ses limites légales en France ?", answers: ["Absolue — tout peut être dit en ligne", "Liberté garantie par la loi mais limitée : injure, diffamation, incitation à la haine, négationnisme, menace restent des infractions en ligne comme offline", "Uniquement pour les médias officiels", "Limitée aux sujets non politiques"], correct: 1, explanation: "La liberté d'expression (art. 11 DDHC) s'applique en ligne mais les mêmes limites légales s'appliquent : injure publique (1 an prison, 45 000€), diffamation (même peine), incitation à la haine raciale/homophobie (1 an prison, 45 000€), négationnisme (loi Gayssot), menaces. La loi Avia (2020) a renforcé les obligations des plateformes de supprimer les contenus haineux." },
    { question: "Qu'est-ce que le cybersquatting et comment protéger son nom de domaine ?", answers: ["Pirater un site web", "Enregistrement de mauvaise foi d'un nom de domaine correspondant à une marque ou nom d'une personne pour le revendre", "Utiliser l'espace disque d'un autre site", "Copier le design d'un site concurrent"], correct: 1, explanation: "Le cybersquatting consiste à enregistrer un nom de domaine identique ou similaire à une marque ou nom d'une personne connue, dans l'intention de le revendre à prix élevé. Recours : procédure UDRP (Uniform Domain Name Dispute Resolution Policy) devant l'ICANN, plus rapide et moins coûteuse qu'un tribunal. Protégez votre marque en enregistrant simultanément votre nom de domaine." },
    { question: "Quels sont vos droits si vous êtes victime de fraude sur une plateforme e-commerce ?", answers: ["Aucun recours contre les plateformes", "Signalement à la DGCCRF, demande de remboursement à votre banque (chargeback), dépôt de plainte, contact de la plateforme", "Seulement si vous avez payé par carte bancaire", "Uniquement si le montant dépasse 100€"], correct: 1, explanation: "En cas de fraude e-commerce : 1. Contactez immédiatement votre banque pour un chargeback (opposition sur paiement par carte, possible jusqu'à 13 mois), 2. Signalez sur signal.conso.gouv.fr et cybermalveillance.gouv.fr, 3. Déposez plainte au commissariat (emportez tous les justificatifs), 4. Contactez la plateforme (Amazon, eBay ont des garanties acheteur). Conservez toutes les preuves." },
    { question: "Qu'est-ce que la propriété intellectuelle appliquée aux créations numériques ?", answers: ["Elle ne s'applique pas au numérique", "Tout contenu original créé (texte, photo, vidéo, code, musique) est protégé automatiquement par le droit d'auteur dès sa création", "Uniquement si enregistré à l'INPI", "Seulement pour les entreprises commerciales"], correct: 1, explanation: "Le droit d'auteur protège automatiquement toute œuvre originale dès sa création, sans formalité ni enregistrement (contrairement aux marques et brevets). Durée : vie de l'auteur + 70 ans. S'applique aux créations numériques : photos, vidéos, articles, code source, illustrations, musiques. Copier sans autorisation = contrefaçon (3 ans prison, 300 000€ amende)." },
    { question: "Peut-on légalement créer un site identique à celui d'un concurrent en changeant juste les couleurs ?", answers: ["Oui si on change suffisamment", "Non — la concurrence déloyale par parasitisme et la contrefaçon de design protègent l'apparence d'un site original", "Oui si le site concurrent n'est pas déposé", "Oui si on est dans un pays différent"], correct: 1, explanation: "Copier l'apparence d'un site (design, charte graphique, mise en page originale) constitue une concurrence déloyale et potentiellement une contrefaçon. La jurisprudence sanctionne le parasitisme (profiter du travail d'un concurrent). Le design d'un site peut être protégé par le droit d'auteur (si original) ou par un dessin et modèle déposé à l'INPI." },
    { question: "Qu'est-ce que la responsabilité des hébergeurs de contenu selon la loi française ?", answers: ["Responsables de tout contenu publié sur leur plateforme", "Responsabilité limitée (safe harbor) : non responsables s'ils retirent promptement les contenus illicites signalés", "Aucune responsabilité quelle que soit la situation", "Responsables uniquement des contenus commerciaux"], correct: 1, explanation: "La LCEN (2004) et le DSA européen (2022) : les hébergeurs (Facebook, YouTube, TikTok) ne sont pas responsables des contenus publiés par les utilisateurs tant qu'ils les retirent promptement après signalement. Obligations renforcées pour les très grandes plateformes (DSA) : transparence des algorithmes, signalement simplifié, coordination avec les autorités nationales." },
    { question: "Quel est le cadre légal de la revente de produits numériques (jeux vidéo, ebooks) en Europe ?", answers: ["La revente numérique est toujours légale", "Arrêt UsedSoft (CJUE 2012) : revente de logiciels légaux possible. Mais ebooks, musique et films sont généralement sous licence non transférable", "Totalement illégale", "Légale uniquement entre particuliers sans profit"], correct: 1, explanation: "La Cour de Justice de l'UE (arrêt UsedSoft, 2012) a établi que les logiciels achetés en ligne (licence perpétuelle) peuvent être revendus. Mais les ebooks, films en streaming, musique restent généralement sous licences d'utilisation personnelle non transférables selon les CGU des plateformes (Amazon Kindle, iTunes). Un projet de directive européenne est en discussion pour harmoniser les règles." },
    { question: "Qu'est-ce que le droit à la portabilité des données selon le RGPD ?", answers: ["Droit d'emporter son ordinateur partout", "Droit de récupérer ses données personnelles dans un format lisible et de les transférer vers un autre service", "Droit de stocker ses données dans le cloud", "Droit d'accéder à internet depuis n'importe quel pays"], correct: 1, explanation: "Le droit à la portabilité (art. 20 RGPD) : vous pouvez demander à tout responsable de traitement de vous fournir vos données dans un format structuré, couramment utilisé et lisible par machine (JSON, CSV) pour les transférer à un autre service. Applicable aux données que vous avez fournies activement. Permet de quitter une plateforme sans perdre vos données (historique, contacts)." },
    { question: "Comment signaler un contenu illégal (pédopornographie, terrorisme, haine) en France ?", answers: ["Uniquement via la police physiquement", "Plateforme PHAROS (internet-signalement.gouv.fr) — traité par l'Office Central de Lutte contre la Criminalité liée aux Technologies de l'Information", "Directement à l'hébergeur uniquement", "Signalement impossible pour les contenus hébergés à l'étranger"], correct: 1, explanation: "PHAROS (Plateforme d'Harmonisation d'Analyse de Recoupement et d'Orientation des Signalements) gérée par la Police Nationale permet de signaler : pédopornographie, apologie du terrorisme, incitation à la haine, arnaque en ligne. Traité par l'OCLCTIC. Les plateformes ont l'obligation légale (DSA) de retirer sous 24h les contenus illégaux signalés par les autorités." },
  ],
  tips: ["Toute photo publiée de quelqu'un sans autorisation viole le droit à l'image — même en lieu public", "Vos données sur les réseaux sociaux vous appartiennent — exercez votre droit à la portabilité RGPD", "PHAROS (internet-signalement.gouv.fr) pour signaler tout contenu illégal — traité par la police nationale"],
};
export default quizDroitNumerique2;
