/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizDepassementSoi = {
  title: "Dépassement de Soi — Psychologie de la Performance",
  description: "Les secrets mentaux des champions, explorateurs et leaders qui ont repoussé les limites humaines !",
  emoji: "🏆",
  questions: [
    { question: "Qu'est-ce que le Flow selon Mihaly Csikszentmihalyi, psychologue hongrois ?", answers: ["Un état de relaxation profonde", "Un état optimal de conscience où on est totalement absorbé dans une activité avec performance maximale", "Une technique de respiration", "Un état de transe méditatif"], correct: 1, explanation: "Le Flow est l'état de concentration totale où le temps disparaît et la performance est maximale. Il se produit quand le défi est légèrement supérieur aux compétences. Les sportifs l'appellent 'être dans la zone'. Conditions : objectif clair, feedback immédiat, concentration totale." },
    { question: "Quelle est la règle des 10 000 heures d'Anders Ericsson popularisée par Malcolm Gladwell ?", answers: ["Il faut 10 000 heures pour être heureux", "La pratique délibérée de 10 000 heures serait nécessaire pour atteindre l'excellence dans un domaine", "10 000 heures de sommeil pour récupérer", "Lire 10 000 livres pour être expert"], correct: 1, explanation: "Anders Ericsson a étudié les experts (violonistes, échecs, sport) et trouvé que l'excellence requiert environ 10 000 heures de PRATIQUE DÉLIBÉRÉE (pas juste de la répétition, mais un entraînement ciblé sur les faiblesses). Malcolm Gladwell l'a popularisé dans 'Outliers'. Note : la qualité de la pratique compte plus que la quantité." },
    { question: "Qu'est-ce que la résilience psychologique ?", answers: ["L'absence totale de souffrance", "La capacité à se relever et à se reconstruire après les épreuves, souvent plus fort qu'avant", "L'indifférence émotionnelle", "Éviter les situations difficiles"], correct: 1, explanation: "La résilience est la capacité à rebondir après un traumatisme, un échec ou une adversité. Le concept de 'croissance post-traumatique' montre que certaines personnes sortent PLUS FORTES des épreuves. Boris Cyrulnik, psychiatre guadeloupéen-français, est le pionnier de la résilience en France." },
    { question: "Qu'est-ce que la discipline stoïcienne du 'Dichotomie du contrôle' enseignée par Épictète ?", answers: ["Contrôler tout ce qui se passe", "Se concentrer uniquement sur ce qui dépend de nous — ignorer ce qui n'en dépend pas", "Contrôler ses émotions par la force", "Planifier chaque détail de sa vie"], correct: 1, explanation: "Épictète (esclave devenu philosophe) enseignait : certaines choses dépendent de nous (pensées, jugements, désirs, actions), d'autres non (corps, réputation, richesse, opinions des autres). La liberté et la paix viennent de se concentrer exclusivement sur ce qui dépend de nous. Base du stoïcisme moderne (Ryan Holiday)." },
    { question: "Quelle pratique matinale David Goggins, ancien Navy SEAL, recommande pour le dépassement de soi ?", answers: ["Dormir 10 heures pour récupérer", "Confronter intentionnellement l'inconfort chaque matin pour renforcer la volonté", "Méditer 2 heures avant toute activité", "Jeûner 24 heures par semaine"], correct: 1, explanation: "David Goggins prône la confrontation délibérée et quotidienne de l'inconfort pour construire la résilience mentale. Son concept de 'Callous the Mind' (durcir le mental comme la peau) : faire régulièrement ce qu'on redoute — bain froid, sport intense, conversations difficiles — crée une réserve de force mentale." },
    { question: "Qu'est-ce que l'intelligence émotionnelle selon Daniel Goleman et pourquoi est-elle plus prédictive du succès que le QI ?", answers: ["La capacité à mémoriser des émotions", "La capacité à reconnaître, comprendre et gérer ses propres émotions et celles des autres", "Ne jamais montrer ses émotions en public", "Être toujours positif"], correct: 1, explanation: "Daniel Goleman (1995) a montré que l'intelligence émotionnelle (QE) prédit mieux le succès que le QI. Le QE comprend : conscience de soi, maîtrise de soi, motivation, empathie, compétences sociales. 90% des top performers ont un QE élevé selon ses recherches sur 500 000 personnes." },
    { question: "Qu'est-ce que la 'règle des 5 secondes' de Mel Robbins pour vaincre l'hésitation ?", answers: ["Compter jusqu'à 5 avant de s'endormir", "Au moment d'hésiter, compter 5-4-3-2-1 et agir immédiatement avant que le cerveau sabote l'action", "Attendre 5 secondes avant de répondre en colère", "Faire 5 respirations profondes avant une décision"], correct: 1, explanation: "Mel Robbins a découvert que le cerveau a une fenêtre de 5 secondes avant d'activer des mécanismes de sabotage. Compter 5-4-3-2-1 comme un lancement de fusée et agir immédiatement contourne ce mécanisme. Simple mais puissant : son TED Talk est l'un des plus vus au monde." },
    { question: "Qu'est-ce que le 'Stoïcisme négatif' ou prémeditation malorum utilisé par les champions ?", answers: ["Penser négativement en permanence", "Visualiser intentionnellement ce qui pourrait mal tourner pour s'y préparer et réduire la peur", "Éviter tout risque", "Se concentrer sur les échecs passés"], correct: 1, explanation: "La Premeditatio Malorum (stoïcisme) consiste à visualiser intentionnellement les pires scénarios possibles — non pour avoir peur mais pour s'y préparer et réaliser qu'on peut y faire face. Tim Ferriss l'appelle 'fear setting'. Cette pratique réduit paradoxalement l'anxiété et augmente l'action." },
    { question: "Selon les études sur les ultra-endurances (marathons, Iron Man), qu'est-ce qui limite en premier le corps humain ?", answers: ["Les muscles", "Le cœur et les poumons", "Le mental — le cerveau envoie des signaux d'arrêt bien avant les limites physiques réelles", "Le manque d'eau"], correct: 2, explanation: "Les recherches de Tim Noakes sur les limites humaines montrent que le cerveau (Gouverneur Central) envoie des signaux de fatigue et d'arrêt bien avant les vraies limites physiques, comme mécanisme de protection. Les ultramarathoniens apprennent à négocier avec ce gouverneur mental — leurs limites physiques réelles sont bien au-delà." },
    { question: "Que recommande Tony Robbins comme première pratique quotidienne pour conditionner un état mental optimal ?", answers: ["Lire 30 minutes chaque matin", "La triade du mouvement physique, de la respiration intense et de la visualisation — Priming", "Faire la liste de ses objectifs", "Méditer 1 heure en silence total"], correct: 1, explanation: "Tony Robbins enseigne le 'Priming' : 10 minutes le matin combinant respiration rythmique intense (Kapalbhati), gratitude profonde et visualisation. L'idée : l'état mental optimal se CRÉE intentionnellement, il ne s'attend pas. Le mouvement physique change immédiatement la biochimie du cerveau." },
  ],
  tips: ["Le Flow arrive quand le défi dépasse légèrement vos compétences — cherchez cet équilibre", "Boris Cyrulnik, pionnier de la résilience, est né à Bordeaux de parents juifs ukrainiens — lui-même résilient extraordinaire", "10 000 heures de pratique DÉLIBÉRÉE (ciblée sur les faiblesses) — pas juste de la répétition mécanique"],
};
export default quizDepassementSoi;
