const quizSingapourEssentiel = {
  title: "Singapour — Essentiel Voyage & Culture",
  description: "Droits, règles, culture et bons à savoir avant d'aller à Singapour — city-state aux lois très strictes !",
  emoji: "🇸🇬",
  questions: [
    { question: "🛂 Faut-il un visa pour visiter Singapour depuis la France ?", answers: ["Oui visa obligatoire", "Non, 30 jours sans visa pour passeport français", "ESTA obligatoire", "Visa à l'arrivée seulement"], correct: 1, explanation: "Les ressortissants français peuvent entrer à Singapour sans visa pour un séjour touristique de 30 jours (depuis 2023, 90 jours pour les Européens dans certains cas). Le passeport doit être valide 6 mois au-delà de la date de départ." },
    { question: "🚬 Quelle est l'amende pour avoir jeté un mégot de cigarette par terre à Singapour ?", answers: ["50 SGD", "300 SGD", "1 000 SGD", "Pas d'amende"], correct: 2, explanation: "Jeter un déchet à Singapour, y compris un mégot, peut coûter jusqu'à 1 000 SGD (environ 700€) pour une première infraction. Singapour est l'une des villes les plus propres du monde grâce à ces lois strictes et à leur application rigoureuse." },
    { question: "🍬 Depuis 1992, quel produit est interdit d'importation et de vente à Singapour ?", answers: ["La cigarette", "Le chewing-gum", "L'alcool fort", "Les drogues douces"], correct: 1, explanation: "Le chewing-gum est interdit à Singapour depuis 1992 (sauf usage médical sur prescription). Son importation est illégale. La raison : les gens collaient des chewing-gums sur les portes du métro, bloquant les capteurs. Amende pouvant atteindre 100 000 SGD." },
    { question: "💀 Quelle est la peine pour trafic de drogue à Singapour ?", answers: ["Prison ferme", "Amende très lourde", "Peine de mort obligatoire selon les quantités", "Expulsion du pays"], correct: 2, explanation: "Singapour applique la peine de mort OBLIGATOIRE pour le trafic de drogue au-delà de certains seuils (ex: 15g d'héroïne, 500g de cannabis). Même être en transit avec des drogues dans l'aéroport est extrêmement dangereux." },
    { question: "🚇 Peut-on manger ou boire dans le métro (MRT) de Singapour ?", answers: ["Oui librement", "Non, interdit avec amende de 500 SGD", "Seulement l'eau", "Seulement dans les gares"], correct: 1, explanation: "Manger, boire (même de l'eau), fumer dans le métro de Singapour est INTERDIT avec une amende de 500 SGD (350€). Les trains et stations sont impeccables grâce à ces règles. Le MRT est l'un des meilleurs systèmes de transport au monde." },
    { question: "🌡️ Quel est le climat à Singapour toute l'année ?", answers: ["Tropical humide 27-33°C avec pluies fréquentes", "Tempéré comme en France", "Désertique et sec", "Tropical sec en été"], correct: 0, explanation: "Singapour est à 1° du nord de l'équateur. Température constante de 27-33°C toute l'année avec humidité de 70-90%. Des averses tropicales courtes et intenses peuvent survenir n'importe quand. Vêtements légers mais ombrelle ou imperméable recommandés." },
    { question: "💰 Singapour est l'un des pays avec le coût de la vie le plus élevé au monde. Combien coûte un repas simple dans un hawker centre ?", answers: ["20-30 SGD", "3-8 SGD", "50 SGD minimum", "15-20 SGD"], correct: 1, explanation: "Les hawker centres sont des centres de restauration populaires où les Singapouriens mangent quotidiennement pour 3-8 SGD (2-6€). C'est la meilleure option budget. Les restaurants classiques coûtent 20-50 SGD. Les hawker centres ont leur culture propre au patrimoine UNESCO." },
    { question: "🏳️ Singapour reconnaît-il le mariage homosexuel ?", answers: ["Oui légalisé en 2022", "Non, et la relation entre hommes était illégale jusqu'en 2022", "Oui depuis 2015", "Illégal avec prison"], correct: 1, explanation: "La Section 377A (criminalisant les relations entre hommes) a été abrogée en novembre 2022. Cependant, Singapour ne reconnaît toujours pas le mariage homosexuel en 2024. La société reste conservatrice sur ce sujet malgré son ouverture économique." },
    { question: "🌆 Quelle est la superficie de Singapour, l'un des plus petits pays du monde ?", answers: ["100 km²", "728 km²", "2 000 km²", "300 km²"], correct: 1, explanation: "Singapour ne fait que 728 km² (légèrement plus grand que Paris + petite couronne). Malgré sa taille, c'est l'un des pays les plus riches du monde avec un PIB par habitant de 65 000 USD. Sa position stratégique en fait le 2ème port mondial." },
    { question: "🔌 Quel type de prise électrique utilise Singapour ?", answers: ["Type A américain", "Type C européen", "Type G britannique à 3 broches", "Type F"], correct: 2, explanation: "Singapour utilise les prises de type G, identiques au Royaume-Uni, avec 3 broches rectangulaires et tension de 230V. Un adaptateur est obligatoire pour les appareils français. La plupart des hôtels ont des adaptateurs disponibles à la réception." },
  ],
  tips: ["Zéro tolérance pour les drogues — peine de mort possible pour le trafic", "Ne pas jeter de déchets — amende 1 000 SGD minimum", "Hawker centres pour manger local et bon marché — meilleure expérience culinaire de Singapour"],
};
export default quizSingapourEssentiel;
