const quizAllemagneEssentiel = {
  title: "Allemagne — Essentiel Voyage & Culture",
  description: "Droits, règles, culture et bons à savoir avant d'aller en Allemagne !",
  emoji: "🇩🇪",
  questions: [
    { question: "🛂 Faut-il un visa pour aller en Allemagne depuis la France ?", answers: ["Oui, visa Schengen", "Non, espace Schengen libre", "ESTA obligatoire", "Passeport biométrique seul"], correct: 1, explanation: "L'Allemagne est dans l'espace Schengen. Les citoyens français et guadeloupéens (français) peuvent y circuler librement avec carte d'identité ou passeport, sans visa ni formalité." },
    { question: "🚗 Quelle est la particularité unique de l'autoroute allemande (Autobahn) ?", answers: ["Péage obligatoire partout", "Pas de limitation de vitesse sur certaines sections", "Réservée aux résidents", "Interdite aux étrangers"], correct: 1, explanation: "Sur environ 30% de l'Autobahn, il n'y a pas de limitation de vitesse officielle ! Une vitesse recommandée de 130 km/h existe mais n'est pas obligatoire. Certaines voitures y roulent à 200-300 km/h." },
    { question: "🍺 À quel âge peut-on acheter de la bière en Allemagne ?", answers: ["18 ans", "21 ans", "16 ans", "14 ans avec parents"], correct: 2, explanation: "En Allemagne, la bière et le vin sont légaux dès 16 ans. Les spiritueux (whisky, vodka...) sont réservés aux 18 ans et plus. L'Allemagne est le pays de la bière avec 1 300 brasseries !" },
    { question: "🔇 Quel jour est particulièrement silencieux en Allemagne par loi ?", answers: ["Lundi", "Vendredi soir", "Dimanche", "Samedi matin"], correct: 2, explanation: "Le dimanche est légalement protégé en Allemagne (Sonntagsruhe). Tondre la pelouse, faire du bruit excessif ou bricoler est interdit. Les magasins sont fermés. Cette loi est strictement respectée et peut valoir une amende." },
    { question: "♻️ L'Allemagne est championne mondiale de quoi ?", answers: ["Production automobile", "Recyclage des déchets", "Énergie solaire", "Exportation de bière"], correct: 1, explanation: "L'Allemagne recycle environ 66% de ses déchets, record mondial. Le système de consigne (Pfand) sur les bouteilles rapporte 0,25€ par bouteille. Trier ses déchets est une obligation sociale très sérieuse." },
    { question: "💶 Quel est le salaire minimum (Mindestlohn) en Allemagne en 2024 ?", answers: ["9€/heure", "12,41€/heure", "10€/heure", "15€/heure"], correct: 1, explanation: "Le salaire minimum allemand (Mindestlohn) était de 12,41€/heure en 2024, parmi les plus élevés d'Europe. Il a été introduit seulement en 2015 après des années de débat politique." },
    { question: "🚲 Quelle ville allemande est considérée comme la capitale mondiale du vélo ?", answers: ["Berlin", "Munich", "Hambourg", "Münster"], correct: 3, explanation: "Münster est connue comme la ville la plus cycliste du monde avec 40% des déplacements à vélo. Berlin et Munich ont aussi d'excellentes infrastructures cyclables. Le vélo est un mode de transport très sérieux en Allemagne." },
    { question: "🏥 Comment fonctionne la santé en Allemagne ?", answers: ["Gratuite comme en France", "Assurance maladie obligatoire publique ou privée", "Payante sans remboursement", "Réservée aux résidents depuis 5 ans"], correct: 1, explanation: "En Allemagne, l'assurance maladie est OBLIGATOIRE pour tout le monde. Il existe des caisses publiques (Krankenkasse) et privées. Les touristes doivent avoir une assurance voyage. Qualité des soins excellente." },
    { question: "🗣️ Combien de personnes parlent allemand dans le monde ?", answers: ["50 millions", "100 millions", "130 millions", "200 millions"], correct: 2, explanation: "L'allemand est parlé par environ 130 millions de personnes. C'est la langue maternelle la plus parlée d'Europe. Langue officielle en Allemagne, Autriche, Suisse, Liechtenstein et Luxembourg." },
    { question: "🏛️ Quelle est la capitale de l'Allemagne depuis 1990 ?", answers: ["Francfort", "Munich", "Hambourg", "Berlin"], correct: 3, explanation: "Berlin est redevenue la capitale de l'Allemagne réunifiée le 3 octobre 1990. Avant la réunification, Bonn était la capitale de l'Allemagne de l'Ouest. Berlin est aujourd'hui la plus grande ville d'Allemagne avec 3,7 millions d'habitants." },
  ],
  tips: ["Le dimanche tout est fermé en Allemagne — faites vos courses le samedi", "Trier ses déchets est une obligation sociale très forte", "La bière est légale à 16 ans — culture brassicole unique au monde"],
};
export default quizAllemagneEssentiel;
