const quizDroitFamille = {
  title: "Droit de la Famille",
  description: "Mariage, divorce, succession, garde des enfants — connaissez vos droits familiaux !",
  emoji: "👨‍👩‍👧‍👦",
  questions: [
    { question: "Quelles sont les 3 formes d'union officielles reconnues en France ?", answers: ["Mariage civil seulement", "Mariage civil, PACS et concubinage (union libre) — 3 statuts aux droits très différents", "Mariage civil et PACS seulement", "Mariage civil et mariage religieux"], correct: 1, explanation: "En France : Mariage (protection maximale, communauté de biens par défaut, droits successoraux automatiques), PACS (Pacte Civil de Solidarité — moins de protections que le mariage, pas d'adoption conjointe automatique), Concubinage/Union libre (aucune protection juridique automatique). Chaque statut a des conséquences fiscales et patrimoniales très différentes." },
    { question: "Quel est le délai minimum entre la demande de divorce par consentement mutuel et son prononcé en France ?", answers: ["6 mois", "Depuis 2017, divorce par consentement mutuel sans juge possible en quelques semaines si accord total", "1 an", "3 mois minimum"], correct: 1, explanation: "Depuis la réforme de 2017, le divorce par consentement mutuel peut être réalisé SANS juge en quelques semaines : les deux avocats (un par époux obligatoire) rédigent une convention de divorce, signée par les époux et déposée chez un notaire. Si enfant mineur demande à être entendu par un juge, retour devant le tribunal. Coût : honoraires d'avocat + notaire." },
    { question: "Qu'est-ce que l'autorité parentale conjointe et que se passe-t-il lors d'un divorce ?", answers: ["Elle est perdue par le parent qui quitte le domicile", "Elle reste conjointe après le divorce dans la très grande majorité des cas — les deux parents décident ensemble des choix importants", "Le juge la retire toujours à un parent", "Elle s'arrête à la majorité de l'enfant automatiquement"], correct: 1, explanation: "L'autorité parentale conjointe est la règle après divorce (art. 373-2 Code Civil). Les deux parents conservent le droit et le devoir de prendre ensemble les décisions importantes (école, santé, religion, voyages à l'étranger). Le juge ne retire l'autorité parentale que dans des cas graves (violence, abandon). La résidence de l'enfant est distincte de l'autorité parentale." },
    { question: "Qu'est-ce que la pension alimentaire et comment est-elle fixée ?", answers: ["Un loyer versé à l'ex-conjoint", "Contribution à l'entretien de l'enfant versée par le parent non gardien — fixée par le juge selon les ressources et besoins", "Obligatoire uniquement si le divorce est conflictuel", "Supprimée à la majorité de l'enfant automatiquement"], correct: 1, explanation: "La pension alimentaire est fixée par le juge aux affaires familiales selon : les ressources du parent débiteur, les besoins de l'enfant, le mode de résidence (alternée ou principale). Elle est due jusqu'à l'autonomie financière réelle de l'enfant (souvent après 18 ans si études). Non-paiement : crime d'abandon de famille (2 ans prison, 15 000€ amende). Révision possible si situation change." },
    { question: "Quels sont les droits successoraux du conjoint survivant marié en France ?", answers: ["Aucun droit légal — uniquement si testament", "En présence d'enfants : usufruit de la totalité ou quart en pleine propriété. En l'absence d'enfants : moitié ou totalité selon les héritiers", "La totalité de la succession automatiquement", "Uniquement le logement commun"], correct: 1, explanation: "Le conjoint survivant marié a des droits légaux : en présence d'enfants communs uniquement, il choisit entre l'usufruit de la totalité ou le quart en pleine propriété. En présence d'enfants d'un autre lit : quart en pleine propriété uniquement. Le conjoint survivant est exonéré de droits de succession (depuis 2007). Le PACS et concubinage offrent beaucoup moins de protection." },
    { question: "Qu'est-ce que la reconnaissance d'enfant naturel et dans quel délai peut-elle être effectuée ?", answers: ["Uniquement possible avant la naissance", "Avant naissance (reconnaissance prénatale) ou après — pas de délai légal pour le père, mais effets différents selon le moment", "Obligatoirement dans les 8 jours après la naissance", "Impossible sans test ADN"], correct: 1, explanation: "La reconnaissance peut être : prénatale (avant la naissance, chez le notaire ou officier d'état civil), simultanée à la déclaration de naissance, ou ultérieure (à tout moment). Pour la mère : établie automatiquement par l'accouchement. Pour le père non marié : reconnaissance obligatoire pour établir la filiation. Aucun test ADN n'est imposé — la reconnaissance est un acte volontaire." },
    { question: "Qu'est-ce que le régime matrimonial de la communauté réduite aux acquêts, régime légal par défaut en France ?", answers: ["Tout appartient aux deux époux dès le mariage", "Biens acquis avant mariage = propres. Biens acquis pendant le mariage = communs (sauf donations et héritages)", "Chacun garde ses biens séparément", "Tout est commun y compris les héritages"], correct: 1, explanation: "La communauté réduite aux acquêts est le régime légal par défaut (sans contrat de mariage). Biens propres : tout ce que chaque époux possédait avant le mariage + héritages et donations reçus pendant le mariage. Biens communs : tout ce acquis pendant le mariage (salaires, biens achetés ensemble). En cas de divorce : partage des biens communs à 50/50." },
    { question: "Peut-on déshériter un enfant en France ?", answers: ["Oui totalement par testament", "Non — la réserve héréditaire protège les enfants : minimum 50% de la succession pour 1 enfant, 66% pour 2, 75% pour 3+", "Oui si l'enfant a commis un crime", "Oui mais uniquement les enfants majeurs"], correct: 1, explanation: "La réserve héréditaire (art. 912 Code Civil) protège les enfants : ils ne peuvent pas être totalement déshérités. La quotité disponible (part librement testamentée) est de 50% pour 1 enfant, 33% pour 2 enfants, 25% pour 3 enfants ou plus. La part réservataire peut être réduite pour ingratitude grave (attentat à la vie du parent, sévices...) mais reste complexe juridiquement." },
    { question: "Qu'est-ce que la médiation familiale et quand y recourir ?", answers: ["Un tribunal spécialisé pour familles", "Processus amiable avec un médiateur neutre pour trouver des accords sur l'organisation familiale — moins coûteux et plus rapide que le tribunal", "Obligatoire avant tout divorce", "Uniquement pour les violences conjugales"], correct: 1, explanation: "La médiation familiale est un processus volontaire (sauf obligation de réunion d'information imposée par certains juges) où un médiateur neutre aide les parents à trouver des accords sur la garde, pension, organisation des vacances. Avantages : moins coûteux (participation selon revenus), plus rapide, accords mieux respectés car construits ensemble. 80% des médiations aboutissent à un accord partiel ou total." },
    { question: "Quel est le délai de prescription pour contester une succession en France ?", answers: ["1 an", "5 ans à partir du jour où on a eu connaissance de l'atteinte à ses droits", "2 ans uniquement", "10 ans pour les fraudes graves"], correct: 1, explanation: "L'action en réduction (pour récupérer sa part réservataire) se prescrit par 5 ans à compter du jour où l'héritier a eu connaissance de l'atteinte à sa réserve (et au plus tard 10 ans après le décès). L'action en nullité de testament se prescrit par 5 ans. Il est important d'agir rapidement dès connaissance d'une irrégularité successorale." },
  ],
  tips: ["Le concubinage (union libre) n'offre AUCUNE protection juridique automatique — le PACS ou mariage est indispensable", "La réserve héréditaire protège vos enfants — impossible de les déshériter totalement en France", "Le divorce par consentement mutuel sans juge est possible depuis 2017 — rapide et moins coûteux"],
};
export default quizDroitFamille;
