/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizDroitEtrangers = {
  title: "Droit des Étrangers & Immigration",
  description: "Comprendre les droits des étrangers en France et les procédures d'immigration !",
  emoji: "🌐",
  questions: [
    { question: "Quels sont les titres de séjour principaux pour un ressortissant non-européen en France ?", answers: ["Uniquement le visa touristique", "Visa long séjour, carte de séjour temporaire (1 an), carte de séjour pluriannuelle (2-4 ans), carte de résident (10 ans)", "Seulement la carte de résident", "Le passeport du pays d'origine suffit"], correct: 1, explanation: "Les titres de séjour en France pour les non-européens : Visa long séjour (> 3 mois, différentes catégories : travail, étudiant, famille), Carte de Séjour Temporaire (1 an, renouvelable), Carte de Séjour Pluriannuelle (2 à 4 ans), Carte de Résident (10 ans, renouvelable, pour résidence stable et régulière depuis 5 ans). La naturalisation est possible après 5 ans de résidence régulière." },
    { question: "Qu'est-ce que le droit d'asile et qui peut en bénéficier en France ?", answers: ["Droit réservé aux Européens en difficulté", "Toute personne persécutée dans son pays pour sa race, religion, nationalité, appartenance à un groupe social ou opinions politiques", "Uniquement pour les réfugiés de guerre", "Droit supprimé en 2015"], correct: 1, explanation: "Le droit d'asile est garanti par la Convention de Genève (1951) et la Constitution française. Tout étranger persécuté dans son pays pour sa race, religion, nationalité, appartenance à un groupe social ou opinions politiques peut demander l'asile. En France, l'OFPRA (Office Français de Protection des Réfugiés) instruit les demandes. La CNDA est la cour d'appel." },
    { question: "Un enfant né en France de parents étrangers est-il automatiquement français ?", answers: ["Oui, le droit du sol est absolu en France", "Non — il peut réclamer la nationalité française à ses 18 ans s'il réside en France, ou dès 13 ans sous conditions", "Oui automatiquement à la naissance", "Non, jamais possible par droit du sol"], correct: 1, explanation: "La France applique un droit du sol conditionnel (jus soli) : un enfant né en France de parents étrangers n'est PAS automatiquement français à la naissance. Il peut acquérir la nationalité française à 18 ans s'il réside en France habituellement depuis 5 ans (ou à 13 ans sur demande parentale, ou à 16 ans sur demande propre). Différent du droit du sol pur des USA." },
    { question: "Quels droits fondamentaux s'appliquent aux étrangers en situation irrégulière en France ?", answers: ["Aucun droit car sans papiers", "Droit à l'urgence médicale (AME), droit à la scolarisation des enfants, droit de ne pas être expulsé sans procédure régulière, droit à un interprète", "Seulement droit à l'éducation des enfants", "Uniquement le droit à un avocat commis d'office"], correct: 1, explanation: "Même en situation irrégulière, des droits fondamentaux s'appliquent : Aide Médicale d'État (AME) pour soins urgents, scolarisation obligatoire des enfants sans condition de séjour, protection contre l'expulsion sans procédure régulière (rétention administrative limitée à 90 jours), droit à un interprète et à un avocat lors de la procédure d'éloignement." },
    { question: "Qu'est-ce que le regroupement familial et quelles sont ses conditions principales ?", answers: ["Un droit automatique dès l'arrivée en France", "Procédure permettant à un étranger en situation régulière de faire venir sa famille — conditions : 18 mois de résidence, ressources suffisantes, logement adapté", "Uniquement pour les réfugiés reconnus", "Procédure supprimée en 2020"], correct: 1, explanation: "Le regroupement familial (R. 421-1 CESEDA) permet à un étranger légalement en France de faire venir conjoint et enfants mineurs. Conditions : 18 mois de résidence régulière minimum, ressources stables suffisantes (équivalent SMIC), logement de taille adéquate, respect des principes de la République. Délai de traitement : 6 à 12 mois. Décision par le maire puis le préfet." },
    { question: "Après combien d'années de résidence régulière peut-on demander la naturalisation française ?", answers: ["3 ans", "5 ans en général (2 ans pour certains cas privilégiés : diplômé français, service militaire, francophonie)", "10 ans obligatoirement", "7 ans minimum"], correct: 1, explanation: "La naturalisation est possible après 5 ans de résidence régulière (art. 21-17 Code Civil). Délai réduit à 2 ans pour : diplômé d'une grande école ou université française, service militaire volontaire, ressortissant francophone (Afrique, DOM-TOM). Conditions supplémentaires : assimilation culturelle, connaissance du français (niveau B1 minimum), absence de condamnation pénale grave." },
    { question: "Qu'est-ce que l'Aide Médicale d'État (AME) réservée aux étrangers en situation irrégulière ?", answers: ["Une aide financière mensuelle", "Couverture santé pour les soins urgents et de base — accessible après 3 mois de résidence en France sans papiers, sous conditions de ressources", "Identique à la Sécurité Sociale", "Une aide supprimée en 2023"], correct: 1, explanation: "L'AME couvre les soins médicaux essentiels pour les personnes en situation irrégulière résidant en France depuis plus de 3 mois avec des revenus sous le plafond CMU. Remboursement à 100% des soins pris en charge. Elle vise à éviter que des personnes malades non soignées constituent un risque de santé publique. Coût annuel : environ 1 milliard € pour 400 000 bénéficiaires." },
    { question: "Quel est le droit d'un étranger placé en rétention administrative (CRA) ?", answers: ["Aucun droit en rétention", "Droit à un avocat, à un interprète, à un médecin, à contacter sa famille et son consulat — contrôle judiciaire dans les 48h", "Rétention illimitée possible", "Uniquement droit à un interprète"], correct: 1, explanation: "En Centre de Rétention Administrative (CRA) : droit à un avocat (commis d'office si besoin), interprète, médecin, contact avec famille et consulat. Un juge des libertés et de la détention (JLD) contrôle la légalité dans les 48h, puis tous les 15 jours. Durée maximale de rétention : 90 jours en France. L'association CIMADE assiste les personnes en CRA." },
    { question: "Les ressortissants des DOM (Guadeloupe, Martinique, Guyane, La Réunion, Mayotte) ont-ils besoin d'un titre de séjour pour vivre en France métropolitaine ?", answers: ["Oui, comme tout citoyen étranger", "Non — ils sont citoyens français à part entière, libres de circuler sans aucun titre de séjour", "Visa DOM-TOM spécifique requis", "Carte de résident DOM nécessaire"], correct: 1, explanation: "Les ressortissants des DOM (Guadeloupe, Martinique, Guyane, La Réunion) et COM (Saint-Martin, Saint-Barthélemy, Polynésie...) sont des CITOYENS FRANÇAIS À PART ENTIÈRE. Ils circulent librement sur tout le territoire français et européen avec leur carte nationale d'identité française. Aucun titre de séjour requis. Même droits sociaux qu'en métropole." },
    { question: "Qu'est-ce que le titre 'passeport talent' créé en 2016 pour attirer les talents étrangers en France ?", answers: ["Un passeport diplomatique", "Carte de séjour pluriannuelle de 4 ans pour les profils hautement qualifiés : chercheurs, artistes, entrepreneurs innovants, salariés qualifiés", "Un visa pour les touristes fortunés", "Un titre réservé aux sportifs professionnels"], correct: 1, explanation: "Le Passeport Talent (depuis 2016) est une carte de séjour pluriannuelle de 4 ans (renouvelable) destinée à attirer les talents étrangers. Catégories : salarié qualifié (salaire > 2,5x SMIC), chercheur, artiste, entrepreneur porteur de projet innovant, investisseur. Le conjoint obtient automatiquement une autorisation de travail. Démarche accélérée par rapport aux procédures classiques." },
  ],
  tips: ["Les Guadeloupéens et Martiniquais sont citoyens français — aucun titre de séjour requis nulle part en Europe", "Même sans papiers, les enfants ont le droit à la scolarisation en France — obligation légale", "Le Passeport Talent permet aux entrepreneurs et créateurs étrangers de s'installer facilement en France"],
};
export default quizDroitEtrangers;
