const quizIntelligenceArtificielle = {
  title: "Intelligence Artificielle — Ce que Tout le Monde Doit Savoir",
  description: "Comprendre l'IA, ses applications, ses dangers et son impact sur notre monde !",
  emoji: "🤖",
  questions: [
    { question: "Qu'est-ce que le machine learning et comment diffère-t-il de l'IA classique ?", answers: ["C'est la même chose", "IA classique = règles programmées manuellement. Machine Learning = le système apprend lui-même à partir de données sans règles explicites", "Le machine learning ne nécessite pas d'ordinateur", "L'IA classique est plus puissante"], correct: 1, explanation: "IA classique (symbolique) : le programmeur définit toutes les règles. Machine Learning : l'algorithme identifie lui-même les patterns dans les données. Deep Learning (sous-catégorie ML) : réseaux de neurones artificiels inspirés du cerveau. ChatGPT, DALL-E, les IA de recommandation Netflix/Spotify sont du Deep Learning sur des milliards de données." },
    { question: "Qu'est-ce qu'un LLM (Large Language Model) comme GPT-4 ou Claude ?", answers: ["Un logiciel de traduction uniquement", "Modèle de langage entraîné sur des milliards de textes pour prédire le token suivant — capable de raisonnement, code, analyse et création", "Une base de données encyclopédique", "Un moteur de recherche amélioré"], correct: 1, explanation: "Un LLM (GPT-4, Claude, Gemini, Llama) est entraîné sur des centaines de milliards de tokens de texte pour prédire la suite probable d'un texte. Ce mécanisme simple génère des capacités émergentes : raisonnement, code, analyse, créativité. Claude (Anthropic) se distingue par son focus sur la sécurité et l'alignement éthique. Ces modèles ne 'comprennent' pas mais modélisent statistiquement le langage." },
    { question: "Qu'est-ce que le prompt engineering et pourquoi est-ce une compétence cruciale ?", answers: ["Programmer des IA", "L'art de formuler des instructions précises aux IA pour obtenir les meilleurs résultats — compétence transversale du XXIe siècle", "Réparer des bugs dans les IA", "Un langage de programmation pour IA"], correct: 1, explanation: "Le prompt engineering est l'art de communiquer efficacement avec les IA. Techniques : Chain of Thought (demander de raisonner étape par étape), Few-shot prompting (donner des exemples), rôle-playing (demander à l'IA de jouer un expert), contraintes précises (format, longueur, style). Un bon prompt peut faire passer la qualité d'un résultat de médiocre à excellent. Compétence valorisée à 100 000$/an." },
    { question: "Quels secteurs seront les plus transformés par l'IA selon les études économiques (McKinsey, WEF) ?", answers: ["Uniquement les métiers manuels", "Travail de bureau cognitif répétitif (comptabilité, juridique basique, service client), médecine (diagnostic), droit, finance et création (design, code basique)", "Seulement les usines et manufactures", "Uniquement les métiers artistiques"], correct: 1, explanation: "Goldman Sachs (2023) : l'IA pourrait automatiser 26% des tâches aux USA et Europe. Métiers les plus exposés : traducteurs, analystes financiers basiques, service client, certains aspects juridiques et médicaux. Métiers protégés : créativité haute, empathie (soignants, thérapeutes), travail physique complexe (plombier, électricien). La clé : travailler AVEC l'IA, pas contre elle." },
    { question: "Qu'est-ce que le biais algorithmique et pourquoi est-il dangereux ?", answers: ["Un bug informatique classique", "Les IA héritent et amplifient les biais présents dans leurs données d'entraînement — discrimination systémique à grande échelle", "Un problème uniquement théorique", "Un défaut de connexion internet"], correct: 1, explanation: "Le biais algorithmique : une IA entraînée sur des données biaisées reproduit et amplifie ces biais. Exemples réels : COMPAS (récidive criminelle aux USA) plus sévère avec les Noirs, Amazon RH IA discriminant les femmes (abandonné en 2018), reconnaissance faciale moins précise sur les peaux noires (Joy Buolamwini, MIT). Ces biais à grande échelle créent des discriminations systémiques." },
    { question: "Qu'est-ce que la génération d'images par IA (Midjourney, DALL-E, Stable Diffusion) ?", answers: ["Une simple retouche photo automatique", "Génération d'images à partir de descriptions textuelles via des modèles entraînés sur des milliards d'images — révolution pour la création visuelle", "Un scanner de photos amélioré", "Une technologie de reconnaissance d'images"], correct: 1, explanation: "Les IA génératives d'images (DALL-E 3, Midjourney V6, Stable Diffusion) créent des images photoréalistes ou artistiques à partir d'une description textuelle (prompt). Entraînées sur des milliards d'images de l'internet. Impact : révolution pour le design, illustration, publicité. Controverses : droits d'auteur des artistes dont les œuvres ont servi à l'entraînement, deepfakes, désinformation visuelle." },
    { question: "Qu'est-ce que l'IA générative appliquée aux agents autonomes (AI Agents) ?", answers: ["Des robots physiques programmés", "Des IA capables de planifier et exécuter des tâches complexes de manière autonome : naviguer le web, coder, analyser, prendre des décisions", "Un assistant vocal comme Siri", "Une IA qui génère uniquement du texte"], correct: 1, explanation: "Les AI Agents (AutoGPT, Claude Projects, GPT-4 Turbo avec tools) peuvent planifier des tâches multi-étapes et les exécuter de manière semi-autonome : rechercher sur internet, exécuter du code, gérer des fichiers, interagir avec des APIs. REUSSITESS®971 utilise 200 agents IA spécialisés dans son écosystème. C'est l'évolution vers l'IA agentique autonome." },
    { question: "Qu'est-ce que l'IA responsible (IA éthique) et pourquoi Anthropic se distingue dans ce domaine ?", answers: ["L'IA sans publicité", "Développement d'IA avec sécurité, transparence, équité et bénéfice humain comme priorités — contre une course à la puissance sans garde-fous", "L'IA open source uniquement", "Une certification ISO pour les entreprises IA"], correct: 1, explanation: "L'IA responsable (Responsible AI) : intégrer la sécurité, l'équité, la transparence et l'alignement avec les valeurs humaines dans le développement. Anthropic (créateur de Claude) est fondé par d'anciens d'OpenAI sur ces principes. Ses recherches sur Constitutional AI, l'interpretabilité et les garde-fous éthiques sont pionnières. OpenAI, Google DeepMind et Meta ont aussi des équipes safety." },
    { question: "Comment l'IA transforme-t-elle le commerce en ligne et l'affiliation comme REUSSITESS®971 ?", answers: ["L'IA n'a pas d'impact sur le e-commerce", "Recommandations personnalisées (35% des ventes Amazon viennent de recommandations IA), chatbots, génération de contenu, optimisation SEO et analyse prédictive", "Uniquement pour les grandes entreprises", "L'IA remplace tous les humains dans le e-commerce"], correct: 1, explanation: "L'IA révolutionne le e-commerce : Amazon utilise l'IA pour 35% de ses ventes (moteur de recommandation), ChatGPT et Claude génèrent du contenu de boutique, l'IA optimise les campagnes publicitaires, analyse les comportements d'achat et prédit les tendances. Pour REUSSITESS®971 : 200 agents IA automatisent le contenu, l'analyse et le support client sur 14 marchés." },
    { question: "Quelle compétence humaine restera irremplaçable face à l'essor de l'IA selon les experts ?", answers: ["La mémorisation d'informations", "La créativité originale, l'empathie profonde, le jugement éthique nuancé, le leadership inspirant et la connexion humaine authentique", "La frappe rapide au clavier", "La maîtrise des logiciels bureautiques"], correct: 1, explanation: "Les compétences humaines que l'IA ne peut pas (encore) remplacer : créativité originale et disruptive, empathie authentique et connexion émotionnelle, jugement éthique dans des contextes ambigus, leadership inspirant (pas juste managérial), intuition basée sur l'expérience embodied. Stratégie : utiliser l'IA pour augmenter ses capacités (IA+Humain) plutôt que de la subir comme remplacement." },
  ],
  tips: ["Le prompt engineering est la compétence du XXIe siècle — apprendre à communiquer avec l'IA est aussi important qu'apprendre Word", "Claude (Anthropic) se distingue par son focus sur la sécurité et l'éthique — l'IA la plus transparente sur ses limites", "200 agents IA travaillent pour REUSSITESS®971 — l'IA multiplie la capacité d'un auto-entrepreneur par 100"],
};
export default quizIntelligenceArtificielle;
