const quizDroitConsommateur = {
  title: "Droits du Consommateur",
  description: "Connaissez vos droits d'acheteur et ne vous laissez plus jamais arnaquer !",
  emoji: "🛒",
  questions: [
    { question: "Quel est le délai de rétractation légal pour un achat en ligne (e-commerce) en France ?", answers: ["7 jours", "14 jours calendaires sans justification — directive européenne 2014", "30 jours", "48 heures seulement"], correct: 1, explanation: "Pour tout achat en ligne (e-commerce), à distance ou hors établissement, vous avez 14 jours calendaires pour vous rétracter SANS justification (loi Hamon 2014, directive européenne). Le délai part de la réception du bien ou de la signature du contrat de service. Le remboursement doit intervenir dans les 14 jours suivant votre rétractation." },
    { question: "Quelle est la garantie légale de conformité applicable à tout achat de produit en France ?", answers: ["6 mois uniquement", "2 ans à partir de la livraison — le vendeur doit réparer, remplacer ou rembourser", "1 an uniquement", "Pas de garantie légale, seulement commerciale"], correct: 1, explanation: "La garantie légale de conformité (art. L217-4 et suivants Code de la Consommation) : 2 ans pour les produits neufs (1 an pour l'occasion) à compter de la livraison. Le vendeur professionnel (pas un particulier) doit réparer, remplacer ou rembourser. Pendant les 24 premiers mois, la présomption est que le défaut existait à l'achat — c'est au vendeur de prouver le contraire." },
    { question: "Qu'est-ce que la garantie des vices cachés et comment s'en prévaloir ?", answers: ["Identique à la garantie de conformité", "Garantie contre les défauts cachés qui rendent le bien impropre à l'usage, existant avant la vente — même entre particuliers", "Uniquement pour les voitures d'occasion", "Garantie de 6 mois uniquement"], correct: 1, explanation: "La garantie des vices cachés (art. 1641 Code Civil) s'applique même aux ventes entre particuliers. Le vice doit être : caché (non apparent lors de la vente), antérieur à la vente, grave (rend le bien inutilisable ou diminue son usage). Délai : 2 ans à partir de la découverte du vice. Recours : résolution de la vente ou réduction du prix." },
    { question: "Que faire face à un démarchage téléphonique non sollicité en France ?", answers: ["Obligatoire d'écouter jusqu'à la fin", "S'inscrire sur la liste Bloctel (bloctel.gouv.fr) — le démarchage des inscrits est interdit sauf relations commerciales préexistantes", "Aucun recours possible", "Porter plainte à la police directement"], correct: 1, explanation: "Bloctel (depuis 2016) est la liste d'opposition au démarchage téléphonique. L'inscription est gratuite sur bloctel.gouv.fr. Les professionnels ne peuvent pas démarcher les personnes inscrites (sauf client actuel). Amende jusqu'à 75 000€ par appel illicite pour les entreprises. Signalez les violations sur signal.conso.gouv.fr." },
    { question: "Un commerçant est-il obligé d'afficher ses prix en France ?", answers: ["Non, les prix sont libres et non obligatoirement affichés", "Oui — affichage des prix TTC obligatoire pour tous les professionnels, visible avant l'achat", "Seulement les grandes surfaces", "Seulement pour les produits alimentaires"], correct: 1, explanation: "L'affichage des prix TTC est une obligation légale pour tout professionnel (arrêté du 3 décembre 1987). Dans un magasin : prix sur ou à côté de chaque produit. Sur un menu : prix de tous les plats. En vitrine : prix des produits exposés. Non-respect : amende de 3 000€ (personne physique) à 15 000€ (personne morale). Signal.conso.gouv.fr pour signaler." },
    { question: "Qu'est-ce qu'une clause abusive dans un contrat de consommation ?", answers: ["Toute clause qui déplait au consommateur", "Clause créant un déséquilibre significatif entre les droits et obligations des parties au détriment du consommateur — réputée non écrite", "Uniquement dans les contrats de téléphonie", "Clause difficile à comprendre"], correct: 1, explanation: "Une clause abusive (art. L212-1 Code Conso) crée un déséquilibre significatif au détriment du consommateur. Elle est réputée non écrite (nulle) mais le reste du contrat s'applique. Exemples : pénalités asymétriques, exclusion de responsabilité totale, renouvellement tacite sans préavis suffisant. La Commission des Clauses Abusives publie des recommandations." },
    { question: "Quel est votre droit si un produit acheté en ligne ne correspond pas à la description ?", answers: ["Vous devez le garder", "Droit de rétractation 14 jours + garantie légale de conformité + remboursement frais de retour à la charge du vendeur si non-conformité", "Seul le renvoi du produit est possible sans remboursement", "Uniquement si le vendeur accepte"], correct: 1, explanation: "Produit non conforme à la description : vous pouvez exercer la rétractation (14 jours, remboursement sous 14 jours) OU la garantie légale de conformité (réparation, remplacement, remboursement). En cas de non-conformité, les frais de retour sont à la charge du vendeur professionnel. Conservez toutes les preuves (captures d'écran de la description, photos)." },
    { question: "Comment se défendre efficacement contre une arnaque ou un litige avec un commerçant ?", answers: ["Porter plainte immédiatement au commissariat", "Lettre recommandée AR → Médiation de la consommation → DGCCRF (signal.conso.gouv.fr) → Tribunal de proximité si < 5000€", "Publier des avis négatifs en ligne uniquement", "Contacter directement le PDG de l'entreprise"], correct: 1, explanation: "Procédure graduelle : 1. Lettre recommandée AR au service client (conservez toujours les preuves), 2. Médiation de la consommation (obligatoire pour les pros depuis 2016), 3. Signalement DGCCRF sur signal.conso.gouv.fr, 4. Tribunal de proximité pour les litiges < 5 000€ (gratuit, sans avocat obligatoire), 5. Association de consommateurs (UFC-Que Choisir, 60 Millions de Consommateurs)." },
    { question: "Qu'est-ce que le droit à l'image et comment s'applique-t-il à la consommation numérique ?", answers: ["Un droit uniquement pour les célébrités", "Toute personne contrôle l'utilisation de son image — consentement écrit obligatoire pour utilisation commerciale", "Inapplicable sur internet", "Uniquement pour les photos professionnelles"], correct: 1, explanation: "Le droit à l'image (art. 9 Code Civil) protège toute personne : nul ne peut publier, diffuser ou utiliser votre image sans votre consentement exprès. Pour usage commercial : consentement écrit obligatoire avec description précise de l'utilisation. Violation : jusqu'à 45 000€ d'amende et 1 an de prison. Ce droit s'applique pleinement aux réseaux sociaux et au e-commerce." },
    { question: "Quels sont vos droits si votre vol aérien est annulé ou retardé de plus de 3 heures (UE) ?", answers: ["Aucun droit légal", "Règlement EU 261/2004 : remboursement ou réacheminement + indemnisation 250€ à 600€ selon distance + assistance (repas, hôtel)", "Uniquement un bon d'achat", "Droits seulement si départ depuis l'UE"], correct: 1, explanation: "Règlement EU 261/2004 : si vol annulé ou retard > 3h : remboursement total ou réacheminement + indemnisation forfaitaire : 250€ (< 1500km), 400€ (1500-3500km), 600€ (> 3500km). Assistance obligatoire : repas, boissons, hébergement si nuit, 2 appels téléphoniques. S'applique si départ UE (toute compagnie) ou arrivée UE (compagnie européenne)." },
  ],
  tips: ["14 jours pour vous rétracter de tout achat en ligne — sans justification — c'est un droit européen", "Inscrivez-vous sur Bloctel (gratuit) pour bloquer le démarchage téléphonique", "Vol annulé ou retard > 3h = jusqu'à 600€ d'indemnisation légale — réclamez systématiquement"],
};
export default quizDroitConsommateur;
