/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizAfroCaraibes2 = {
  title: "Grands Hommes Noirs & Inventeurs",
  description: "Découvrez les inventions et les figures noires qui ont marqué l'histoire mondiale !",
  emoji: "🏆",
  questions: [
    { question: "Qui a inventé le filament en carbone pour l'ampoule électrique, permettant à Edison de perfectionner sa lampe ?", answers: ["Nikola Tesla", "Lewis Howard Latimer", "George Washington Carver", "Jan Ernst Matzeliger"], correct: 1, explanation: "Lewis Howard Latimer (1848-1928), fils d'esclaves fugitifs, a inventé le filament en carbone en 1881. Il a travaillé pour Edison et Bell, et était membre des Edison Pioneers." },
    { question: "Quel inventeur afro-caribéen a révolutionné l'industrie de la chaussure avec sa machine à assembler les semelles ?", answers: ["Elijah McCoy", "Jan Ernst Matzeliger", "Granville Woods", "Frederick Jones"], correct: 1, explanation: "Jan Ernst Matzeliger (1852-1889), né au Suriname, a inventé en 1883 la machine à assembler les chaussures. Son invention a réduit de 50% le prix des chaussures." },
    { question: "Quel inventeur noir a créé le lubrifiant automatique de train, si fiable qu'on disait The Real McCoy ?", answers: ["Granville Woods", "Elijah McCoy", "Lewis Latimer", "Henry Blair"], correct: 1, explanation: "Elijah McCoy (1844-1929) a inventé un lubrifiant automatique pour locomotives en 1872. L'expression The Real McCoy, signifiant l'authentique, viendrait de lui." },
    { question: "Qui a inventé la banque de sang et sauvé des millions de vies pendant la Seconde Guerre mondiale ?", answers: ["Daniel Hale Williams", "Charles Drew", "Louis Terman", "Carter Woodson"], correct: 1, explanation: "Charles Richard Drew (1904-1950) a développé les techniques de conservation du plasma sanguin et créé les premières banques de sang en 1940." },
    { question: "Quel médecin africain-américain a réalisé la première opération à cœur ouvert réussie en 1893 ?", answers: ["Charles Drew", "Daniel Hale Williams", "Mae Jemison", "Ronald McNair"], correct: 1, explanation: "Daniel Hale Williams (1856-1931) a réalisé la première chirurgie cardiaque réussie le 9 juillet 1893 à Chicago. Il a aussi fondé le premier hôpital interracial des États-Unis." },
    { question: "Qui fut la première femme afro-américaine à voyager dans l'espace en 1992 ?", answers: ["Katherine Johnson", "Mae Jemison", "Sally Ride", "Guion Bluford"], correct: 1, explanation: "Mae C. Jemison est devenue la première femme noire dans l'espace lors de la mission STS-47 en septembre 1992. Médecin et ingénieure, elle citait Uhura de Star Trek comme inspiration." },
    { question: "Quelle mathématicienne afro-américaine a calculé la trajectoire qui a permis à John Glenn de faire le tour de la Terre ?", answers: ["Mae Jemison", "Dorothy Vaughan", "Katherine Johnson", "Mary Jackson"], correct: 2, explanation: "Katherine Johnson (1918-2020) était une mathématicienne de génie à la NASA. John Glenn refusait de décoller sans qu'elle vérifie les calculs. Le film Hidden Figures raconte son histoire." },
    { question: "Quel scientifique afro-américain a découvert plus de 300 utilisations pour l'arachide ?", answers: ["Lewis Latimer", "George Washington Carver", "Charles Drew", "Norbert Rillieux"], correct: 1, explanation: "George Washington Carver (1860-1943), né esclave, a découvert 300 utilisations pour l'arachide et 118 pour la patate douce, révolutionnant l'agriculture du Sud américain." },
    { question: "Qui a inventé le téléphone multi-lignes et le relais ferroviaire, surnommé le Black Edison ?", answers: ["Elijah McCoy", "Lewis Latimer", "Granville T. Woods", "Frederick Jones"], correct: 2, explanation: "Granville T. Woods (1856-1910) a inventé plus de 60 brevets. Son Multiplex Telegraph de 1887 permettait de communiquer entre trains en mouvement, révolutionnant la sécurité ferroviaire." },
    { question: "Qui fut le premier athlète noir à remporter 4 médailles d'or aux JO de Berlin 1936, humiliant Hitler ?", answers: ["Jim Thorpe", "Jesse Owens", "Jack Johnson", "Paul Robeson"], correct: 1, explanation: "Jesse Owens (1913-1980) a remporté 4 médailles d'or à Berlin en 1936 sous les yeux d'Adolf Hitler qui prônait la supériorité aryenne." },
    { question: "Quel boxeur noir surnommé le plus grand a refusé d'aller combattre au Vietnam ?", answers: ["Joe Louis", "Sugar Ray Robinson", "Muhammad Ali", "Mike Tyson"], correct: 2, explanation: "Muhammad Ali (1942-2016) a refusé d'intégrer l'armée américaine pour le Vietnam en 1967. Il a été déchu de son titre avant d'être blanchi par la Cour Suprême." },
    { question: "Qui a fondé le Parti des Panthères Noires en 1966 à Oakland ?", answers: ["Malcolm X et MLK", "Huey P. Newton et Bobby Seale", "Stokely Carmichael et H. Rap Brown", "Angela Davis et Eldridge Cleaver"], correct: 1, explanation: "Huey P. Newton et Bobby Seale ont fondé le Black Panther Party en 1966, prônant l'autodéfense armée et la fin de la brutalité policière." },
    { question: "Quel musicien de la Nouvelle-Orléans est souvent cité comme l'inventeur du jazz vers 1895 ?", answers: ["Duke Ellington", "Louis Armstrong", "Buddy Bolden", "Miles Davis"], correct: 2, explanation: "Charles Buddy Bolden (1877-1931) est souvent cité comme l'inventeur du jazz à la Nouvelle-Orléans. Ses improvisations mélangeaient blues, ragtime et musique de fanfare." },
    { question: "Qui fut le premier nageur africain à remporter une médaille d'or olympique en 1988 ?", answers: ["Anthony Ervin", "Cullen Jones", "Anthony Nesty", "Maritza Correia"], correct: 2, explanation: "Anthony Nesty, né au Suriname, a remporté l'or en natation aux JO de Séoul en 1988 sur 100m papillon, première médaille d'or olympique pour le Suriname." },
    { question: "Qui est la première femme noire à avoir reçu le Prix Nobel de Littérature en 1993 ?", answers: ["Maya Angelou", "Toni Morrison", "Alice Walker", "Zora Neale Hurston"], correct: 1, explanation: "Toni Morrison (1931-2019) a reçu le Prix Nobel de Littérature en 1993. Son roman Beloved a remporté le Pulitzer." },
    { question: "Quel artiste haïtien est le père de la peinture naïve haïtienne découvert par André Breton ?", answers: ["Jean-Michel Basquiat", "Hector Hyppolite", "Edouard Duval-Carrié", "André Pierre"], correct: 1, explanation: "Hector Hyppolite (1894-1948), prêtre vodou et peintre autodidacte, a été découvert par le surréaliste André Breton. Ses œuvres sont exposées au MoMA de New York." },
    { question: "Quel astronome afro-américain a publié des almanachs astronomiques et écrit à Thomas Jefferson pour dénoncer l'esclavage ?", answers: ["Neil deGrasse Tyson", "Benjamin Banneker", "George Alcorn", "Christine Darden"], correct: 1, explanation: "Benjamin Banneker (1731-1806) a publié des almanachs de 1792 à 1797 et a participé à la conception de Washington D.C. Sa lettre à Jefferson dénonçant l'esclavage est célèbre." },
    { question: "Quel médecin afro-américain a développé les médicaments anti-rejet et pratiqué 500 transplantations rénales ?", answers: ["Charles Drew", "Vivien Thomas", "Samuel Lee Kountz", "Daniel Hale Williams"], correct: 2, explanation: "Le Dr Samuel Lee Kountz (1930-1981) a pratiqué plus de 500 transplantations rénales et développé des médicaments anti-rejet. Sa recherche a rendu possibles les transplantations actuelles." },
    { question: "Qui fut le premier général afro-américain à diriger les forces armées américaines comme chef d'état-major ?", answers: ["Benjamin Davis Sr.", "Colin Powell", "Lloyd Austin", "Eric Holder"], correct: 1, explanation: "Colin Powell (1937-2021), fils d'immigrants jamaïcains, fut le premier Afro-Américain à diriger le Comité des chefs d'état-major (1989-1993), puis Secrétaire d'État." },
    { question: "Quel leader du Ghana, premier pays d'Afrique noire indépendant en 1957, a inspiré les Caraïbes ?", answers: ["Jomo Kenyatta", "Julius Nyerere", "Kwame Nkrumah", "Patrice Lumumba"], correct: 2, explanation: "Kwame Nkrumah (1909-1972) a mené le Ghana à l'indépendance le 6 mars 1957. Son slogan Africa must unite a inspiré toute la diaspora caribéenne." },
    { question: "Quel guitariste afro-américain de Seattle est considéré comme le plus grand de tous les temps ?", answers: ["B.B. King", "Chuck Berry", "Jimi Hendrix", "Robert Johnson"], correct: 2, explanation: "Jimi Hendrix (1942-1970), né à Seattle, a révolutionné la guitare électrique. Son interprétation de l'hymne américain à Woodstock en 1969 reste légendaire." },
    { question: "Quel athlète jamaïcain détient les records mondiaux du 100m et 200m établis à Berlin en 2009 ?", answers: ["Asafa Powell", "Yohan Blake", "Usain Bolt", "Michael Johnson"], correct: 2, explanation: "Usain Bolt (né en 1986) détient les records du 100m (9.58s) et 200m (19.19s). Triple champion olympique en 2008, 2012 et 2016, il est l'athlète le plus titré de l'histoire." },
    { question: "Quelle reine africaine du XVIIe siècle a résisté aux colonisateurs portugais en Angola ?", answers: ["Nzinga de Ndongo", "Yaa Asantewaa", "Kimpa Vita", "Hatshepsout"], correct: 0, explanation: "La reine Nzinga (1583-1663) du Ndongo et Matamba a résisté aux Portugais pendant des décennies. Elle est aujourd'hui l'héroïne nationale de l'Angola." },
    { question: "Quel général haïtien ancien esclave a construit la Citadelle Laferrière, patrimoine mondial UNESCO ?", answers: ["Henri Christophe", "Jean-Jacques Dessalines", "Toussaint Louverture", "Alexandre Pétion"], correct: 0, explanation: "Henri Christophe (1767-1820), ancien esclave devenu roi Henri Ier d'Haïti, a construit la Citadelle Laferrière, l'une des plus grandes forteresses des Amériques." },
    { question: "Quelle scientifique de la NASA a calculé la trajectoire de retour qui a sauvé les astronautes d'Apollo 13 ?", answers: ["Mae Jemison", "Katherine Johnson", "Mary Jackson", "Christine Darden"], correct: 1, explanation: "Katherine Johnson (1918-2020) a calculé la trajectoire de retour d'Apollo 13 après l'explosion de 1970. Sans ses calculs, les astronautes ne seraient jamais rentrés." },
  ],
  tips: [
    "George Washington Carver a refusé une offre de 100 000$ de Thomas Edison — il préférait aider sa communauté",
    "Mae Jemison et Katherine Johnson prouvent que le ciel n'est pas la limite pour les femmes noires dans les sciences",
    "La résistance afro-caribéenne n'a jamais cessé — de la Reine Nzinga à Marcus Garvey, en passant par Toussaint Louverture"
  ],
};
export default quizAfroCaraibes2;
