const quizPlantesMediacinales = {
  title: "Se Soigner par les Plantes — Phytothérapie",
  description: "Découvrez les plantes médicinales et leurs vertus thérapeutiques reconnues !",
  emoji: "🌿",
  questions: [
    { question: "Quelle plante antillaise surnommée 'aspirine des Caraïbes' est utilisée contre la fièvre et les douleurs ?", answers: ["Le vétiver", "La citronnelle", "Le sirop de miel", "La verveine citronnelle (bois citron / lemon grass)"], correct: 3, explanation: "La verveine citronnelle (Cymbopogon citratus), appelée bois citron ou lemon grass aux Antilles, est utilisée traditionnellement en tisane contre la fièvre, les maux de tête et douleurs. Ses propriétés anti-inflammatoires et analgésiques sont reconnues. Très utilisée en médecine créole guadeloupéenne et martiniquaise." },
    { question: "Quelles sont les propriétés médicinales reconnues du curcuma ?", answers: ["Uniquement colorant alimentaire", "Anti-inflammatoire puissant, antioxydant, protecteur hépatique — la curcumine est étudiée contre le cancer", "Antibiotique naturel uniquement", "Antidépresseur naturel uniquement"], correct: 1, explanation: "Le curcuma (Curcuma longa) contient de la curcumine, l'un des anti-inflammatoires naturels les plus puissants connus. Des milliers d'études montrent ses propriétés : anti-inflammatoire, antioxydant, protection du foie, soutien cérébral. Mieux absorbé avec poivre noir (pipérine +2000%) et matière grasse." },
    { question: "Quelle plante est connue comme 'adaptogène' aidant le corps à résister au stress ?", answers: ["La camomille", "L'ashwagandha (ginseng indien)", "La menthe poivrée", "Le romarin"], correct: 1, explanation: "L'Ashwagandha (Withania somnifera) est un adaptogène majeur de l'Ayurveda. Les adaptogènes aident le corps à s'adapter au stress physique et mental. Études prouvant : réduction du cortisol de 27%, amélioration des performances sportives, soutien thyroïdien et hormonal. Utilisé depuis 3000 ans en Inde." },
    { question: "Quelle plante des Antilles est utilisée contre le diabète de type 2 en médecine traditionnelle ?", answers: ["La cannelle de Ceylan uniquement", "Le corossol, la morelle noire et la carambole — plusieurs plantes antillaises hypoglycémiantes", "Le gingembre uniquement", "Le basilic uniquement"], correct: 1, explanation: "Plusieurs plantes antillaises ont des propriétés hypoglycémiantes étudiées : les feuilles de corossol (Annona muricata), la momordique (margose/bitter melon), les feuilles de goyavier. La médecine créole utilisait ces plantes bien avant la médecine moderne. Des études valident leurs effets sur la glycémie." },
    { question: "Quelles sont les propriétés de l'aloé vera reconnues scientifiquement ?", answers: ["Uniquement hydratant cosmétique", "Cicatrisant, anti-inflammatoire cutané, laxatif (gel interne), soutien immunitaire", "Antibiotique systémique puissant", "Antiviral contre tous les virus"], correct: 1, explanation: "L'aloe vera a des propriétés scientifiquement validées : cicatrisant et anti-inflammatoire topique (brûlures, psoriasis), laxatif stimulant (latex interne — usage limité), soutien immunitaire (acemannan). La FDA américaine reconnaît son usage topique. Plante présente dans tous les jardins antillais." },
    { question: "Qu'est-ce que la phytothérapie et comment diffère-t-elle de la médecine conventionnelle ?", answers: ["C'est exactement la même chose", "L'utilisation thérapeutique des plantes entières ou extraits — approche plus douce avec moins d'effets secondaires mais interactions médicamenteuses possibles", "Une médecine sans preuves scientifiques", "Uniquement pour les maladies chroniques"], correct: 1, explanation: "La phytothérapie utilise les plantes médicinales à des fins thérapeutiques. Elle est reconnue par l'OMS (25% des médicaments modernes sont issus de plantes). Avantages : effets secondaires souvent moindres, approche holistique. Risques : interactions avec médicaments, dosage variable, qualité des produits. Toujours informer son médecin." },
    { question: "Quelles plantes sont reconnues pour leurs propriétés contre l'anxiété et l'insomnie ?", answers: ["Le café et le thé vert", "La valériane, la passiflore, la lavande et la mélisse", "Le ginseng et l'éphédra", "Le millepertuis uniquement"], correct: 1, explanation: "Plantes anxiolytiques et somnifères reconnues : Valériane (raccourcit l'endormissement), Passiflore (anxiété légère), Lavande (aromathérapie prouvée), Mélisse (tension nerveuse). Le millepertuis est prouvé contre la dépression légère à modérée mais a de nombreuses interactions médicamenteuses (à éviter avec anticoagulants, pilule)." },
    { question: "Quelle plante est utilisée depuis l'Antiquité pour ses propriétés antibactériennes et antivirales ?", answers: ["La lavande uniquement", "L'ail (Allium sativum) — l'allicine est un antibactérien naturel puissant", "Le thym uniquement", "Le basilic"], correct: 1, explanation: "L'ail contient de l'allicine (formée quand on l'écrase), un antibactérien naturel puissant. Études prouvant : réduction du cholestérol LDL, effets antiviraux (rhume réduit de 63%), antibactérien contre H. pylori. Hippocrate prescrivait déjà l'ail il y a 2400 ans. Meilleur consommé cru, écrasé, 10 minutes après coupe." },
    { question: "Qu'est-ce que la gemmothérapie, branche de la phytothérapie utilisant les bourgeons ?", answers: ["La thérapie par les pierres précieuses", "L'utilisation des bourgeons et jeunes pousses de plantes, concentrés en facteurs de croissance", "La thérapie par les fleurs de Bach", "L'utilisation des racines uniquement"], correct: 1, explanation: "La gemmothérapie (Dr Pol Henry, années 1950) utilise les bourgeons et jeunes pousses de plantes, les parties les plus concentrées en facteurs de croissance, vitamines et hormones végétales. Ex: bourgeons de cassis (anti-inflammatoire), de bouleau (drainage rénal), de romarin (foie). Macerats glycérinés dilués en D1." },
    { question: "Pourquoi certaines plantes médicinales peuvent-elles être dangereuses malgré leur origine naturelle ?", answers: ["Elles ne peuvent pas être dangereuses car naturelles", "Interactions avec médicaments, dosage excessif, mauvaise identification, contre-indications (grossesse, maladies)", "Uniquement dangereuses pour les enfants", "Seulement si importées"], correct: 1, explanation: "Naturel ne signifie pas sans risque : le millepertuis réduit l'efficacité de la pilule et des anticoagulants. La valériane potentialise les somnifères. Certaines plantes sont hépatotoxiques (tussilage). La digitale est un poison mortel ET le médicament cardiaque le plus utilisé (digoxine). Toujours consulter un professionnel de santé." },
  ],
  tips: ["Le curcuma est 2000% mieux absorbé avec du poivre noir — la combinaison est ancienne dans la cuisine indienne et créole", "La verveine citronnelle antillaise est l'une des plantes médicinales les plus utilisées en Guadeloupe et Martinique", "Naturel ne signifie pas sans risque — informez toujours votre médecin de vos plantes médicinales"],
};
export default quizPlantesMediacinales;
