const quizSymbolisme = {
  title: "Symbolisme & Signes Sacrés du Monde",
  description: "Découvrez la signification profonde des symboles sacrés qui traversent les cultures et les siècles !",
  emoji: "🔯",
  questions: [
    { question: "Que représente l'Ankh, symbole égyptien en forme de croix avec une boucle ?", answers: ["La mort et le deuil", "La vie éternelle et l'union du masculin et du féminin", "La royauté seule", "La guerre et la victoire"], correct: 1, explanation: "L'Ankh est le symbole égyptien de la vie éternelle. La boucle supérieure représente le féminin (la vie), la croix inférieure représente le masculin (la Terre). Tenu par les dieux, il accorde la vie. Aujourd'hui encore très utilisé dans la bijouterie et la spiritualité." },
    { question: "Que symbolise le Vévé de Baron Samedi dans le Vaudou haïtien ?", answers: ["L'amour et le mariage", "La mort, la résurrection et le passage entre les mondes", "La guerre", "La richesse matérielle"], correct: 1, explanation: "Baron Samedi est le Loa de la mort et de la résurrection dans le Vaudou haïtien. Son Vévé (symbole rituel dessiné au sol) représente la croix des cimetières. Il est aussi protecteur de la santé et peut guérir ceux qu'il choisit. Représenté en chapeau haut-de-forme et costume noir." },
    { question: "Que représente l'Étoile de David (étoile à 6 branches) dans la tradition juive ?", answers: ["Les 6 jours de la création", "L'union du divin et de l'humain, du ciel et de la terre", "Les 6 commandements principaux", "L'étoile de Bethléem"], correct: 1, explanation: "L'Étoile de David (Magen David) représente l'union de deux triangles : l'un pointant vers le haut (élan vers Dieu) et l'autre vers le bas (présence divine dans le monde matériel). Elle symbolise la connexion entre le divin et l'humain, et est devenue le symbole du peuple juif." },
    { question: "Que signifie le Om (Aum), son sacré de l'hindouisme et du bouddhisme ?", answers: ["Paix en sanskrit", "Le son primordial de l'univers, la vibration fondamentale de toute existence", "Merci en sanskrit", "Dieu en hindi"], correct: 1, explanation: "Om (Aum) est considéré comme le son originel de l'univers, la vibration fondamentale de toute existence. En méditant sur Om, on se connecte à la conscience universelle. A-U-M représente les trois états de conscience : éveil, rêve et sommeil profond, plus le 4ème état de conscience pure." },
    { question: "Que symbolise le Sankofa, symbole africain Akan représenté par un oiseau regardant en arrière ?", answers: ["L'oubli du passé pour avancer", "Il est toujours temps de revenir en arrière pour récupérer ce qu'on a oublié — honorer ses racines", "La mort des ancêtres", "La migration vers l'Occident"], correct: 1, explanation: "Le Sankofa (peuple Akan, Ghana) montre un oiseau qui avance en regardant en arrière. Sa signification : il faut connaître son passé pour construire son avenir. Ce symbole est central dans la diaspora africaine-caribéenne comme rappel de l'importance des racines et de la mémoire ancestrale." },
    { question: "Que représente la Fleur de Vie, géométrie sacrée retrouvée dans toutes les cultures ?", answers: ["Un motif décoratif sans signification", "Le modèle de base de toute création — la structure mathématique de l'univers", "La croissance des plantes uniquement", "Un symbole militaire antique"], correct: 1, explanation: "La Fleur de Vie est un motif géométrique composé de 19 cercles entrelacés retrouvé dans l'Égypte antique, en Inde, en Chine, au Japon et en Europe. Elle représente le modèle mathématique fondamental de toute création et contient tous les Solides de Platon." },
    { question: "Que symbolise le Trident de Shiva dans l'hindouisme ?", answers: ["La pêche et l'océan", "Les trois aspects divins : création, préservation, destruction — et les trois gunas", "La Trinité chrétienne uniquement", "Les trois océans"], correct: 1, explanation: "Le Trishula (trident) de Shiva symbolise les trois fonctions divines : création (Brahma), préservation (Vishnou) et destruction-transformation (Shiva). Il représente aussi les trois Gunas (qualités de la nature) : Tamas, Rajas et Sattva, et la maîtrise du temps (passé, présent, futur)." },
    { question: "Que représente l'Adinkra Gye Nyame du peuple Akan d'Afrique de l'Ouest ?", answers: ["La puissance du roi", "La suprématie de Dieu — rien ne peut exister sans Dieu", "La fertilité de la terre", "L'amour romantique"], correct: 1, explanation: "Gye Nyame est le symbole Adinkra le plus répandu en Afrique de l'Ouest. Il signifie 'sauf Dieu' et représente l'omniprésence et la toute-puissance divine. Les Adinkra sont des symboles visuels akan (Ghana, Côte d'Ivoire) utilisés sur les tissus, poteries et architecture, chacun portant une sagesse." },
    { question: "Que signifie le symbole du Caducée (deux serpents enroulés autour d'un bâton ailé) ?", answers: ["La guerre et la victoire militaire", "La médecine, l'équilibre des forces contraires et la guérison", "Le commerce uniquement", "La sagesse royale"], correct: 1, explanation: "Le Caducée d'Hermès/Mercure représente l'équilibre des forces opposées (les deux serpents) guidées vers l'élévation (les ailes). Adopté comme symbole médical (bien qu'il soit souvent confondu avec l'Asclépios à un seul serpent, vrai symbole médical). Représente aussi le commerce et la communication." },
    { question: "Que représente l'Ojo de Dios (Œil de Dieu), tissage en losange des cultures amérindiennes ?", answers: ["La malchance", "La protection divine, le regard bienveillant de Dieu sur l'enfant et la famille", "L'œil mauvais", "La puissance chamanique seule"], correct: 1, explanation: "L'Ojo de Dios est un tissage traditionnel des peuples Huichol (Mexique) et d'autres cultures amérindiennes. Fabriqué avec des fils de couleurs vives en forme de losange, il représente le regard protecteur de Dieu. Offert aux enfants pour leur protection, il représente les 4 éléments et les 4 directions." },
  ],
  tips: ["Le Sankofa africain est un message puissant pour la diaspora caribéenne — connaître ses racines pour avancer", "La Fleur de Vie retrouvée dans toutes les cultures suggère une connaissance universelle partagée", "Les symboles sont des langages universels qui transcendent les barrières linguistiques et culturelles"],
};
export default quizSymbolisme;
