/* © Reussitess®971 INPI DSO2026012614 PORINUS Rony 2026 */
const quizPsychologie = {
  title: "Psychologie",
  description: "Comprenez les mécanismes de l'esprit humain !",
  emoji: "🧠",
  questions: [
    { question: "🧠 Qu'est-ce que l'effet Dunning-Kruger ?", answers: ["Un trouble de la personnalité", "Le phénomène où les personnes peu compétentes surestiment leurs capacités, et les experts sous-estiment les leurs", "Une technique de persuasion", "Un biais de confirmation"], correct: 1, explanation: "L'effet Dunning-Kruger décrit deux biais cognitifs : les incompétents ne réalisent pas leur incompétence (ils n'ont pas le recul pour mesurer ce qu'ils ignorent), tandis que les experts doutent de leurs connaissances." },
    { question: "🔄 Qu'est-ce que le biais de confirmation ?", answers: ["Confirmer son mot de passe", "La tendance à chercher, interpréter et mémoriser les informations qui confirment nos croyances préexistantes", "Un trouble obsessionnel", "Une technique de mémorisation"], correct: 1, explanation: "Le biais de confirmation nous pousse à ne remarquer que ce qui valide ce qu'on pense déjà. Si vous croyez que les cryptos sont une arnaque, vous ne verrez que les mauvaises nouvelles crypto. La pensée critique consiste à chercher activement ce qui contredit nos croyances." },
    { question: "💭 Qu'est-ce que la dissonance cognitive ?", answers: ["Un trouble de la parole", "L'inconfort mental ressenti quand nos croyances et nos actions sont contradictoires", "Un type d'hypnose", "Une forme de méditation"], correct: 1, explanation: "La dissonance cognitive (Leon Festinger) est l'état d'inconfort créé par des croyances ou comportements contradictoires. Pour la réduire, on change soit son comportement, soit sa croyance — souvent en se racontant une histoire qui justifie l'incohérence." },
    { question: "😊 Qu'est-ce que la psychologie positive ?", answers: ["Toujours être positif et ignorer les problèmes", "L'étude scientifique de ce qui rend la vie épanouissante : forces, bien-être, résilience et bonheur", "Une forme de thérapie coûteuse", "Un courant anti-psychanalyse"], correct: 1, explanation: "La psychologie positive (Martin Seligman) s'intéresse à ce qui fait que la vie vaut la peine d'être vécue. Elle étudie les émotions positives, le sens, l'engagement et les relations. Ce n'est pas du 'pensée positive' naïf mais une science rigoureuse." },
    { question: "🪞 Qu'est-ce que l'estime de soi ?", answers: ["L'amour de son apparence physique", "La valeur globale qu'on s'accorde à soi-même — notre jugement sur notre propre valeur en tant que personne", "La confiance en ses compétences professionnelles", "Le narcissisme"], correct: 1, explanation: "L'estime de soi est le regard global qu'on porte sur soi-même. Elle diffère de la confiance en soi (croyance en ses capacités dans un domaine spécifique). Une haute estime de soi n'est pas du narcissisme — c'est s'accepter avec ses forces ET ses limites." },
    { question: "🌊 Qu'est-ce que le 'flow' selon Mihaly Csikszentmihalyi ?", answers: ["Un état de relaxation totale", "L'état de concentration optimale où on est complètement absorbé par une activité — le temps s'arrête", "Une technique de respiration", "Un état d'hypnose légère"], correct: 1, explanation: "Le flow est l'état de 'zone' où on est si absorbé par une activité qu'on oublie le temps, la fatigue et soi-même. Il survient quand le défi est parfaitement calibré à nos compétences — ni trop facile (ennui), ni trop difficile (anxiété)." },
  ],
  tips: ["🧠 Connaître ses biais cognitifs est la première étape pour mieux décider", "💭 La méditation est prouvée scientifiquement pour réduire le stress et améliorer la concentration", "🌱 Le cerveau est plastique — on peut toujours apprendre et changer"],
};
export default quizPsychologie;
